<?xml version="1.0" encoding="utf-8"?><Database Name="elearn" Class="ELearningDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PREWIN-PC\SQLEXPRESS;Initial Catalog=elearn;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="elearnConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tblCategory" Member="tblCategories">
    <Type Name="tblCategory">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="tblCategory_tblForumQuestion" Member="tblForumQuestions" ThisKey="Id" OtherKey="FK_CategoryId" Type="tblForumQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.tblForumQuestion" Member="tblForumQuestions">
    <Type Name="tblForumQuestion">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_CategoryId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblCategory_tblForumQuestion" Member="tblCategory" ThisKey="FK_CategoryId" OtherKey="Id" Type="tblCategory" IsForeignKey="true" />
      <Association Name="tblLogin_tblForumQuestion" Member="tblLogin" ThisKey="FK_UserId" OtherKey="Id" Type="tblLogin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblLogin" Member="tblLogins">
    <Type Name="tblLogin">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RollNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_RoleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="tblLogin_tblForumQuestion" Member="tblForumQuestions" ThisKey="Id" OtherKey="FK_UserId" Type="tblForumQuestion" />
      <Association Name="tblLogin_tblForumAnswer" Member="tblForumAnswers" ThisKey="Id" OtherKey="FK_UserId" Type="tblForumAnswer" />
      <Association Name="tblLogin_tblAssignment" Member="tblAssignments" ThisKey="Id" OtherKey="FK_StaffId" Type="tblAssignment" />
      <Association Name="tblLogin_tblNote" Member="tblNotes" ThisKey="Id" OtherKey="FK_StaffId" Type="tblNote" />
      <Association Name="tblRole_tblLogin" Member="tblRole" ThisKey="FK_RoleId" OtherKey="Id" Type="tblRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblQuestion" Member="tblQuestions">
    <Type Name="tblQuestion">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Fk_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QuestionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="OptionA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblQuestionTitle_tblQuestion" Member="tblQuestionTitle" ThisKey="Fk_TitleId" OtherKey="Id" Type="tblQuestionTitle" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblQuestionTitle" Member="tblQuestionTitles">
    <Type Name="tblQuestionTitle">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QuestionTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblQuestionTitle_tblQuestion" Member="tblQuestions" ThisKey="Id" OtherKey="Fk_TitleId" Type="tblQuestion" />
    </Type>
  </Table>
  <Table Name="dbo.tblRoles" Member="tblRoles">
    <Type Name="tblRole">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="tblRole_tblLogin" Member="tblLogins" ThisKey="Id" OtherKey="FK_RoleId" Type="tblLogin" />
    </Type>
  </Table>
  <Table Name="dbo.tblSubjects" Member="tblSubjects">
    <Type Name="tblSubject">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="tblSubject_tblTitle" Member="tblTitles" ThisKey="Id" OtherKey="FK_SubjectId" Type="tblTitle" />
    </Type>
  </Table>
  <Table Name="dbo.tblTitles" Member="tblTitles">
    <Type Name="tblTitle">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_SubjectId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="tblSubject_tblTitle" Member="tblSubject" ThisKey="FK_SubjectId" OtherKey="Id" Type="tblSubject" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblForumAnswer" Member="tblForumAnswers">
    <Type Name="tblForumAnswer">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_QuestionId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="tblLogin_tblForumAnswer" Member="tblLogin" ThisKey="FK_UserId" OtherKey="Id" Type="tblLogin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblAssignments" Member="tblAssignments">
    <Type Name="tblAssignment">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Topic" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AssignNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_StudentId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tblLogin_tblAssignment" Member="tblLogin" ThisKey="FK_StaffId" OtherKey="Id" Type="tblLogin" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblNotes" Member="tblNotes">
    <Type Name="tblNote">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_FileId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="tblLogin_tblNote" Member="tblLogin" ThisKey="FK_StaffId" OtherKey="Id" Type="tblLogin" IsForeignKey="true" />
      <Association Name="tblFile_tblNote" Member="tblFile" ThisKey="FK_FileId" OtherKey="Id" Type="tblFile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tblFiles" Member="tblFiles">
    <Type Name="tblFile">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Association Name="tblFile_tblNote" Member="tblNotes" ThisKey="Id" OtherKey="FK_FileId" Type="tblNote" />
    </Type>
  </Table>
  <Function Name="dbo.sp_tblLoginNewDeleteCommand" Method="sp_tblLoginNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblLoginNewInsertCommand" Method="sp_tblLoginNewInsertCommand">
    <Parameter Name="RollNumber" Parameter="rollNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Class" Parameter="class" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="EmailID" Parameter="emailID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreatedDate" Parameter="createdDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastLogin" Parameter="lastLogin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FK_RoleId" Parameter="fK_RoleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="PostalCode" Parameter="postalCode" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblLoginNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RollNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_RoleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblLoginNewSelectCommand" Method="sp_tblLoginNewSelectCommand">
    <ElementType Name="sp_tblLoginNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RollNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_RoleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblLoginNewUpdateCommand" Method="sp_tblLoginNewUpdateCommand">
    <Parameter Name="RollNumber" Parameter="rollNumber" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Class" Parameter="class" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Department" Parameter="department" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="EmailID" Parameter="emailID" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="CreatedDate" Parameter="createdDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="LastLogin" Parameter="lastLogin" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FK_RoleId" Parameter="fK_RoleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Address" Parameter="address" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="PostalCode" Parameter="postalCode" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblLoginNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="RollNumber" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Class" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Department" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EmailID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_RoleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PostalCode" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSubjectsNewDeleteCommand" Method="sp_tblSubjectsNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblSubjectsNewInsertCommand" Method="sp_tblSubjectsNewInsertCommand">
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="sp_tblSubjectsNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSubjectsNewSelectCommand" Method="sp_tblSubjectsNewSelectCommand">
    <ElementType Name="sp_tblSubjectsNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblSubjectsNewUpdateCommand" Method="sp_tblSubjectsNewUpdateCommand">
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblSubjectsNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTitlesNewDeleteCommand" Method="sp_tblTitlesNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblTitlesNewInsertCommand" Method="sp_tblTitlesNewInsertCommand">
    <Parameter Name="TitleName" Parameter="titleName" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FK_SubjectId" Parameter="fK_SubjectId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblTitlesNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_SubjectId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTitlesNewSelectCommand" Method="sp_tblTitlesNewSelectCommand">
    <ElementType Name="sp_tblTitlesNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_SubjectId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblTitlesNewUpdateCommand" Method="sp_tblTitlesNewUpdateCommand">
    <Parameter Name="TitleName" Parameter="titleName" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FK_SubjectId" Parameter="fK_SubjectId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblTitlesNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_SubjectId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblQuestionNewDeleteCommand" Method="sp_tblQuestionNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblQuestionNewInsertCommand" Method="sp_tblQuestionNewInsertCommand">
    <Parameter Name="Fk_TitleId" Parameter="fk_TitleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="QuestionNumber" Parameter="questionNumber" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Question" Parameter="question" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="OptionA" Parameter="optionA" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="OptionB" Parameter="optionB" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="OptionC" Parameter="optionC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="OptionD" Parameter="optionD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Answer" Parameter="answer" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_tblQuestionNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fk_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QuestionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="OptionA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblQuestionNewSelectCommand" Method="sp_tblQuestionNewSelectCommand">
    <ElementType Name="sp_tblQuestionNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fk_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QuestionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="OptionA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblQuestionNewUpdateCommand" Method="sp_tblQuestionNewUpdateCommand">
    <Parameter Name="Fk_TitleId" Parameter="fk_TitleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="QuestionNumber" Parameter="questionNumber" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Question" Parameter="question" Type="System.String" DbType="NVarChar(1000)" />
    <Parameter Name="OptionA" Parameter="optionA" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="OptionB" Parameter="optionB" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="OptionC" Parameter="optionC" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="OptionD" Parameter="optionD" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Answer" Parameter="answer" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblQuestionNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Fk_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="QuestionNumber" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="OptionA" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionB" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionC" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="OptionD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Answer" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblQuestionTitleNewDeleteCommand" Method="sp_tblQuestionTitleNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblQuestionTitleNewInsertCommand" Method="sp_tblQuestionTitleNewInsertCommand">
    <Parameter Name="QuestionTitle" Parameter="questionTitle" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_tblQuestionTitleNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="QuestionTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblQuestionTitleNewSelectCommand" Method="sp_tblQuestionTitleNewSelectCommand">
    <ElementType Name="sp_tblQuestionTitleNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="QuestionTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblQuestionTitleNewUpdateCommand" Method="sp_tblQuestionTitleNewUpdateCommand">
    <Parameter Name="QuestionTitle" Parameter="questionTitle" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblQuestionTitleNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="QuestionTitle" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblAssignmentsNewDeleteCommand" Method="sp_tblAssignmentsNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblAssignmentsNewInsertCommand" Method="sp_tblAssignmentsNewInsertCommand">
    <Parameter Name="FilePath" Parameter="filePath" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FK_StaffId" Parameter="fK_StaffId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Topic" Parameter="topic" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="AssignNum" Parameter="assignNum" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FK_StudentId" Parameter="fK_StudentId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Status" Parameter="status" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="sp_tblAssignmentsNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Topic" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AssignNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_StudentId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblAssignmentsNewSelectCommand" Method="sp_tblAssignmentsNewSelectCommand">
    <ElementType Name="sp_tblAssignmentsNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Topic" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AssignNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_StudentId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblAssignmentsNewUpdateCommand" Method="sp_tblAssignmentsNewUpdateCommand">
    <Parameter Name="FilePath" Parameter="filePath" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FK_StaffId" Parameter="fK_StaffId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Topic" Parameter="topic" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="AssignNum" Parameter="assignNum" Type="System.Int32" DbType="Int" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FK_StudentId" Parameter="fK_StudentId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Status" Parameter="status" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblAssignmentsNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Topic" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AssignNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_StudentId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_select" Method="sp_select">
    <Parameter Name="StaffId" Parameter="staffId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Status" Parameter="status" Type="System.Boolean" DbType="Bit" />
    <ElementType Name="sp_selectResult">
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Topic" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="AssignNum" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_StudentId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblNotesNewDeleteCommand" Method="sp_tblNotesNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblNotesNewInsertCommand" Method="sp_tblNotesNewInsertCommand">
    <Parameter Name="FK_StaffId" Parameter="fK_StaffId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FK_FileId" Parameter="fK_FileId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblNotesNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_FileId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblNotesNewSelectCommand" Method="sp_tblNotesNewSelectCommand">
    <ElementType Name="sp_tblNotesNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_FileId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblNotesNewUpdateCommand" Method="sp_tblNotesNewUpdateCommand">
    <Parameter Name="FK_StaffId" Parameter="fK_StaffId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FK_FileId" Parameter="fK_FileId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblNotesNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_StaffId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_FileId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblFilesNewDeleteCommand" Method="sp_tblFilesNewDeleteCommand">
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_tblFilesNewInsertCommand" Method="sp_tblFilesNewInsertCommand">
    <Parameter Name="FK_TitleId" Parameter="fK_TitleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FilePath" Parameter="filePath" Type="System.String" DbType="NVarChar(500)" />
    <ElementType Name="sp_tblFilesNewInsertCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblFilesNewSelectCommand" Method="sp_tblFilesNewSelectCommand">
    <ElementType Name="sp_tblFilesNewSelectCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_tblFilesNewUpdateCommand" Method="sp_tblFilesNewUpdateCommand">
    <Parameter Name="FK_TitleId" Parameter="fK_TitleId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FilePath" Parameter="filePath" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Original_Id" Parameter="original_Id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Id" Parameter="id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_tblFilesNewUpdateCommandResult">
      <Column Name="Id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_TitleId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_select_file" Method="sp_select_file">
    <ElementType Name="sp_select_fileResult">
      <Column Name="TitleName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FilePath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>