



<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - October - 2010 ::</title>
</head>
<script language="JavaScript">

<!--



function NewWindow(url) {                       

                var hWnd = window.open(url,"Window","width=700,height=330,resizable=no,scrollbars=yes,left=100,top=25");

                if (hWnd.focus != null) hWnd.focus();

        }



// -->

</script>
<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top1.php"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#EFEFE9" colspan="3" align=center height="10">
            <div align="left">
				<table border="0" style="border-collapse: collapse" width="237" cellpadding="0">
					<tr>
						<td width="16" bgcolor="#FF0000" height="30" style="border-left-style: solid; border-left-width: 1px; border-right-width: 1px; border-top-width: 1px; border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#000000">&nbsp;</td>
						<td valign="bottom" style="border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#FF0000" width="204">
            <p align="left" style="margin-left: 5px">
			<b><font face="Verdana" size="1"><a name="top">BEYOND BOARDROOMS</a></font></b></td>
					</tr>
				</table>
			</div>
			</td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	          <tr> 
                <td height="18"> <b></b> 
				<p align="justify" style="margin-left: 10px; margin-right: 10px" dir="ltr"> 
                    <b> 
                    <font face="Verdana" size="4" color="#C00000"><br>
					Penchant for innovation</font><font face="Verdana" size="4" color="#CC3333"><br>
					</font></b><font face="Verdana" size="2"><b><br>
					</b></font><b><font face="Verdana" size="2">Ghaya Al Barwani 
					capitalises on her abilities to adapt to changes and take 
					decisions. Muhammed Nafie reports</font></b><font face="Verdana" size="1"><br>
					<br>
					</font> 
				<font size="1" face="Verdana, Arial, Helvetica, sans-serif">
                    <b> 
                    <img src="images/oct_beyond1.jpg" hspace="9" vspace="5" border="0" style="border: 1px solid #C0C0C0; " align="right"></b></font><font face="Verdana" size="1"><b>Ghaya 
					Al Barwani</b>, Head of Marketing of Ahli Bank, draws her 
					inspiration from the two maxims that she used to hear from 
					her superiors: Jedi Master Yoda’s famous “Do or Do Not, 
					there is no try” and “QED – Quite Easily Done.” The secret 
					behind her rise to the top echelons of the corporate sector 
					has been the indefatigable spirit generated by these two 
					‘favourite phrases’ which inspire her daily.<br>
					<br>
					Ghaya’s abilities to adapt to changes helped her brave all 
					challenges and scale new heights in her professional life. 
					Although Ghaya originally studied to be a town planner, she 
					started her career with Citibank where she could develop and 
					brush up her financial skills for four and half years. Later 
					she moved to BankMuscat. Meanwhile, while working in Bank 
					Muscat, she secured an MBA (Finance) from Leicester 
					University which opened up new opportunities and 
					responsibilities in front of her. She says, “I believe that 
					my abilities to adapt to changes and take decisions are part 
					of my core strengths. I capitalise on these strengths on a 
					regular basis, to enable the bank’s business and 
					communication to adapt thus remaining competitive.<br>
					<br>
					</font><font face="Verdana" color="#000080"><b>Taking charge</b></font><font face="Verdana" size="1"><br>
					<br>
					Ghaya joined ahlibank two months after its inception in 
					2008. Under the guidance of the cooperative executive 
					management team of the bank, she worked on the development 
					and implementation of the retail products and services and 
					the general communications strategy of the bank.<br>
					<br>
					She believes that the management style of each team leader 
					varies and is influenced by the overall organisational 
					style, the task at hand and the level of expertise of the 
					team members. She says, “At ahlibank, I am fortunate enough 
					to work in an environment that invites and encourages the 
					participation of all staff members to grow and develop the 
					bank. Working with a professional team of ahlibankers and 
					suppliers encouraged me to be more participative in 
					management delegating responsibilities as warranted”. <br>
					<br>
					She does not claim to have found a balance between her work 
					and family commitments. However, she is happy that her 
					family understands her work commitments and her organisation 
					greatly appreciates that each individual needs to honour his 
					or her commitments physically, socially, mentally and 
					emotionally. <br>
					<br>
					Referring to her role models in life, Ghaya says, “I have 
					several role models and people who have supported me, 
					starting from my parents who continue to evaluate and advise 
					me professionally to superiors, colleagues, friends of 
					family and friends who help me and inspire me daily.” <br>
					She spends most of her leisure time with family and friends 
					watching comedy shows, going for out camping, driving 
					off-road and enjoying delicious barbeques. Ghaya would like 
					to travel to old metropolitan cities which offer a synthesis 
					of the richness of past and the glitter of modernity. “My 
					favourite cities include Cairo, Paris, London and Berlin. I 
					look forward to enjoying more of the cities in Indian 
					Subcontinent,” she says.<br>
					<br>
					<br>
					&nbsp;</font></p>
				<div align="center">
						<table class="small_text" id="table42" style="BORDER-COLLAPSE: collapse" borderColor="#ffffff" cellSpacing="0" cellPadding="0" width="413" border="1" height="45">
							<tr>
								<td width="401" bgColor="#d9eef9" align="right" height="100">
								<p style="margin: 1 5; line-height:150%" align="left">
                    <b><font color="#C00000" face="Verdana" size="1">Education</font></b><p style="margin: 1 5; line-height:150%" align="left">
								- <font face="Verdana" size="1">MBA (Finance) from Leicester 
					University<br><font color="#C00000"><b>Work experience</b></font></font></p>
								<p style="margin: 1 5; line-height:150%" align="left">
								<font face="Verdana" size="1">-
					Citibank, BankMuscat and Ahli Bank<br>
								</font>
								<font color="#C00000" face="Verdana" size="1">
								<b>Leisure<br>
								</b></font><font face="Verdana" size="1">-
					Watching comedy shows, outdoor camping, driving off-road</font></p>
								<p style="margin: 1 5; line-height:150%" align="left">
								<font face="Verdana" size="1">and 
					travelling</font></td>
							</tr>
							</table>
					</div>
				<p align="justify" style="margin-left: 10px; margin-right: 10px" dir="ltr"> 
                    <font face="Verdana" size="1"><br>
&nbsp;</font></p>                </td>
	</tr>
	          <tr> 
                <td height="18">                </td>
	</tr>
	          <tr> 
                <td height="18"> 

<p align="right" dir="ltr" style="margin-left: 5px; margin-right:5px"><font face="Verdana" size="1">
						<a href="#top">Top^</a></font></p>

				</td>
	</tr>
	          </table>

                    <hr color="#CC3333">
            </td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
</table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>

        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?></body></html>&nbsp;