<?	session_start();?>
<?	session_register("id");
	if(!$HTTP_SESSION_VARS["id"]=="")
	{?>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - March - 2005 ::</title>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top1.php"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="5" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#FFFCE8" colspan="3" align=center><b>



<? if(!$HTTP_SESSION_VARS["id"]==""){echo "<font face=Verdana size=2 color=#000000>Welcome&nbsp;&nbsp;</font><font face=Verdana size=2 color=red><i>".$HTTP_SESSION_VARS["id"]."!</i></font>
            ";}else{echo$HTTP_SESSION_VARS["mes"];$HTTP_SESSION_VARS["mes"]="";}?>
              </b></td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF">

<p align="justify" dir="ltr"><font face="Verdana" size="4" color="#FF0000">Stock 
swings<br>
</font><font face="Verdana" size="1"><br>
<b>Khalid Al-Yahmadi attempts to identify the forces that are responsible for 
the movement of a stock’s price on the bourses</b><br>
<br>
</font><b><font face="Verdana" size="3">S</font></b><font face="Verdana" size="1">tock 
prices move up or down in the marketplace as supply meets demand. Since the 
beginning of stock play, investors have tried to figure out the forces that move 
stock prices so that they can buy undervalued stocks and sell overvalued ones. 
Although there is no clear cut formula that tells us exactly how a stock price 
might behave, I will try in this column to pinpoint some of the forces that I 
believe move stock prices up or down. <br>
Your goal as an investor is not to be right all the time – rather, it is to make 
big money when you are right and to get out early when you are otherwise. 
Therefore, to make big money, you have to buy the very best stocks in the 
market.<br>
<br>
<b>Back to basics</b><br>
I believe that a company’s profitability, represented by earnings per share 
(EPS), is one of the most important factors that impact the stock price. 
Companies that show consistent earnings improvement, and strong profit margins 
coupled by a high return on equity (ROE) are the biggest winners. You should be 
looking for strong increases in quarterly sales and earnings compared to the 
same quarter the year before. <br>
<br>
Beside quarterly sales and earnings increases, you want to see growth in annual 
sales and earnings. Although the range will vary from market to market, a 
company has to show a growth of between 20 and 30 per cent in earnings for the 
previous three years to qualify as growing consistently. In addition, a big 
winner should maintain a return on equity of 17 per cent or more. <br>
<br>
In its is simplest form, the value of a company is the product of its ROE and 
beginning book value of equity divided by its cost of invested capital – i.e., 
the return required by capital providers. Therefore, if a company can earn a 
return on its employed capital of more than the cost of capital it is using, 
then a value will be created and the stock price will increase and vice-versa.<br>
<br>
However, one should be careful when analysing company profitability or its EPS. 
A lot of executives apparently believe that if they can figure out a way to 
boost reported EPS, their prices will go up even if the higher EPS does not 
represent any underlying economic change. Therefore, EPS manipulation is one of 
the oldest professions that managements utilise to boost their share prices. <br>
<br>
To protect themselves, however, investors should evaluate the quality of EPS. 
EPS is calculated by dividing net income by the total common shares outstanding. 
It is calculated using accrual basis accounting; so, it might not represent the 
actual cash the company has generated. However, financial theory says that the 
value of a stock is worth no more than all of the future cash flows expected to 
be generated by the firm discounted by an appropriate risk-adjusted rate. So, 
‘Cash is King’! <br>
<br>
The best way to evaluate the quality of EPS is to compare it to operating cash 
flow per share. The company can show a positive earning on the income statement 
while also bearing a negative cash flow. This is not a good situation to be in 
for a long time, because it means that the company has to borrow money to keep 
operating. A negative cash flow also indicates that there is a fundamental 
operating problem: either inventory is not selling or receivables are not 
getting collected. <br>
<br>
If operating cash flow per share (operating cash flow divided by the number of 
shares outstanding) is greater than reported EPS, earnings are of a high quality 
because the company is generating more cash than is reported on the income 
statement. Reported EPS therefore understates the profitability of the company.<br>
<br>
If, on the other hand, cash flow per share is less than reported EPS, it means 
that the company is generating less cash than is represented by reported EPS. In 
this case, EPS is of low quality because it does not reflect the negative 
operating results of the company and overstates what I feel are the true ‘cash’ 
operating results.<br>
<br>
<b>Technical talk</b><br>
Besides fundamental factors, there are a few technical factors that I think are 
important. Relative Price Strength (RPS) is one key indicator that shows you 
what value the market itself places upon a stock. We calculate the RPS rating by 
taking a stock’s price one year ago and its price today, calculating the 
percentage change and then comparing it to all other stocks over the same 
period. Stocks that have a rating of 80 or higher should be selected.<br>
<br>
Another factor is liquidity, which refers to how much investor interest and 
attention a specific stock receives. A stock like Oman International Bank is 
highly liquid and, therefore, highly responsive to material news. Trading volume 
is one proxy for liquidity.<br>
The last factor I consider is market sentiment – which refers to the psychology 
of market participants individually and collectively. Market sentiment is often 
subjective, biased and obstinate. For example, you can make a solid judgement 
about a stock’s future growth prospects, and the future may even confirm your 
projections, but in the short term, the market may myopically dwell on a single 
piece of news that keeps the stock artificially high or low. This happens 
frequently in our stock market.<br>
<br>
<b>In conclusion</b><br>
Generally, there are two sets of factors that impact stock prices. Earnings or 
cash flows, sales, long-term growth, and reinvestment rate are among the most 
important fundamental factors. Technical factors like relative price strength, 
liquidity and market sentiment are also very important.<br>
<br>
Different types of investors depend on different factors. If you are a 
short-term investor or a trader, you should incorporate or even prioritise 
technical factors. However, if you are a long-term investor, you should 
prioritise fundamentals and recognise that technical factors play an important 
role.<br>
<br>
<i>The author is Investment Manager, Al Madina Investment &amp; Financial Services. 
The views contained within this column are those of the author and do not 
necessarily represent those of OER or his employer. The publisher does not 
accept responsibility for any loss occasioned to any person or organisation 
acting or refraining as a result of material in this publication.</i></font></p>

                    <hr color="#CC3333">
                    </td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?>
        </body>
        </html>
        <?}
else 
Header("Location:/inc/error.php");
?>