<?xml version="1.0" encoding="utf-8"?><Database Name="OnlineExam" Class="OnlineExamDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ICONSTECH\SQLEXPRESS;Initial Catalog=OnlineExam;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OnlineExamConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.OnlineCategory" Member="OnlineCategories">
    <Type Name="OnlineCategory">
      <Column Name="CategoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="OnlineCategory_OnlineQuestion" Member="OnlineQuestions" ThisKey="CategoryId" OtherKey="FK_Category" Type="OnlineQuestion" />
      <Association Name="OnlineCategory_OnlineResultMark" Member="OnlineResultMarks" ThisKey="CategoryId" OtherKey="FK_MarkType" Type="OnlineResultMark" />
    </Type>
  </Table>
  <Table Name="dbo.OnlineOptions" Member="OnlineOptions">
    <Type Name="OnlineOption">
      <Column Name="OptionId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="OptionName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OptionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_QuestionId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="OnlineOption_OnlineQuestion" Member="OnlineQuestions" ThisKey="OptionId" OtherKey="FK_Answer" Type="OnlineQuestion" />
      <Association Name="OnlineQuestion_OnlineOption" Member="OnlineQuestion" ThisKey="FK_QuestionId" OtherKey="QuestionId" Type="OnlineQuestion" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OnlineQuestion" Member="OnlineQuestions">
    <Type Name="OnlineQuestion">
      <Column Name="QuestionId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Imageurl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FK_Answer" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_Category" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="OnlineQuestion_OnlineOption" Member="OnlineOptions" ThisKey="QuestionId" OtherKey="FK_QuestionId" Type="OnlineOption" />
      <Association Name="OnlineOption_OnlineQuestion" Member="OnlineOption" ThisKey="FK_Answer" OtherKey="OptionId" Type="OnlineOption" IsForeignKey="true" />
      <Association Name="OnlineCategory_OnlineQuestion" Member="OnlineCategory" ThisKey="FK_Category" OtherKey="CategoryId" Type="OnlineCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OnlineRegistration" Member="OnlineRegistrations">
    <Type Name="OnlineRegistration">
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="OnlineRegistration_OnlineResult" Member="OnlineResults" ThisKey="UserId" OtherKey="FK_UserId" Type="OnlineResult" />
    </Type>
  </Table>
  <Table Name="dbo.OnlineResult" Member="OnlineResults">
    <Type Name="OnlineResult">
      <Column Name="ResultId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FK_UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OnlineResult_OnlineResultMark" Member="OnlineResultMarks" ThisKey="ResultId" OtherKey="FK_ResultId" Type="OnlineResultMark" />
      <Association Name="OnlineRegistration_OnlineResult" Member="OnlineRegistration" ThisKey="FK_UserId" OtherKey="UserId" Type="OnlineRegistration" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OnlineResultMarks" Member="OnlineResultMarks">
    <Type Name="OnlineResultMark">
      <Column Name="MarkId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_MarkType" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_ResultId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="OnlineCategory_OnlineResultMark" Member="OnlineCategory" ThisKey="FK_MarkType" OtherKey="CategoryId" Type="OnlineCategory" IsForeignKey="true" />
      <Association Name="OnlineResult_OnlineResultMark" Member="OnlineResult" ThisKey="FK_ResultId" OtherKey="ResultId" Type="OnlineResult" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_OnlineCategoryNewDeleteCommand" Method="sp_OnlineCategoryNewDeleteCommand">
    <Parameter Name="Original_CategoryId" Parameter="original_CategoryId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_OnlineCategoryNewInsertCommand" Method="sp_OnlineCategoryNewInsertCommand">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="NVarChar(100)" />
    <ElementType Name="sp_OnlineCategoryNewInsertCommandResult">
      <Column Name="CategoryId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineCategoryNewSelectCommand" Method="sp_OnlineCategoryNewSelectCommand">
    <ElementType Name="sp_OnlineCategoryNewSelectCommandResult">
      <Column Name="CategoryId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineCategoryNewUpdateCommand" Method="sp_OnlineCategoryNewUpdateCommand">
    <Parameter Name="Category" Parameter="category" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Original_CategoryId" Parameter="original_CategoryId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="CategoryId" Parameter="categoryId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineCategoryNewUpdateCommandResult">
      <Column Name="CategoryId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineOptionsNewDeleteCommand" Method="sp_OnlineOptionsNewDeleteCommand">
    <Parameter Name="Original_OptionId" Parameter="original_OptionId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_OnlineOptionsNewInsertCommand" Method="sp_OnlineOptionsNewInsertCommand">
    <Parameter Name="OptionName" Parameter="optionName" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="OptionType" Parameter="optionType" Type="System.Int32" DbType="Int" />
    <Parameter Name="FK_QuestionId" Parameter="fK_QuestionId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineOptionsNewInsertCommandResult">
      <Column Name="OptionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="OptionName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OptionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_QuestionId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineOptionsNewSelectCommand" Method="sp_OnlineOptionsNewSelectCommand">
    <ElementType Name="sp_OnlineOptionsNewSelectCommandResult">
      <Column Name="OptionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="OptionName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OptionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_QuestionId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineOptionsNewUpdateCommand" Method="sp_OnlineOptionsNewUpdateCommand">
    <Parameter Name="OptionName" Parameter="optionName" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="OptionType" Parameter="optionType" Type="System.Int32" DbType="Int" />
    <Parameter Name="FK_QuestionId" Parameter="fK_QuestionId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_OptionId" Parameter="original_OptionId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="OptionId" Parameter="optionId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineOptionsNewUpdateCommandResult">
      <Column Name="OptionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="OptionName" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OptionType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_QuestionId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineQuestionNewDeleteCommand" Method="sp_OnlineQuestionNewDeleteCommand">
    <Parameter Name="Original_QuestionId" Parameter="original_QuestionId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_OnlineQuestionNewInsertCommand" Method="sp_OnlineQuestionNewInsertCommand">
    <Parameter Name="Question" Parameter="question" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Imageurl" Parameter="imageurl" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="FK_Answer" Parameter="fK_Answer" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FK_Category" Parameter="fK_Category" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineQuestionNewInsertCommandResult">
      <Column Name="QuestionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Imageurl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FK_Answer" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_Category" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineQuestionNewSelectCommand" Method="sp_OnlineQuestionNewSelectCommand">
    <ElementType Name="sp_OnlineQuestionNewSelectCommandResult">
      <Column Name="QuestionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Imageurl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FK_Answer" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_Category" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineQuestionNewUpdateCommand" Method="sp_OnlineQuestionNewUpdateCommand">
    <Parameter Name="Question" Parameter="question" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Imageurl" Parameter="imageurl" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="FK_Answer" Parameter="fK_Answer" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FK_Category" Parameter="fK_Category" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_QuestionId" Parameter="original_QuestionId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="QuestionId" Parameter="questionId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineQuestionNewUpdateCommandResult">
      <Column Name="QuestionId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Question" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Imageurl" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="FK_Answer" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_Category" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineRegistrationNewDeleteCommand" Method="sp_OnlineRegistrationNewDeleteCommand">
    <Parameter Name="Original_UserId" Parameter="original_UserId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_OnlineRegistrationNewSelectCommand" Method="sp_OnlineRegistrationNewSelectCommand">
    <ElementType Name="sp_OnlineRegistrationNewSelectCommandResult">
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineRegistrationNewUpdateCommand" Method="sp_OnlineRegistrationNewUpdateCommand">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Original_UserId" Parameter="original_UserId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="UserId" Parameter="userId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineRegistrationNewUpdateCommandResult">
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineRegistrationNewInsertCommand" Method="sp_OnlineRegistrationNewInsertCommand">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Date" Parameter="date" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="sp_OnlineRegistrationNewInsertCommandResult">
      <Column Name="UserId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineResultMarksNewDeleteCommand" Method="sp_OnlineResultMarksNewDeleteCommand">
    <Parameter Name="Original_MarkId" Parameter="original_MarkId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_OnlineResultMarksNewInsertCommand" Method="sp_OnlineResultMarksNewInsertCommand">
    <Parameter Name="Mark" Parameter="mark" Type="System.Int32" DbType="Int" />
    <Parameter Name="FK_MarkType" Parameter="fK_MarkType" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FK_ResultId" Parameter="fK_ResultId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineResultMarksNewInsertCommandResult">
      <Column Name="MarkId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_MarkType" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_ResultId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineResultMarksNewSelectCommand" Method="sp_OnlineResultMarksNewSelectCommand">
    <ElementType Name="sp_OnlineResultMarksNewSelectCommandResult">
      <Column Name="MarkId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_MarkType" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_ResultId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineResultMarksNewUpdateCommand" Method="sp_OnlineResultMarksNewUpdateCommand">
    <Parameter Name="Mark" Parameter="mark" Type="System.Int32" DbType="Int" />
    <Parameter Name="FK_MarkType" Parameter="fK_MarkType" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FK_ResultId" Parameter="fK_ResultId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_MarkId" Parameter="original_MarkId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="MarkId" Parameter="markId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineResultMarksNewUpdateCommandResult">
      <Column Name="MarkId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_MarkType" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FK_ResultId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineResultNewDeleteCommand" Method="sp_OnlineResultNewDeleteCommand">
    <Parameter Name="Original_ResultId" Parameter="original_ResultId" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_OnlineResultNewInsertCommand" Method="sp_OnlineResultNewInsertCommand">
    <Parameter Name="FK_UserId" Parameter="fK_UserId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Mark" Parameter="mark" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_OnlineResultNewInsertCommandResult">
      <Column Name="ResultId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineResultNewSelectCommand" Method="sp_OnlineResultNewSelectCommand">
    <ElementType Name="sp_OnlineResultNewSelectCommandResult">
      <Column Name="ResultId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_OnlineResultNewUpdateCommand" Method="sp_OnlineResultNewUpdateCommand">
    <Parameter Name="FK_UserId" Parameter="fK_UserId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Mark" Parameter="mark" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_ResultId" Parameter="original_ResultId" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="ResultId" Parameter="resultId" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_OnlineResultNewUpdateCommandResult">
      <Column Name="ResultId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FK_UserId" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mark" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>