INSERT INTO TB_FAMILY 
	(
		FAMILY_NAME
	,	FOOT_NOTES
	,	PARENT_FAMILY_ID
	,	ROOT_FAMILY
	,	STATUS
	,	PRODUCT_TABLE_STRUCTURE
	,	DISPLAY_TABLE_HEADER
	,	CATEGORY_ID
	)
SELECT 
		FAMILY_NAME
	,	FOOT_NOTES
	,	966608
	,	0
	,	STATUS
	,	PRODUCT_TABLE_STRUCTURE
	,	DISPLAY_TABLE_HEADER
	,	'HHHSUB1' 
FROM TB_FAMILY WHERE FAMILY_ID=966614

DECLARE @NEW_FAMILY INT = SCOPE_IDENTITY();

INSERT INTO TB_CATALOG_FAMILY 
	(	
		CATALOG_ID
	,	FAMILY_ID
	,	SORT_ORDER
	,	CATEGORY_ID
	)
SELECT 
		CATALOG_ID
	,	@NEW_FAMILY
	,	(SELECT MAX(SORT_ORDER) + 1 FROM TB_SUBFAMILY WHERE FAMILY_ID = 966608)
	,	'HHHSUB1' 
FROM TB_CATALOG_FAMILY WHERE FAMILY_ID =966614 AND CATALOG_ID=2

INSERT INTO TB_SUBFAMILY 
	(
		SUBFAMILY_ID
	,	FAMILY_ID
	,	SORT_ORDER
	)
VALUES 
	(	
		@NEW_FAMILY
	,	966608
	,	(SELECT MAX(SORT_ORDER) + 1 FROM TB_SUBFAMILY WHERE (FAMILY_ID = 966608))
	) 

SELECT * FROM TB_CATALOG_FAMILY WHERE FAMILY_ID =966614 AND CATALOG_ID=2
SELECT MAX(SORT_ORDER) + 1 FROM TB_SUBFAMILY WHERE (FAMILY_ID = 966608)
SELECT * FROM TB_SUBFAMILY WHERE FAMILY_ID = 966608

SELECT COUNT(*) FROM TB_SUBFAMILY WHERE SUBFAMILY_ID=966613
SELECT * FROM TB_FAMILY