--VIEW
SELECT * FROM TB_FAMILY ORDER BY CREATED_DATE DESC
SELECT * FROM TB_SUBFAMILY ORDER BY CREATED_DATE DESC
	SELECT * FROM TB_SUBFAMILY ORDER BY CREATED_DATE DESC
SELECT * FROM TB_CATALOG_FAMILY ORDER BY CREATED_DATE DESC 
--DELETE TB_CATALOG_FAMILY WHERE FAMILY_ID=966602
SELECT * FROM TB_FAMILY_SPECS ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_FAMILY_TABLE_STRUCTURE ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PRODUCT ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_SPECS WHERE ATTRIBUTE_ID=1 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PARTS_KEY ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_FAMILY ORDER BY CREATED_DATE DESC
	
SELECT * FROM TB_CATALOG_PRODUCT WHERE CATALOG_ID IN (1,2) ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_FAMILY_ATTR_LIST ORDER BY CREATED_DATE DESC 
--SOURCE
SELECT * FROM TB_FAMILY WHERE CATEGORY_ID='MMC002' AND FAMILY_ID=966601 ORDER BY CREATED_DATE DESC
SELECT * FROM TB_SUBFAMILY WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC
	SELECT * FROM TB_SUBFAMILY WHERE SUBFAMILY_ID=966601 ORDER BY CREATED_DATE DESC
SELECT * FROM TB_CATALOG_FAMILY WHERE CATEGORY_ID='MMC002' AND FAMILY_ID=966601 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_FAMILY_SPECS WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_FAMILY_TABLE_STRUCTURE WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PRODUCT WHERE CATEGORY_ID='MMC002' ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_SPECS WHERE ATTRIBUTE_ID=1 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PARTS_KEY WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_FAMILY WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_CATALOG_PRODUCT WHERE CATALOG_ID IN (1,2) ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_FAMILY_ATTR_LIST WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC 
--DESTINATION
ALTER PROC STP_COPY_FAMILY_CATEGORY
@OLD_FAMILY_ID INT,
@NEW_CATEGORY_ID VARCHAR(MAX)
AS
BEGIN
DECLARE @OLD_CATEGORY_ID VARCHAR(MAX) = (SELECT TOP 1 CATEGORY_ID FROM TB_FAMILY WHERE FAMILY_ID=@OLD_FAMILY_ID ORDER BY CREATED_DATE DESC)
INSERT INTO TB_FAMILY (FAMILY_NAME,FOOT_NOTES,PARENT_FAMILY_ID,ROOT_FAMILY,STATUS,PRODUCT_TABLE_STRUCTURE,DISPLAY_TABLE_HEADER,CATEGORY_ID)
	SELECT FAMILY_NAME,FOOT_NOTES,PARENT_FAMILY_ID,ROOT_FAMILY,STATUS,PRODUCT_TABLE_STRUCTURE,DISPLAY_TABLE_HEADER,@NEW_CATEGORY_ID 
	FROM TB_FAMILY WHERE CATEGORY_ID=@OLD_CATEGORY_ID AND FAMILY_ID=@OLD_FAMILY_ID
DECLARE @NEW_FAMILY_ID INT = (SELECT TOP 1 FAMILY_ID FROM TB_FAMILY ORDER BY CREATED_DATE DESC)
--SELECT * FROM TB_SUBFAMILY WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC
	--SELECT * FROM TB_SUBFAMILY WHERE SUBFAMILY_ID=966601 ORDER BY CREATED_DATE DESC
	
INSERT INTO TB_CATALOG_FAMILY(CATALOG_ID,FAMILY_ID,SORT_ORDER,CATEGORY_ID)
SELECT CATALOG_ID,@NEW_FAMILY_ID,SORT_ORDER,@NEW_CATEGORY_ID FROM TB_CATALOG_FAMILY 
WHERE CATEGORY_ID=@OLD_CATEGORY_ID AND CATALOG_ID<>1 AND FAMILY_ID=@OLD_FAMILY_ID

--SELECT * FROM TB_FAMILY_SPECS WHERE FAMILY_ID=966601 ORDER BY CREATED_DATE DESC 

INSERT INTO TB_FAMILY_TABLE_STRUCTURE (CATALOG_ID,FAMILY_ID,FAMILY_TABLE_STRUCTURE,STRUCTURE_NAME,IS_DEFAULT)
SELECT CATALOG_ID,@NEW_FAMILY_ID,FAMILY_TABLE_STRUCTURE,STRUCTURE_NAME,IS_DEFAULT FROM TB_FAMILY_TABLE_STRUCTURE 
WHERE FAMILY_ID=@OLD_FAMILY_ID AND CATALOG_ID<>1

DECLARE @TEMP TABLE
(
ID INT
)
INSERT INTO TB_PRODUCT(SINGLE_OR_KIT,STATUS,CATEGORY_ID) 
OUTPUT INSERTED.PRODUCT_ID INTO @TEMP(ID)
SELECT 1,'ACTIVE',@NEW_CATEGORY_ID FROM TB_PROD_FAMILY WHERE FAMILY_ID=@OLD_FAMILY_ID 
--DECLARE @COUNT INT = (SELECT COUNT(*) FROM @TEMP)

INSERT INTO TB_PROD_FAMILY (SORT_ORDER,FAMILY_ID,PRODUCT_ID,PUBLISH) SELECT ROW_NUMBER() OVER (ORDER BY ID ASC),@NEW_FAMILY_ID,ID,1 FROM @TEMP
DECLARE @FIRST INT = (SELECT TOP 1 ID FROM TE ORDER BY ID)
DECLARE @SECOND INT = (SELECT TOP 1 PRODUCT_ID FROM TB_PROD_SPECS WHERE PRODUCT_ID IN (SELECT PRODUCT_ID FROM TB_PROD_FAMILY 
	WHERE FAMILY_ID=@OLD_FAMILY_ID) ORDER BY PRODUCT_ID)
--PRINT @FIRST-@SECOND
DECLARE @COUNT INT = @FIRST-@SECOND

INSERT INTO TB_PROD_SPECS (STRING_VALUE,PRODUCT_ID,ATTRIBUTE_ID,NUMERIC_VALUE,OBJECT_TYPE,OBJECT_NAME) 
	SELECT STRING_VALUE,(PRODUCT_ID+@COUNT),ATTRIBUTE_ID,NUMERIC_VALUE,OBJECT_TYPE,OBJECT_NAME 
	FROM TB_PROD_SPECS WHERE PRODUCT_ID IN (SELECT PRODUCT_ID FROM TB_PROD_FAMILY WHERE FAMILY_ID=@OLD_FAMILY_ID)

INSERT INTO TB_PARTS_KEY (ATTRIBUTE_ID,PRODUCT_ID,FAMILY_ID,ATTRIBUTE_VALUE) 
	SELECT ATTRIBUTE_ID,(PRODUCT_ID+@COUNT),@NEW_FAMILY_ID,ATTRIBUTE_VALUE FROM TB_PARTS_KEY WHERE FAMILY_ID=@OLD_FAMILY_ID
INSERT INTO TB_CATALOG_PRODUCT (PRODUCT_ID,CATALOG_ID)
	SELECT (PRODUCT_ID+@COUNT),CATALOG_ID FROM TB_CATALOG_PRODUCT WHERE PRODUCT_ID IN (SELECT PRODUCT_ID FROM TB_PROD_FAMILY WHERE FAMILY_ID=@OLD_FAMILY_ID)
INSERT INTO TB_PROD_FAMILY_ATTR_LIST (ATTRIBUTE_ID,SORT_ORDER,FAMILY_ID,PRODUCT_ID)
	SELECT ATTRIBUTE_ID,SORT_ORDER,@NEW_FAMILY_ID,(PRODUCT_ID+@COUNT) FROM TB_PROD_FAMILY_ATTR_LIST WHERE FAMILY_ID=@OLD_FAMILY_ID
END







 
