SP_HELPTEXT STP_CATALOGSTUDIO5_ADDPROJECT

  
CREATE PROCEDURE [STP_CATALOGSTUDIO5_AddProject]  
@PROJECT_NAME NVARCHAR(50),  
@COMMENTS NVARCHAR(500),  
@CATALOG_ID INT,  
@PROJECT_TYPE INT,  
@PROJECT_ID INT OUTPUT  
AS  
INSERT INTO TB_PROJECT(PROJECT_NAME, COMMENTS, CATALOG_ID, PROJECT_TYPE)  
VALUES (@PROJECT_NAME, @COMMENTS, @CATALOG_ID, @PROJECT_TYPE)  
SET @PROJECT_ID = @@identity  
RETURN  
  
SELECT * FROM TB_PROJECT WHERE PROJECT_ID=13710

SP_HELPTEXT STP_CATALOGSTUDIO5_ADDIDFILE

  
  
CREATE PROCEDURE [STP_CATALOGSTUDIO5_AddIdFile]  
@ProjectID int,  
@Notes nvarchar(1000),  
@RecordID int OUTPUT  
as  
declare @FILE_NO int  
SELECT @FILE_NO = isnull(max(file_no),0) +1  from TB_PROJECT_SECTIONS WHERE PROJECT_ID = @ProjectID  
if (@FILE_NO = 0)  
BEGIN  
 SET @FILE_NO = 1  
END  
INSERT INTO TB_PROJECT_SECTIONS (PROJECT_ID, FILE_NO, NOTES) VALUES(@ProjectID, @FILE_NO, @Notes)  
SET @RecordID = @@Identity  
RETURN  

SELECT isnull(max(file_no),0) +1 FROM TB_PROJECT_SECTIONS
  
SELECT * FROM TB_PROJECT_SECTIONS WHERE PROJECT_ID=13710
-------------------------------------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM TB_CATEGORY WHERE CATEGORY_ID='WES 0496'

SELECT FAMILY_ID FROM TB_PROJECT_SECTION_DETAILS 
	WHERE	RECORD_ID IN 
			(SELECT RECORD_ID FROM TB_PROJECT_SECTIONS WHERE  RECORD_ID = 139)

SELECT F.FAMILY_ID FROM TB_FAMILY F, TB_CATALOG_FAMILY CF 
	WHERE		F.CATEGORY_ID = 'WES 0496' 
			AND F.CATEGORY_ID = CF.CATEGORY_ID 
			AND F.FAMILY_ID = CF.FAMILY_ID  
			AND F.PARENT_FAMILY_ID = 0 
			AND  CF.CATALOG_ID = 2 
				ORDER BY CF.SORT_ORDER
 
SELECT TB_CATEGORY.CATEGORY_ID,CATEGORY_NAME,SORT_ORDER FROM TB_CATEGORY, TB_CATALOG_SECTIONS,TB_CATALOG 
WHERE		TB_CATALOG_SECTIONS.CATEGORY_ID = TB_CATEGORY.CATEGORY_ID 
		AND TB_CATALOG.CATALOG_ID=TB_CATALOG_SECTIONS.CATALOG_ID 
		AND TB_CATALOG.CATALOG_ID=2 
		AND TB_CATEGORY.PARENT_CATEGORY='WES 0496' 
			ORDER BY SORT_ORDER


SELECT F.FAMILY_ID FROM TB_FAMILY F, TB_CATALOG_FAMILY CF 
WHERE		F.CATEGORY_ID = 'WES 04962N' 
		AND F.CATEGORY_ID = CF.CATEGORY_ID 
		AND F.FAMILY_ID = CF.FAMILY_ID  
		AND F.PARENT_FAMILY_ID = 0 
		AND CF.CATALOG_ID = 2 
			ORDER BY CF.SORT_ORDER

SELECT TB_CATEGORY.CATEGORY_ID,CATEGORY_NAME,SORT_ORDER FROM TB_CATEGORY, TB_CATALOG_SECTIONS,TB_CATALOG 
WHERE		TB_CATALOG_SECTIONS.CATEGORY_ID = TB_CATEGORY.CATEGORY_ID 
		AND TB_CATALOG.CATALOG_ID=TB_CATALOG_SECTIONS.CATALOG_ID 
		AND TB_CATALOG.CATALOG_ID=2 
		AND TB_CATEGORY.PARENT_CATEGORY='WES 04962N' 
			ORDER BY SORT_ORDER


SP_HELPTEXT STP_CATALOGSTUDIO5_ADDSECDETAIL


  
  
CREATE PROCEDURE [STP_CATALOGSTUDIO5_AddSecDetail]  
@RecordID int,  
@FamilyID int,  
@SectionName nvarchar(100)  
AS  
Declare @Sort_order int  
select @Sort_order = isnull(max(sort_order),0) + 1 from tb_project_section_details where record_id = @RecordID  
INSERT INTO TB_PROJECT_SECTION_DETAILS(FAMILY_ID, SORT_ORDER, RECORD_ID, SECTION_NAME)   
VALUES(@FamilyID, @Sort_order, @RecordID, @SectionName)  
RETURN  

SELECT FAMILY_ID FROM TB_PROJECT_SECTION_DETAILS 
WHERE RECORD_ID IN 
				(SELECT RECORD_ID FROM TB_PROJECT_SECTIONS WHERE  FILE_NO = 1 AND PROJECT_ID  = 13710) ORDER BY SORT_ORDER

SELECT CATEGORY_ID,PARENT_CATEGORY,CATEGORY_NAME FROM TB_CATEGORY 
WHERE CATEGORY_ID = (SELECT DISTINCT CATEGORY_ID FROM TB_CATALOG_FAMILY WHERE FAMILY_ID = 60913  AND CATALOG_ID = 2)

SELECT CATEGORY_ID,PARENT_CATEGORY,CATEGORY_NAME from TB_CATEGORY WHERE CATEGORY_ID = 'WES 0496'

SELECT FAMILY_FILTERS FROM TB_CATALOG WHERE  CATALOG_ID = 2 

SELECT TB_FAMILY.FAMILY_ID AS SUBFAMILY_ID, TB_FAMILY.FAMILY_NAME, TB_FAMILY.FOOT_NOTES, TB_FAMILY.PARENT_FAMILY_ID, TB_FAMILY.ROOT_FAMILY, TB_FAMILY.STATUS, TB_FAMILY_TABLE_STRUCTURE.FAMILY_TABLE_STRUCTURE, TB_FAMILY.CATEGORY_ID,  TB_SUBFAMILY.SORT_ORDER  
FROM TB_FAMILY INNER JOIN TB_CATALOG_FAMILY 
ON TB_FAMILY.FAMILY_ID = TB_CATALOG_FAMILY.FAMILY_ID  
INNER JOIN TB_CATALOG_SECTIONS 
ON TB_FAMILY.CATEGORY_ID = TB_CATALOG_SECTIONS.CATEGORY_ID AND TB_CATALOG_FAMILY.CATALOG_ID = TB_CATALOG_SECTIONS.CATALOG_ID  
INNER JOIN TB_SUBFAMILY 
ON TB_FAMILY.FAMILY_ID = TB_SUBFAMILY.SUBFAMILY_ID AND TB_CATALOG_FAMILY.FAMILY_ID = TB_SUBFAMILY.SUBFAMILY_ID 
	AND  TB_CATALOG_FAMILY.CATALOG_ID = TB_CATALOG_SECTIONS.CATALOG_ID,TB_FAMILY_TABLE_STRUCTURE 
WHERE TB_FAMILY_TABLE_STRUCTURE.CATALOG_ID=TB_CATALOG_SECTIONS.CATALOG_ID AND  TB_FAMILY_TABLE_STRUCTURE.FAMILY_ID=TB_FAMILY.FAMILY_ID
AND TB_FAMILY_TABLE_STRUCTURE.IS_DEFAULT=1 AND (TB_CATALOG_SECTIONS.CATALOG_ID =2) AND (TB_CATALOG_SECTIONS.CATALOG_ID = TB_CATALOG_SECTIONS.CATALOG_ID) 
AND  (TB_FAMILY.PARENT_FAMILY_ID = 60913) ORDER BY TB_SUBFAMILY.SORT_ORDER

SELECT CATEGORY_ID,PARENT_CATEGORY,CATEGORY_NAME from TB_CATEGORY WHERE CATEGORY_ID = (select distinct category_id from tb_catalog_family where family_id = 60913  and catalog_id = 2)

SELECT f.family_name,c.category_name,f.foot_notes, SHORT_DESC,IMAGE_FILE,IMAGE_TYPE,IMAGE_NAME,IMAGE_NAME2,IMAGE_FILE2,IMAGE_TYPE2,CUSTOM_NUM_FIELD1,CUSTOM_NUM_FIELD2,CUSTOM_NUM_FIELD3 ,CUSTOM_TEXT_FIELD1,CUSTOM_TEXT_FIELD2,CUSTOM_TEXT_FIELD3  FROM tb_family f, tb_category c	WHERE f.family_id = 60916 and f.category_id=c.category_id

SELECT CATEGORY_NAME,PARENT_CATEGORY from TB_CATEGORY WHERE CATEGORY_ID = (select distinct category_id from tb_catalog_family where family_id = 60916  and catalog_id = 2)

SELECT CATEGORY_NAME,PARENT_CATEGORY from TB_CATEGORY WHERE CATEGORY_ID = 'WES 0496'

SELECT CATEGORY_NAME,PARENT_CATEGORY FROM TB_CATEGORY WHERE CATEGORY_ID =  (SELECT CATEGORY_ID FROM TB_CATALOG_FAMILY WHERE FAMILY_ID = 60916  AND CATALOG_ID = 2)

SELECT CATEGORY_NAME,PARENT_CATEGORY,CATEGORY_ID from TB_CATEGORY WHERE CATEGORY_ID = 'WES 0496'

SELECT CATEGORY_ID FROM TB_CATALOG_FAMILY WHERE FAMILY_ID = 60916  AND CATALOG_ID = 2

SELECT SUPPLIER_NAME,URL,REPLACE(REPLACE(LOGO_IMAGE_FILE,'\','/'),'&','&AMP;') AS IMAGE_FILE,LOGO_IMAGE_TYPE FROM TB_SUPPLIER WHERE SUPPLIER_NAME IN (SELECT DISTINCT P.STRING_VALUE FROM TB_PROD_SPECS P,TB_PROD_FAMILY L WHERE P.PRODUCT_ID=L.PRODUCT_ID AND L.FAMILY_ID=60916 AND P.STRING_VALUE <> '')

SELECT FAMILY_TABLE_STRUCTURE  FROM TB_FAMILY_TABLE_STRUCTURE WHERE family_id=60916 AND CATALOG_ID=2 AND IS_DEFAULT=1

SELECT * FROM TB_CATALOG_SECTIONS
SELECT * FROM TB_CATEGORY
SELECT * FROM TB_CATALOG

SELECT * FROM TB_FAMILY
SELECT * FROM TB_CATALOG_FAMILY
SELECT * FROM TB_PROJECT_SECTION_DETAILS where RECORD_ID=139
SELECT * FROM TB_PROJECT_SECTION_DETAILS order by CREATED_DATE desc
















