UPDATE    TB_PROJECT_SECTIONS
SET              XML_FILE_NAME = gggggggggg, XSD_FILE_NAME = '', PAGE_FILE_NAME = '', TEMPLATE_FILE_NAME = '', 
                       NOTES = ''
WHERE     (RECORD_ID = 139) AND (FILE_NO = 1) AND (PROJECT_ID = 13710)

select * from TB_PROJECT_SECTIONS
where XML_FILE_NAME = 'gggggggggg' and  XSD_FILE_NAME = '' and  PAGE_FILE_NAME = ''and TEMPLATE_FILE_NAME = ''and 
                       NOTES = '' and 
    (RECORD_ID = 139) AND (FILE_NO = 1) AND (PROJECT_ID = 13710)
    
    
    
    
    
SELECT     TB_CATEGORY.CATEGORY_NAME, TB_CATEGORY.CATEGORY_ID, TB_PROJECT_SECTIONS.RECORD_ID, TB_FAMILY.FAMILY_NAME, 
                      TB_FAMILY.FAMILY_ID, TB_PROJECT_SECTION_DETAILS.SECTION_NAME, TB_PROJECT_SECTION_DETAILS.SORT_ORDER
FROM         TB_CATEGORY INNER JOIN
                      TB_CATALOG_FAMILY ON TB_CATEGORY.CATEGORY_ID = TB_CATALOG_FAMILY.CATEGORY_ID INNER JOIN
                      TB_FAMILY ON TB_FAMILY.FAMILY_ID = TB_CATALOG_FAMILY.FAMILY_ID INNER JOIN
                      TB_PROJECT_SECTION_DETAILS ON TB_FAMILY.FAMILY_ID = TB_PROJECT_SECTION_DETAILS.FAMILY_ID INNER JOIN
                      TB_PROJECT_SECTIONS ON TB_PROJECT_SECTION_DETAILS.RECORD_ID = TB_PROJECT_SECTIONS.RECORD_ID
WHERE     (TB_PROJECT_SECTIONS.RECORD_ID = 139) AND (TB_CATALOG_FAMILY.CATALOG_ID = 2)
ORDER BY TB_PROJECT_SECTION_DETAILS.SORT_ORDER

CREATE PROCEDURE [STP_CATALOGSTUDIO5_CopyFile]  
@XMLFileName varchar(1000),
@ProjectID int,  
@Notes nvarchar(1000),  
@RecordID int OUTPUT  
as  
declare @FILE_NO int  
SELECT @FILE_NO = isnull(max(file_no),0) +1  from TB_PROJECT_SECTIONS WHERE PROJECT_ID = @ProjectID  
if (@FILE_NO = 0)  
BEGIN  
 SET @FILE_NO = 1  
END  
INSERT INTO TB_PROJECT_SECTIONS (PROJECT_ID, FILE_NO, NOTES) VALUES(@ProjectID, @FILE_NO, @Notes)  
SET @RecordID = @@Identity  
RETURN



sp_help TB_PROJECT_SECTIONS

SELECT * FROM TB_PROJECT_SECTIONS ORDER BY PROJECT_ID DESC
SELECT * FROM TB_PROJECT_SECTIONS ORDER BY RECORD_ID desc
SELECT * FROM TB_PROJECT_SECTION_DETAILS ORDER BY CREATED_DATE DESC
--SELECT * FROM TB_PROJECT ORDER BY PROJECT_ID DESC

SELECT * FROM TB_PROJECT_SECTIONS where RECORD_ID=161
UPDATE TB_PROJECT_SECTIONS SET FILE_NO = 1 WHERE RECORD_ID=137

STP_CATALOGSTUDIO5_INDESIGN_COPY 141
STP_CATALOGSTUDIO5_INDESIGN_MOVE 13710,141

CREATE PROC STP_CATALOGSTUDIO5_INDESIGN_COPY
@RECORD_ID INT
AS
--SELECT AND INSERTING THE SAME RECORD
INSERT INTO TB_PROJECT_SECTIONS
	(	FILE_NO
	,	TEMPLATE_FILE_NAME
	,	TEMPLATE_FILE_PATH
	,	TEMPLATE_FILE_TYPE
	,	PAGE_FILE_NAME
	,	PAGE_FILE_PATH
	,	PAGE_FILE_TYPE
	,	NOTES
	,	XML_FILE_NAME
	,	PROJECT_ID
	,	XSD_FILE_NAME
	) 
SELECT	FILE_NO
	,	TEMPLATE_FILE_NAME
	,	TEMPLATE_FILE_PATH
	,	TEMPLATE_FILE_TYPE
	,	PAGE_FILE_NAME
	,	PAGE_FILE_PATH
	,	PAGE_FILE_TYPE
	,	NOTES
	,	'Copy of '+XML_FILE_NAME
	,	PROJECT_ID
	,	XSD_FILE_NAME 
FROM TB_PROJECT_SECTIONS 
	WHERE RECORD_ID=@RECORD_ID
--GETTING THE NEW RECORD ID
DECLARE @NEWRECORDID INT;
SET @NEWRECORDID = SCOPE_IDENTITY();
--INSERTING THE ATTRIBUTES ACCRODING TO THAT RECORD
INSERT INTO TB_PROJECT_SECTION_DETAILS
	(	FAMILY_ID
	,	SORT_ORDER
	,	SECTION_NAME
	,	RECORD_ID
	) 
SELECT	FAMILY_ID
	,	SORT_ORDER
	,	SECTION_NAME
	,	@NEWRECORDID AS RECORD_ID 
FROM TB_PROJECT_SECTION_DETAILS 
	WHERE RECORD_ID=@RECORD_ID



CREATE PROC STP_CATALOGSTUDIO5_INDESIGN_MOVE
@PROJECTID INT,
@RECORD_ID INT
AS
--CHANGIND THE PROJECT ID FOR MOVING
UPDATE TB_PROJECT_SECTIONS 
	SET PROJECT_ID=@PROJECTID 
WHERE RECORD_ID=@RECORD_ID


SELECT @PROJECTID PROJECT_ID FROM TB_PROJECT_SECTIONS WHERE RECORD_ID=@RECORD_ID
