--SELECT * FROM TB_FAMILY WHERE FAMILY_NAME='GGGGGGGGGGGGGGGGGGG'
SELECT * FROM TB_FAMILY WHERE CATEGORY_ID='MMC002' ORDER BY CREATED_DATE DESC
SELECT * FROM TB_SUBFAMILY ORDER BY CREATED_DATE DESC
SELECT * FROM TB_CATALOG_FAMILY WHERE CATEGORY_ID='MMC002' ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_FAMILY_SPECS ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_FAMILY_TABLE_STRUCTURE ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PRODUCT WHERE CATEGORY_ID='MMC002' ORDER BY CREATED_DATE DESC 
--SELECT * FROM TB_PROD_SPECS ORDER BY CREATED_DATE DESC
SELECT * FROM TB_PROD_SPECS WHERE ATTRIBUTE_ID=1 ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PARTS_KEY ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_FAMILY ORDER BY CREATED_DATE DESC 
--DELETE TB_PROD_FAMILY WHERE FAMILY_ID=966602
SELECT * FROM TB_CATALOG_PRODUCT WHERE CATALOG_ID IN (1,2) ORDER BY CREATED_DATE DESC 
SELECT * FROM TB_PROD_FAMILY_ATTR_LIST ORDER BY CREATED_DATE DESC 
