CREATE PROC STP_CATALOGSTUDIO5_INDESIGN_COPY
@RECORD_ID INT
AS
--SELECT AND INSERTING THE SAME RECORD
DECLARE @PROJECT_ID INT = (SELECT PROJECT_ID FROM TB_PROJECT_SECTIONS WHERE RECORD_ID=@RECORD_ID)
DECLARE @COUNT INT = (SELECT COUNT(*) FROM TB_PROJECT_SECTIONS WHERE PROJECT_ID=@PROJECT_ID)
INSERT INTO TB_PROJECT_SECTIONS
	(	FILE_NO
	,	TEMPLATE_FILE_NAME
	,	TEMPLATE_FILE_PATH
	,	TEMPLATE_FILE_TYPE
	,	PAGE_FILE_NAME
	,	PAGE_FILE_PATH
	,	PAGE_FILE_TYPE
	,	NOTES
	,	XML_FILE_NAME
	,	PROJECT_ID
	,	XSD_FILE_NAME
	) 
SELECT	@COUNT + 1
	,	TEMPLATE_FILE_NAME
	,	TEMPLATE_FILE_PATH
	,	TEMPLATE_FILE_TYPE
	,	PAGE_FILE_NAME
	,	PAGE_FILE_PATH
	,	PAGE_FILE_TYPE
	,	NOTES
	,	'Copy of '+XML_FILE_NAME
	,	PROJECT_ID
	,	XSD_FILE_NAME 
FROM TB_PROJECT_SECTIONS 
	WHERE RECORD_ID=@RECORD_ID
--GETTING THE NEW RECORD ID
DECLARE @NEWRECORDID INT;
SET @NEWRECORDID = SCOPE_IDENTITY();
--INSERTING THE ATTRIBUTES ACCRODING TO THAT RECORD
INSERT INTO TB_PROJECT_SECTION_DETAILS
	(	FAMILY_ID
	,	SORT_ORDER
	,	SECTION_NAME
	,	RECORD_ID
	) 
SELECT	FAMILY_ID
	,	SORT_ORDER
	,	SECTION_NAME
	,	@NEWRECORDID AS RECORD_ID 
FROM TB_PROJECT_SECTION_DETAILS 
	WHERE RECORD_ID=@RECORD_ID
GO


CREATE PROC STP_CATALOGSTUDIO5_INDESIGN_MOVE
@PROJECTID INT,
@RECORD_ID INT
AS
DECLARE @PREVIOUS_PROJECT_ID INT = (SELECT PROJECT_ID FROM TB_PROJECT_SECTIONS WHERE RECORD_ID=@RECORD_ID)
DECLARE @FILE_NO INT = (SELECT FILE_NO FROM TB_PROJECT_SECTIONS WHERE RECORD_ID=@RECORD_ID)
DECLARE @COUNT INT = (SELECT COUNT(*) FROM TB_PROJECT_SECTIONS WHERE PROJECT_ID=@PROJECTID)
--CHANGIND THE PROJECT ID FOR MOVING
UPDATE TB_PROJECT_SECTIONS 
	SET		PROJECT_ID = @PROJECTID 
		,	FILE_NO = @COUNT + 1
WHERE RECORD_ID=@RECORD_ID
UPDATE TB_PROJECT_SECTIONS 
	SET		FILE_NO = FILE_NO - 1
WHERE PROJECT_ID=@PREVIOUS_PROJECT_ID AND FILE_NO > @FILE_NO
GO