<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - September - 2013 ::</title><style type="text/css">
<!--
.style10 {
	border-collapse: collapse;
}
.style13 {
	font-family: Verdana;
	font-size: xx-small;
	margin: 10px;
}
.style14 {
	font-size: 9pt;
}
.style15 {
	font-family: Verdana;
	font-size: xx-small;
	margin: 10px;
	text-align: justify;
}
.style27 {
	font-family: Verdana;
	font-size: medium;
	color: #C00000;
}
-->
</style>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" cellpadding="0" style="width: 780px;" bordercolor="#111111" class="style10" align="center">
  <tr>
    <td width="100%" style="height: 19px">
<? include("../../../inc/top1.php"); ?>  
<? include("../../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="100%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#EFEFE9" colspan="3" align=center height="10">
            <div align="left">
				<table border="0" style="border-collapse: collapse" width="175" cellpadding="0">
					<tr>
						<td width="28" bgcolor="#FF0000" height="30" style="border-left-style: solid; border-left-width: 1px; border-right-width: 1px; border-top-width: 1px; border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#000000">&nbsp;
						</td>
						
                  <td valign="bottom" style="border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#FF0000" width="131"> 
                    <p align="left" style="margin-left: 5px"> <a name="top">
					<b><font face="Verdana" size="1">REAL ESTATE </font></b></a></td>
					</tr>
				</table>
			</div>
			</td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">

<table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse" bordercolor="#111111">
	<tr>
						<td>&nbsp;
						</td>
					</tr>
	<tr>
						<td valign="top">
						<p align="justify" style="margin: 3px 10px"> 
					<b><font face="Verdana" size="4" color="#C00000">Sustainable Competitive Advantage</font></b><br>
						<font face="Verdana" size="2"><b><br>
						</b></font>
						<br />
                        
                         <img src="images/Realestate/1.jpg">
						<br />
						<font face="Verdana" size="1"><i>By Jose Lora</i></font></p>
                        
						<p align="justify" style="margin: 3px 10px"> 
					<p align="justify" class="style13">Jose Lora, COO of Real Estate and Hospitality Sector for the Zubair Corporation believes that anchorage in Oman's nascent market and strategy are extremely important in trying to achieve a sustainable competitive advantage in real estate
                    
                   
 
<br />
<br />
Anchorage is a concept that is highly developed in the retail industry but can also apply to other forms of real estate development. It is also another element that is extremely important in trying to achieve a sustainable competitive advantage in real estate. What is it about the project that is a principle draw that is highly attractive to the market? As an example, shopping centres generally leverage the footfall generated by such anchors as major department stores, food courts, and entertainment. Real estate projects are no different; the anchorage for a project like Barr Al Jissah is a world class hospitality element such as the Shangri-La. The Shangri-La has been honoured with numerous awards for their quality of service; originally based on Asian Hospitality. We like to think that it contains a strong mix of Omani hospitality. The Shangri-La at the heart of Barr Al Jissah Resort with its three hotels - Al Husn, Al Bandar and Al Waha – creates high demand for the resort; not only from the GCC but from different parts of the World.  
<br />
<br />
In geographical terms Oman is a gold mine and the most beautiful country in the GCC with a strong culture and genuine friendly environment. The strength of Oman's market in terms of real estate development is that it is still a nascent market. The Sultanate has a number of factors fuelling the market. The demographics of the country and the market needs will be a driving force in many areas of real estate development. The country has enjoyed stable governance over the past few decades and there is stable GDP growth guided by the government's careful planning and diversification in non-oil sectors.
<br />
<br />
Strategy in many organisations deals with issues such as the flexibility of your company to respond to the changing market dynamics, continuously looking at achieving best practice standards, and to nurture competencies that would make you a market leader and all this in the context of a market position. The real estate industry is not different than other businesses as developers are constantly looking for those elements which will give their projects a sustainable competitive advantage. In this respect real estate can have elements that absolutely cannot be reproduced. As an example, the majestic beauty of Barr Al Jissah Resort is one of a kind experience. While you may look to copy its architecture or even the same product mix, nature has given Barr Al Jissah a distinctive environment that simply cannot be reproduced and will always be an attractive force in the market. This in itself sets Barr Al Jissah apart and it will always preserve its competitive advantage.
<br />
<br />
<strong>Positioning</strong>
<br />
<br />
The strategic position of any real estate project is also critical to the success or failure of the project. The true measure of the correct positioning is whether or not real estate projects can survive the unanticipated economic cycles of today's global markets. Real estate projects need to endure by strategically positioning developments over a long term horizon. We have gone through the global financial crisis and are going through a European economic downturn and as a result many projects have faltered. Barr Al Jissah is now looking towards the future with a clear vision – of translating the high demand of a prestigious resort and to provide a low quantity of residential product which ultimately translates to long term value. The focus of the Barr Al Jissah Resort is on high networth individuals from the GCC. Our studies have reached a resounding conclusion that this market segment has a strong appetite for real estate in Oman. 
<br />
<br />
<b>Note on the author:</b><br />
Jose Lora has worked extensively in the US, Mexico, South America and in the GCC. In the US he was the design and construction head for the entire East Coast at HomartDevelopment which at one time was the third largest multi-use and shopping centre developer in North America. He then joined the Sears Organisation and moved to Mexico to head the company's Latin America operations. At Sears, he was instrumental in expanding the business in Latin America. Subsequently his real estate consultancy firm Arlo grew into one of the most prominent real estate consultancies in Latin America. Lora has been consulting and developing real estate strategies for over 35 years and is a graduate of the University of Illinois where he studied Architecture and has an MBA from Strathclyde University.


</td>
					</tr>
	<tr>
		        <td width="100%" valign="top"> 

                    <hr color="#CC3333">
                  <p align="right" style="margin: 3px 10px">
					<font face="Verdana" size="1">
                <a href="#top">Top^</a></font></td>
		</tr>
	<tr>
		        <td width="100%" valign="top">&nbsp; 

                    </td>
		</tr>
	</table>

            </td>
            <td  valign=top bgcolor=white><?include("../../../inc/current_issue_menu.php");?>&nbsp;</td>
          </tr>
          
        </table>
	</tr>
  <tr>
    <td width="100%" height="15" valign="middle">
              <? include("../../../inc/menu1.htm");?>
        <? include("../../../inc/bottom.htm");?>
</table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
</body>
</html>