






<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - July - 2011 ::</title><style type="text/css">
<!--
.style10 {
	border-collapse: collapse;
}
.style13 {
	font-family: Verdana;
	font-size: xx-small;
	margin: 10px;
}
.style14 {
	font-size: 9pt;
}
.style15 {
	font-family: Verdana;
	font-size: xx-small;
	margin: 10px;
	text-align: justify;
}
.style16 {
	margin: 10px 15px;
	text-align: center;
}
.style18 {
	border: 15px solid #C4C4C4;
	font-family: Verdana;
	font-size: xx-small;
	margin: 10px;
	text-align: justify;
	background-color: #FFFFCC;
}
.style26 {
	font-family: Verdana;
	font-size: xx-small;
}
.style19 {
	border-width: 0px;
}
-->
</style>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" cellpadding="0" style="width: 780px;" bordercolor="#111111" class="style10" align="center">
  <tr>
    <td width="100%" style="height: 19px">
<? include("../../../inc/top1.php"); ?>  
<? include("../../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="100%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#EFEFE9" colspan="3" align=center height="10">
            <div align="left">
				<table border="0" style="border-collapse: collapse" width="175" cellpadding="0">
					<tr>
						<td width="28" bgcolor="#FF0000" height="30" style="border-left-style: solid; border-left-width: 1px; border-right-width: 1px; border-top-width: 1px; border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#000000">
						&nbsp;</td>
						
                  <td valign="bottom" style="border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#FF0000" width="131"> 
                    <p align="left" style="margin-left: 5px"> <a name="top">
					<span class="style26"><strong>E</strong></span><b><font face="Verdana" size="1">DITORIAL</font></b></a></td>
					</tr>
				</table>
			</div>
			</td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">

<table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse" bordercolor="#111111">
	<tr>
						<td>
						&nbsp;</td>
					</tr>
	<tr>
						<td valign="top">
						<p align="justify" style="margin: 3px 10px"><b>
						<font face="Verdana" size="4" color="#C00000">
						E-Business</font></b><p align="justify" class="style13">
				<br>
				Holding up an iPhone 4, one of the speakers at a recently held 
				Gartner Summit on Enterprise Architecture in London said, “As a 
				mere phone, this is a terrible phone, but it is probably one of 
				the best smart phones around and there is no going back.” How 
				true, the march of technology is an irrevocable and linear 
				trend. According to Gartner Research, 50 per cent of the 
				technology and equipment currently in use will be obsolete over 
				the next ten years. The pace of change is not merely going to 
				quicken but get turbocharged.<br>
				<br>
				The promise offers a big business opportunity for companies. The 
				Middle East region is catching up rapidly in the IT sweepstakes. 
				According to a recent report from the Economist Intelligence 
				Unit, the Middle East IT services market is likely to hit $3.5bn 
				by 2012. There are 41.8mn internet users across 16 Arab 
				countries with Arabic emerging as the seventh most popular 
				language on the net. Oman has been going through its own digital 
				revolution. The IT services market is poised to grow by 10 per 
				cent reaching $0.53bn by the end of 2011. According to Arab 
				Advisory Group data, cellular penetration in Oman stands at 
				132.9 per cent. This growth has made Oman an attractive IT 
				destination for local, regional and international companies. 
				Given the right enablers, the sector has the potential to emerge 
				as a regional powerhouse. This issue’s cover story gives a few 
				pointers in this direction. <br>
				<br>
				As promised, the second edition of Oman Green Awards (OGA) 
				proved to be a thumping success. The post event reactions, press 
				coverage and word of mouth goodwill generated by OGA has helped 
				to raise environment consciousness in the Sultanate. A number of 
				other organisations have initiated environment conservation 
				efforts in its trail and it is heartening to see the Green Oman 
				movement gaining traction.<br>
&nbsp;</td>
					</tr>
	<tr>
		        <td width="100%" valign="top"> 

                    <table style="width: 100%; height: 92px" cellspacing="0" cellpadding="0">
						<tr>
							<td class="style18">
							<p class="style16">
				<font face="Verdana" size="1">
				<img border="0" src="http://www.oeronline.com/images/sign-mayanksing.gif" style="border-style: solid; border-color: #808080;" width="163" height="53" class="style19"><br>
							</font><strong>Mayank Singh</strong></p>
							</td>
						</tr>
					</table>
				</td>
		</tr>
	<tr>
		        <td width="100%" valign="top"> 

                    <hr color="#CC3333">
                  <p align="right" style="margin: 3px 10px">
					<font face="Verdana" size="1">
                <a href="#top">Top^</a></font></td>
		</tr>
	<tr>
		        <td width="100%" valign="top"> 

                    &nbsp;</td>
		</tr>
	</table>

            </td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
	</tr>
  <tr>
    <td width="100%" height="15" valign="middle">
              <? include("../../../inc/menu1.htm");?>
        <? include("../../../inc/bottom.htm");?>
</table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
</body>
</html>