<?xml version="1.0" encoding="utf-8"?><Database Name="PhotoProcessing" Class="PhotoProcessingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=iconstech\SQLEXPRESS;Initial Catalog=PhotoProcessing;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="Biz_OutSource_To_IndiaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Photo_Billing_Address" Member="Photo_Billing_Addresses">
    <Type Name="Photo_Billing_Address">
      <Column Name="Billing_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bill_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Bill_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Photo_Billing_Address_Photo_PhysicalCopyDetail" Member="Photo_PhysicalCopyDetails" ThisKey="Billing_id" OtherKey="FkBilling_Address" Type="Photo_PhysicalCopyDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_Change_Password_log" Member="Photo_Change_Password_logs">
    <Type Name="Photo_Change_Password_log">
      <Column Name="Change_pwd_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="New_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Old_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date_of_change" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_Change_Password_log" Member="Photo_CustomerRegistrationDetail" ThisKey="FkCustomer_id" OtherKey="Customer_id" Type="Photo_CustomerRegistrationDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_CountryDetail" Member="Photo_CountryDetails">
    <Type Name="Photo_CountryDetail">
      <Column Name="Country_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Country_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Country_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Photo_CountryDetail_Photo_StateDetail" Member="Photo_StateDetails" ThisKey="Country_id" OtherKey="FkCountry_id" Type="Photo_StateDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_Customer_Status" Member="Photo_Customer_Status">
    <Type Name="Photo_Customer_Status">
      <Column Name="Status_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Status_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Photo_Customer_Status_Photo_OrderDetail" Member="Photo_OrderDetails" ThisKey="Status_id" OtherKey="FkCustomer_Status" Type="Photo_OrderDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_CustomerRegistrationDetail" Member="Photo_CustomerRegistrationDetails">
    <Type Name="Photo_CustomerRegistrationDetail">
      <Column Name="Customer_id" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Last_Login" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Error_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Current_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Profile_Image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivationStatus_Mail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivationStatus_Mobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMS_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_Change_Password_log" Member="Photo_Change_Password_logs" ThisKey="Customer_id" OtherKey="FkCustomer_id" Type="Photo_Change_Password_log" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_OrderDetail" Member="Photo_OrderDetails" ThisKey="Customer_id" OtherKey="FkCustomer_id" Type="Photo_OrderDetail" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_Promo_codeDetail" Member="Photo_Promo_codeDetails" ThisKey="Customer_id" OtherKey="FkCustomer_id" Type="Photo_Promo_codeDetail" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_OrderSummaryDetail" Member="Photo_OrderSummaryDetails" ThisKey="Customer_id" OtherKey="fkCustomer_id" Type="Photo_OrderSummaryDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_OrderDetail" Member="Photo_OrderDetails">
    <Type Name="Photo_OrderDetail">
      <Column Name="Order_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Image_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Input_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Edit_Options" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Complaint_Towards" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ordered_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliveredDate_SoftCopy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Process_Status" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Output_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Association Name="Photo_OrderDetail_Photo_PhysicalCopyDetail" Member="Photo_PhysicalCopyDetails" ThisKey="Order_id" OtherKey="FkOrder_id" Type="Photo_PhysicalCopyDetail" />
      <Association Name="Photo_OrderDetail_Photo_RemarksDetail" Member="Photo_RemarksDetails" ThisKey="Order_id" OtherKey="FkOrder_id" Type="Photo_RemarksDetail" />
      <Association Name="Photo_Customer_Status_Photo_OrderDetail" Member="Photo_Customer_Status" ThisKey="FkCustomer_Status" OtherKey="Status_id" Type="Photo_Customer_Status" IsForeignKey="true" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_OrderDetail" Member="Photo_CustomerRegistrationDetail" ThisKey="FkCustomer_id" OtherKey="Customer_id" Type="Photo_CustomerRegistrationDetail" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Photo_PlanDetail_Photo_OrderDetail" Member="Photo_PlanDetail" ThisKey="FkPlan_id" OtherKey="Plan_id" Type="Photo_PlanDetail" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_PhysicalCopyDetail" Member="Photo_PhysicalCopyDetails">
    <Type Name="Photo_PhysicalCopyDetail">
      <Column Name="Physical_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PhysicalCopy_Type" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ordered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Delivered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Shipping_tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkBilling_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FkShipping_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Physical_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Photo_Billing_Address_Photo_PhysicalCopyDetail" Member="Photo_Billing_Address" ThisKey="FkBilling_Address" OtherKey="Billing_id" Type="Photo_Billing_Address" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Photo_OrderDetail_Photo_PhysicalCopyDetail" Member="Photo_OrderDetail" ThisKey="FkOrder_id" OtherKey="Order_id" Type="Photo_OrderDetail" IsForeignKey="true" />
      <Association Name="Photo_Shipping_Address_Photo_PhysicalCopyDetail" Member="Photo_Shipping_Address" ThisKey="FkShipping_Address" OtherKey="Shipping_id" Type="Photo_Shipping_Address" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_PlanDetail" Member="Photo_PlanDetails">
    <Type Name="Photo_PlanDetail">
      <Column Name="Plan_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Plan_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Association Name="Photo_PlanDetail_Photo_OrderDetail" Member="Photo_OrderDetails" ThisKey="Plan_id" OtherKey="FkPlan_id" Type="Photo_OrderDetail" />
      <Association Name="Photo_PlanDetail_Photo_SubCatagoryDetail" Member="Photo_SubCatagoryDetails" ThisKey="Plan_id" OtherKey="FkPlan_id" Type="Photo_SubCatagoryDetail" />
      <Association Name="Photo_PlanDetail_Photo_OrderSummaryDetail" Member="Photo_OrderSummaryDetails" ThisKey="Plan_id" OtherKey="fkPlan_id" Type="Photo_OrderSummaryDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_Promo_codeDetail" Member="Photo_Promo_codeDetails">
    <Type Name="Photo_Promo_codeDetail">
      <Column Name="Promo_code_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Promo_Discount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_Promo_codeDetail" Member="Photo_CustomerRegistrationDetail" ThisKey="FkCustomer_id" OtherKey="Customer_id" Type="Photo_CustomerRegistrationDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_RemarksDetail" Member="Photo_RemarksDetails">
    <Type Name="Photo_RemarksDetail">
      <Column Name="Remark_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Remarks_Detail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Photo_OrderDetail_Photo_RemarksDetail" Member="Photo_OrderDetail" ThisKey="FkOrder_id" OtherKey="Order_id" Type="Photo_OrderDetail" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_Shipping_Address" Member="Photo_Shipping_Addresses">
    <Type Name="Photo_Shipping_Address">
      <Column Name="Shipping_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ship_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ship_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Photo_Shipping_Address_Photo_PhysicalCopyDetail" Member="Photo_PhysicalCopyDetails" ThisKey="Shipping_id" OtherKey="FkShipping_Address" Type="Photo_PhysicalCopyDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_StateDetail" Member="Photo_StateDetails">
    <Type Name="Photo_StateDetail">
      <Column Name="State_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="State_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FkCountry_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Photo_CountryDetail_Photo_StateDetail" Member="Photo_CountryDetail" ThisKey="FkCountry_id" OtherKey="Country_id" Type="Photo_CountryDetail" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_SubCatagoryDetail" Member="Photo_SubCatagoryDetails">
    <Type Name="Photo_SubCatagoryDetail">
      <Column Name="SubCategory_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Category_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Photo_PlanDetail_Photo_SubCatagoryDetail" Member="Photo_PlanDetail" ThisKey="FkPlan_id" OtherKey="Plan_id" Type="Photo_PlanDetail" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Photo_OrderSummaryDetail" Member="Photo_OrderSummaryDetails">
    <Type Name="Photo_OrderSummaryDetail">
      <Column Name="OrderSummary_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EditOption" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="fkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="fkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Association Name="Photo_CustomerRegistrationDetail_Photo_OrderSummaryDetail" Member="Photo_CustomerRegistrationDetail" ThisKey="fkCustomer_id" OtherKey="Customer_id" Type="Photo_CustomerRegistrationDetail" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Photo_PlanDetail_Photo_OrderSummaryDetail" Member="Photo_PlanDetail" ThisKey="fkPlan_id" OtherKey="Plan_id" Type="Photo_PlanDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Photo_Billing_AddressNewDeleteCommand" Method="sp_Photo_Billing_AddressNewDeleteCommand">
    <Parameter Name="Original_Billing_id" Parameter="original_Billing_id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_Billing_AddressNewInsertCommand" Method="sp_Photo_Billing_AddressNewInsertCommand">
    <Parameter Name="Bill_Name" Parameter="bill_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_Address" Parameter="bill_Address" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_zipcode" Parameter="bill_zipcode" Type="System.Int32" DbType="Int" />
    <Parameter Name="Bill_Country" Parameter="bill_Country" Type="System.Int32" DbType="Int" />
    <Parameter Name="Bill_State" Parameter="bill_State" Type="System.Int32" DbType="Int" />
    <Parameter Name="Bill_City" Parameter="bill_City" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_Mail" Parameter="bill_Mail" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_Phone" Parameter="bill_Phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Bill_Mobile" Parameter="bill_Mobile" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_Billing_AddressNewInsertCommandResult">
      <Column Name="Billing_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Bill_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Bill_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Billing_AddressNewSelectCommand" Method="sp_Photo_Billing_AddressNewSelectCommand">
    <ElementType Name="sp_Photo_Billing_AddressNewSelectCommandResult">
      <Column Name="Billing_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Bill_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Bill_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Billing_AddressNewUpdateCommand" Method="sp_Photo_Billing_AddressNewUpdateCommand">
    <Parameter Name="Bill_Name" Parameter="bill_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_Address" Parameter="bill_Address" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_zipcode" Parameter="bill_zipcode" Type="System.Int32" DbType="Int" />
    <Parameter Name="Bill_Country" Parameter="bill_Country" Type="System.Int32" DbType="Int" />
    <Parameter Name="Bill_State" Parameter="bill_State" Type="System.Int32" DbType="Int" />
    <Parameter Name="Bill_City" Parameter="bill_City" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_Mail" Parameter="bill_Mail" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Bill_Phone" Parameter="bill_Phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Bill_Mobile" Parameter="bill_Mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_Billing_id" Parameter="original_Billing_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Billing_id" Parameter="billing_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_Billing_AddressNewUpdateCommandResult">
      <Column Name="Billing_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Bill_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bill_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Bill_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Bill_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Change_Password_logNewDeleteCommand" Method="sp_Photo_Change_Password_logNewDeleteCommand">
    <Parameter Name="Original_Change_pwd_id" Parameter="original_Change_pwd_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_Change_Password_logNewInsertCommand" Method="sp_Photo_Change_Password_logNewInsertCommand">
    <Parameter Name="New_Password" Parameter="new_Password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Old_Password" Parameter="old_Password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Date_of_change" Parameter="date_of_change" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FkCustomer_id" Parameter="fkCustomer_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_Change_Password_logNewInsertCommandResult">
      <Column Name="Change_pwd_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="New_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Old_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date_of_change" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Change_Password_logNewSelectCommand" Method="sp_Photo_Change_Password_logNewSelectCommand">
    <ElementType Name="sp_Photo_Change_Password_logNewSelectCommandResult">
      <Column Name="Change_pwd_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="New_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Old_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date_of_change" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Change_Password_logNewUpdateCommand" Method="sp_Photo_Change_Password_logNewUpdateCommand">
    <Parameter Name="New_Password" Parameter="new_Password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Old_Password" Parameter="old_Password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Date_of_change" Parameter="date_of_change" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FkCustomer_id" Parameter="fkCustomer_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_Change_pwd_id" Parameter="original_Change_pwd_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Change_pwd_id" Parameter="change_pwd_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_Change_Password_logNewUpdateCommandResult">
      <Column Name="Change_pwd_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="New_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Old_Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Date_of_change" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Customer_StatusNewDeleteCommand" Method="sp_Photo_Customer_StatusNewDeleteCommand">
    <Parameter Name="Original_Status_id" Parameter="original_Status_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_Customer_StatusNewInsertCommand" Method="sp_Photo_Customer_StatusNewInsertCommand">
    <Parameter Name="Status_name" Parameter="status_name" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_Photo_Customer_StatusNewInsertCommandResult">
      <Column Name="Status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Customer_StatusNewSelectCommand" Method="sp_Photo_Customer_StatusNewSelectCommand">
    <ElementType Name="sp_Photo_Customer_StatusNewSelectCommandResult">
      <Column Name="Status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Customer_StatusNewUpdateCommand" Method="sp_Photo_Customer_StatusNewUpdateCommand">
    <Parameter Name="Status_name" Parameter="status_name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Original_Status_id" Parameter="original_Status_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Status_id" Parameter="status_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_Customer_StatusNewUpdateCommandResult">
      <Column Name="Status_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Status_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_OrderDetailNewDeleteCommand" Method="sp_Photo_OrderDetailNewDeleteCommand">
    <Parameter Name="Original_Order_id" Parameter="original_Order_id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_OrderDetailNewSelectCommand" Method="sp_Photo_OrderDetailNewSelectCommand">
    <ElementType Name="sp_Photo_OrderDetailNewSelectCommandResult">
      <Column Name="Order_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Image_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Input_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Edit_Options" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Complaint_Towards" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ordered_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliveredDate_SoftCopy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkPromo_Code" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Process_Status" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Output_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_PhysicalCopyDetailNewDeleteCommand" Method="sp_Photo_PhysicalCopyDetailNewDeleteCommand">
    <Parameter Name="Original_Physical_id" Parameter="original_Physical_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_PhysicalCopyDetailNewInsertCommand" Method="sp_Photo_PhysicalCopyDetailNewInsertCommand">
    <Parameter Name="PhysicalCopy_Type" Parameter="physicalCopy_Type" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ordered_Date" Parameter="ordered_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Delivered_Date" Parameter="delivered_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FkOrder_id" Parameter="fkOrder_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Shipping_tax" Parameter="shipping_tax" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Tax" Parameter="tax" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="FkBilling_Address" Parameter="fkBilling_Address" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FkShipping_Address" Parameter="fkShipping_Address" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Physical_Amount" Parameter="physical_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <ElementType Name="sp_Photo_PhysicalCopyDetailNewInsertCommandResult">
      <Column Name="Physical_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhysicalCopy_Type" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ordered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Delivered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Shipping_tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkBilling_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FkShipping_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Physical_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_PhysicalCopyDetailNewSelectCommand" Method="sp_Photo_PhysicalCopyDetailNewSelectCommand">
    <ElementType Name="sp_Photo_PhysicalCopyDetailNewSelectCommandResult">
      <Column Name="Physical_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhysicalCopy_Type" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ordered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Delivered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Shipping_tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkBilling_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FkShipping_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Physical_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_PhysicalCopyDetailNewUpdateCommand" Method="sp_Photo_PhysicalCopyDetailNewUpdateCommand">
    <Parameter Name="PhysicalCopy_Type" Parameter="physicalCopy_Type" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Quantity" Parameter="quantity" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ordered_Date" Parameter="ordered_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Delivered_Date" Parameter="delivered_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="FkOrder_id" Parameter="fkOrder_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Shipping_tax" Parameter="shipping_tax" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Tax" Parameter="tax" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="FkBilling_Address" Parameter="fkBilling_Address" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="FkShipping_Address" Parameter="fkShipping_Address" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Physical_Amount" Parameter="physical_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Original_Physical_id" Parameter="original_Physical_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Physical_id" Parameter="physical_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_PhysicalCopyDetailNewUpdateCommandResult">
      <Column Name="Physical_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PhysicalCopy_Type" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ordered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Delivered_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Shipping_tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Tax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkBilling_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FkShipping_Address" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Physical_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_PlanDetailNewDeleteCommand" Method="sp_Photo_PlanDetailNewDeleteCommand">
    <Parameter Name="Original_Plan_id" Parameter="original_Plan_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_PlanDetailNewInsertCommand" Method="sp_Photo_PlanDetailNewInsertCommand">
    <Parameter Name="Plan_Name" Parameter="plan_Name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Rate" Parameter="rate" Type="System.Decimal" DbType="Decimal(18,2)" />
    <ElementType Name="sp_Photo_PlanDetailNewInsertCommandResult">
      <Column Name="Plan_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Plan_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_PlanDetailNewSelectCommand" Method="sp_Photo_PlanDetailNewSelectCommand">
    <ElementType Name="sp_Photo_PlanDetailNewSelectCommandResult">
      <Column Name="Plan_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Plan_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_PlanDetailNewUpdateCommand" Method="sp_Photo_PlanDetailNewUpdateCommand">
    <Parameter Name="Plan_Name" Parameter="plan_Name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Rate" Parameter="rate" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Original_Plan_id" Parameter="original_Plan_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Plan_id" Parameter="plan_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_PlanDetailNewUpdateCommandResult">
      <Column Name="Plan_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Plan_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Rate" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Promo_codeDetailNewDeleteCommand" Method="sp_Photo_Promo_codeDetailNewDeleteCommand">
    <Parameter Name="Original_Promo_code_id" Parameter="original_Promo_code_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_Promo_codeDetailNewInsertCommand" Method="sp_Photo_Promo_codeDetailNewInsertCommand">
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Promo_Discount" Parameter="promo_Discount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="FkCustomer_id" Parameter="fkCustomer_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_Promo_codeDetailNewInsertCommandResult">
      <Column Name="Promo_code_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Promo_Discount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Promo_codeDetailNewSelectCommand" Method="sp_Photo_Promo_codeDetailNewSelectCommand">
    <ElementType Name="sp_Photo_Promo_codeDetailNewSelectCommandResult">
      <Column Name="Promo_code_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Promo_Discount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Promo_codeDetailNewUpdateCommand" Method="sp_Photo_Promo_codeDetailNewUpdateCommand">
    <Parameter Name="Code" Parameter="code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Promo_Discount" Parameter="promo_Discount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="FkCustomer_id" Parameter="fkCustomer_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_Promo_code_id" Parameter="original_Promo_code_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Promo_code_id" Parameter="promo_code_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_Promo_codeDetailNewUpdateCommandResult">
      <Column Name="Promo_code_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Promo_Discount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_RemarksDetailNewDeleteCommand" Method="sp_Photo_RemarksDetailNewDeleteCommand">
    <Parameter Name="Original_Remark_id" Parameter="original_Remark_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_RemarksDetailNewInsertCommand" Method="sp_Photo_RemarksDetailNewInsertCommand">
    <Parameter Name="Remarks_Detail" Parameter="remarks_Detail" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FkOrder_id" Parameter="fkOrder_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_RemarksDetailNewInsertCommandResult">
      <Column Name="Remark_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarks_Detail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_RemarksDetailNewSelectCommand" Method="sp_Photo_RemarksDetailNewSelectCommand">
    <ElementType Name="sp_Photo_RemarksDetailNewSelectCommandResult">
      <Column Name="Remark_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarks_Detail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_RemarksDetailNewUpdateCommand" Method="sp_Photo_RemarksDetailNewUpdateCommand">
    <Parameter Name="Remarks_Detail" Parameter="remarks_Detail" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FkOrder_id" Parameter="fkOrder_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_Remark_id" Parameter="original_Remark_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Remark_id" Parameter="remark_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_RemarksDetailNewUpdateCommandResult">
      <Column Name="Remark_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Remarks_Detail" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkOrder_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Shipping_AddressNewDeleteCommand" Method="sp_Photo_Shipping_AddressNewDeleteCommand">
    <Parameter Name="Original_Shipping_id" Parameter="original_Shipping_id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_Shipping_AddressNewInsertCommand" Method="sp_Photo_Shipping_AddressNewInsertCommand">
    <Parameter Name="Ship_Name" Parameter="ship_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_Address" Parameter="ship_Address" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_zipcode" Parameter="ship_zipcode" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ship_Country" Parameter="ship_Country" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ship_State" Parameter="ship_State" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ship_City" Parameter="ship_City" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_Mail" Parameter="ship_Mail" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_Phone" Parameter="ship_Phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Ship_Mobile" Parameter="ship_Mobile" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_Shipping_AddressNewInsertCommandResult">
      <Column Name="Shipping_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Ship_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ship_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Shipping_AddressNewSelectCommand" Method="sp_Photo_Shipping_AddressNewSelectCommand">
    <ElementType Name="sp_Photo_Shipping_AddressNewSelectCommandResult">
      <Column Name="Shipping_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Ship_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ship_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_Shipping_AddressNewUpdateCommand" Method="sp_Photo_Shipping_AddressNewUpdateCommand">
    <Parameter Name="Ship_Name" Parameter="ship_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_Address" Parameter="ship_Address" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_zipcode" Parameter="ship_zipcode" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ship_Country" Parameter="ship_Country" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ship_State" Parameter="ship_State" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ship_City" Parameter="ship_City" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_Mail" Parameter="ship_Mail" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Ship_Phone" Parameter="ship_Phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Ship_Mobile" Parameter="ship_Mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Original_Shipping_id" Parameter="original_Shipping_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Shipping_id" Parameter="shipping_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_Shipping_AddressNewUpdateCommandResult">
      <Column Name="Shipping_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Ship_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Address" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_zipcode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_State" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ship_City" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Mail" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ship_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Ship_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_SubCatagoryDetailNewDeleteCommand" Method="sp_Photo_SubCatagoryDetailNewDeleteCommand">
    <Parameter Name="Original_SubCategory_id" Parameter="original_SubCategory_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_SubCatagoryDetailNewInsertCommand" Method="sp_Photo_SubCatagoryDetailNewInsertCommand">
    <Parameter Name="Category_name" Parameter="category_name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FkPlan_id" Parameter="fkPlan_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_SubCatagoryDetailNewInsertCommandResult">
      <Column Name="SubCategory_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_SubCatagoryDetailNewSelectCommand" Method="sp_Photo_SubCatagoryDetailNewSelectCommand">
    <ElementType Name="sp_Photo_SubCatagoryDetailNewSelectCommandResult">
      <Column Name="SubCategory_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_SubCatagoryDetailNewUpdateCommand" Method="sp_Photo_SubCatagoryDetailNewUpdateCommand">
    <Parameter Name="Category_name" Parameter="category_name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="FkPlan_id" Parameter="fkPlan_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_SubCategory_id" Parameter="original_SubCategory_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="SubCategory_id" Parameter="subCategory_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_SubCatagoryDetailNewUpdateCommandResult">
      <Column Name="SubCategory_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Category_name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_OrderDetailNewInsertCommand" Method="sp_Photo_OrderDetailNewInsertCommand">
    <Parameter Name="FkCustomer_id" Parameter="fkCustomer_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Image_name" Parameter="image_name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Input_Image_URL" Parameter="input_Image_URL" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Edit_Options" Parameter="edit_Options" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Complaint_Towards" Parameter="complaint_Towards" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FkPlan_id" Parameter="fkPlan_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ordered_date" Parameter="ordered_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DeliveredDate_SoftCopy" Parameter="deliveredDate_SoftCopy" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Process_Status" Parameter="process_Status" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Total_Amount" Parameter="total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="FkCustomer_Status" Parameter="fkCustomer_Status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Output_Image_URL" Parameter="output_Image_URL" Type="System.String" DbType="NVarChar(200)" />
    <ElementType Name="sp_Photo_OrderDetailNewInsertCommandResult">
      <Column Name="Order_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Image_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Input_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Edit_Options" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Complaint_Towards" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ordered_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliveredDate_SoftCopy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Process_Status" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Output_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_OrderDetailNewUpdateCommand" Method="sp_Photo_OrderDetailNewUpdateCommand">
    <Parameter Name="FkCustomer_id" Parameter="fkCustomer_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Image_name" Parameter="image_name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Input_Image_URL" Parameter="input_Image_URL" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Edit_Options" Parameter="edit_Options" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Complaint_Towards" Parameter="complaint_Towards" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="FkPlan_id" Parameter="fkPlan_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Ordered_date" Parameter="ordered_date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DeliveredDate_SoftCopy" Parameter="deliveredDate_SoftCopy" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Process_Status" Parameter="process_Status" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Total_Amount" Parameter="total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="FkCustomer_Status" Parameter="fkCustomer_Status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Output_Image_URL" Parameter="output_Image_URL" Type="System.String" DbType="NVarChar(200)" />
    <Parameter Name="Original_Order_id" Parameter="original_Order_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Order_id" Parameter="order_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_OrderDetailNewUpdateCommandResult">
      <Column Name="Order_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="FkCustomer_id" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Image_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Input_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Edit_Options" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Complaint_Towards" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="FkPlan_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ordered_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DeliveredDate_SoftCopy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Process_Status" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="FkCustomer_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Output_Image_URL" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_CustomerRegistrationDetailNewDeleteCommand" Method="sp_Photo_CustomerRegistrationDetailNewDeleteCommand">
    <Parameter Name="Original_Customer_id" Parameter="original_Customer_id" Type="System.Int64" DbType="BigInt" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Photo_CustomerRegistrationDetailNewInsertCommand" Method="sp_Photo_CustomerRegistrationDetailNewInsertCommand">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Country" Parameter="country" Type="System.Int32" DbType="Int" />
    <Parameter Name="Reg_Date" Parameter="reg_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Last_Login" Parameter="last_Login" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Error_count" Parameter="error_count" Type="System.Int32" DbType="Int" />
    <Parameter Name="Current_Status" Parameter="current_Status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Profile_Image" Parameter="profile_Image" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Full_Name" Parameter="full_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ActivationStatus_Mail" Parameter="activationStatus_Mail" Type="System.Int32" DbType="Int" />
    <Parameter Name="ActivationStatus_Mobile" Parameter="activationStatus_Mobile" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email_Subs" Parameter="email_Subs" Type="System.Int32" DbType="Int" />
    <Parameter Name="SMS_Subs" Parameter="sMS_Subs" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Photo_CustomerRegistrationDetailNewInsertCommandResult">
      <Column Name="Customer_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Last_Login" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Error_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Current_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Profile_Image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivationStatus_Mail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivationStatus_Mobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMS_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_CustomerRegistrationDetailNewSelectCommand" Method="sp_Photo_CustomerRegistrationDetailNewSelectCommand">
    <ElementType Name="sp_Photo_CustomerRegistrationDetailNewSelectCommandResult">
      <Column Name="Customer_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Last_Login" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Error_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Current_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Profile_Image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivationStatus_Mail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivationStatus_Mobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMS_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Photo_CustomerRegistrationDetailNewUpdateCommand" Method="sp_Photo_CustomerRegistrationDetailNewUpdateCommand">
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Country" Parameter="country" Type="System.Int32" DbType="Int" />
    <Parameter Name="Reg_Date" Parameter="reg_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Last_Login" Parameter="last_Login" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Error_count" Parameter="error_count" Type="System.Int32" DbType="Int" />
    <Parameter Name="Current_Status" Parameter="current_Status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Profile_Image" Parameter="profile_Image" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Full_Name" Parameter="full_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ActivationStatus_Mail" Parameter="activationStatus_Mail" Type="System.Int32" DbType="Int" />
    <Parameter Name="ActivationStatus_Mobile" Parameter="activationStatus_Mobile" Type="System.Int32" DbType="Int" />
    <Parameter Name="Email_Subs" Parameter="email_Subs" Type="System.Int32" DbType="Int" />
    <Parameter Name="SMS_Subs" Parameter="sMS_Subs" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_Customer_id" Parameter="original_Customer_id" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Customer_id" Parameter="customer_id" Type="System.Int64" DbType="BigInt" />
    <ElementType Name="sp_Photo_CustomerRegistrationDetailNewUpdateCommandResult">
      <Column Name="Customer_id" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Last_Login" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Error_count" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Current_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Profile_Image" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Full_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ActivationStatus_Mail" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ActivationStatus_Mobile" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Email_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SMS_Subs" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>