#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace churchforms
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ChurchApplication")]
	public partial class ChurchApplicationDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChurch_LoginDetail(Church_LoginDetail instance);
    partial void UpdateChurch_LoginDetail(Church_LoginDetail instance);
    partial void DeleteChurch_LoginDetail(Church_LoginDetail instance);
    partial void InsertChurch_MemberDetail(Church_MemberDetail instance);
    partial void UpdateChurch_MemberDetail(Church_MemberDetail instance);
    partial void DeleteChurch_MemberDetail(Church_MemberDetail instance);
    partial void InsertChurch_OfferingDetail(Church_OfferingDetail instance);
    partial void UpdateChurch_OfferingDetail(Church_OfferingDetail instance);
    partial void DeleteChurch_OfferingDetail(Church_OfferingDetail instance);
    partial void InsertChurch_BankDetail(Church_BankDetail instance);
    partial void UpdateChurch_BankDetail(Church_BankDetail instance);
    partial void DeleteChurch_BankDetail(Church_BankDetail instance);
    partial void InsertChurch_GeneralOfferingDetail(Church_GeneralOfferingDetail instance);
    partial void UpdateChurch_GeneralOfferingDetail(Church_GeneralOfferingDetail instance);
    partial void DeleteChurch_GeneralOfferingDetail(Church_GeneralOfferingDetail instance);
    #endregion
		
		public ChurchApplicationDataContext() : 
				base(global::churchforms.Properties.Settings.Default.ChurchApplicationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ChurchApplicationDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChurchApplicationDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChurchApplicationDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ChurchApplicationDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Church_LoginDetail> Church_LoginDetails
		{
			get
			{
				return this.GetTable<Church_LoginDetail>();
			}
		}
		
		public System.Data.Linq.Table<Church_MemberDetail> Church_MemberDetails
		{
			get
			{
				return this.GetTable<Church_MemberDetail>();
			}
		}
		
		public System.Data.Linq.Table<Church_OfferingDetail> Church_OfferingDetails
		{
			get
			{
				return this.GetTable<Church_OfferingDetail>();
			}
		}
		
		public System.Data.Linq.Table<Church_BankDetail> Church_BankDetails
		{
			get
			{
				return this.GetTable<Church_BankDetail>();
			}
		}
		
		public System.Data.Linq.Table<Church_GeneralOfferingDetail> Church_GeneralOfferingDetails
		{
			get
			{
				return this.GetTable<Church_GeneralOfferingDetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Church_LoginDetail")]
	public partial class Church_LoginDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Login_id;
		
		private System.Nullable<int> _Login_type;
		
		private string _Login_name;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLogin_idChanging(long value);
    partial void OnLogin_idChanged();
    partial void OnLogin_typeChanging(System.Nullable<int> value);
    partial void OnLogin_typeChanged();
    partial void OnLogin_nameChanging(string value);
    partial void OnLogin_nameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public Church_LoginDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Login_id
		{
			get
			{
				return this._Login_id;
			}
			set
			{
				if ((this._Login_id != value))
				{
					this.OnLogin_idChanging(value);
					this.SendPropertyChanging();
					this._Login_id = value;
					this.SendPropertyChanged("Login_id");
					this.OnLogin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login_type", DbType="Int")]
		public System.Nullable<int> Login_type
		{
			get
			{
				return this._Login_type;
			}
			set
			{
				if ((this._Login_type != value))
				{
					this.OnLogin_typeChanging(value);
					this.SendPropertyChanging();
					this._Login_type = value;
					this.SendPropertyChanged("Login_type");
					this.OnLogin_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Login_name", DbType="NVarChar(50)")]
		public string Login_name
		{
			get
			{
				return this._Login_name;
			}
			set
			{
				if ((this._Login_name != value))
				{
					this.OnLogin_nameChanging(value);
					this.SendPropertyChanging();
					this._Login_name = value;
					this.SendPropertyChanged("Login_name");
					this.OnLogin_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Church_MemberDetail")]
	public partial class Church_MemberDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MemberId;
		
		private string _MemberName;
		
		private System.Nullable<long> _CardNo;
		
		private System.Nullable<int> _FamilyNo;
		
		private string _Address;
		
		private string _Telephone;
		
		private System.Nullable<long> _Mobile;
		
		private string _Occupation;
		
		private string _Gender;
		
		private System.Nullable<System.DateTime> _DOB;
		
		private string _MaritalStatus;
		
		private System.Nullable<System.DateTime> _MarriageDate;
		
		private System.Nullable<System.DateTime> _RegisterDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMemberIdChanging(long value);
    partial void OnMemberIdChanged();
    partial void OnMemberNameChanging(string value);
    partial void OnMemberNameChanged();
    partial void OnCardNoChanging(System.Nullable<long> value);
    partial void OnCardNoChanged();
    partial void OnFamilyNoChanging(System.Nullable<int> value);
    partial void OnFamilyNoChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnTelephoneChanging(string value);
    partial void OnTelephoneChanged();
    partial void OnMobileChanging(System.Nullable<long> value);
    partial void OnMobileChanged();
    partial void OnOccupationChanging(string value);
    partial void OnOccupationChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnDOBChanged();
    partial void OnMaritalStatusChanging(string value);
    partial void OnMaritalStatusChanged();
    partial void OnMarriageDateChanging(System.Nullable<System.DateTime> value);
    partial void OnMarriageDateChanged();
    partial void OnRegisterDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegisterDateChanged();
    #endregion
		
		public Church_MemberDetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MemberId
		{
			get
			{
				return this._MemberId;
			}
			set
			{
				if ((this._MemberId != value))
				{
					this.OnMemberIdChanging(value);
					this.SendPropertyChanging();
					this._MemberId = value;
					this.SendPropertyChanged("MemberId");
					this.OnMemberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MemberName", DbType="NVarChar(50)")]
		public string MemberName
		{
			get
			{
				return this._MemberName;
			}
			set
			{
				if ((this._MemberName != value))
				{
					this.OnMemberNameChanging(value);
					this.SendPropertyChanging();
					this._MemberName = value;
					this.SendPropertyChanged("MemberName");
					this.OnMemberNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardNo", DbType="BigInt")]
		public System.Nullable<long> CardNo
		{
			get
			{
				return this._CardNo;
			}
			set
			{
				if ((this._CardNo != value))
				{
					this.OnCardNoChanging(value);
					this.SendPropertyChanging();
					this._CardNo = value;
					this.SendPropertyChanged("CardNo");
					this.OnCardNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FamilyNo", DbType="Int")]
		public System.Nullable<int> FamilyNo
		{
			get
			{
				return this._FamilyNo;
			}
			set
			{
				if ((this._FamilyNo != value))
				{
					this.OnFamilyNoChanging(value);
					this.SendPropertyChanging();
					this._FamilyNo = value;
					this.SendPropertyChanged("FamilyNo");
					this.OnFamilyNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="NVarChar(200)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telephone", DbType="NVarChar(50)")]
		public string Telephone
		{
			get
			{
				return this._Telephone;
			}
			set
			{
				if ((this._Telephone != value))
				{
					this.OnTelephoneChanging(value);
					this.SendPropertyChanging();
					this._Telephone = value;
					this.SendPropertyChanged("Telephone");
					this.OnTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="BigInt")]
		public System.Nullable<long> Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Occupation", DbType="NVarChar(100)")]
		public string Occupation
		{
			get
			{
				return this._Occupation;
			}
			set
			{
				if ((this._Occupation != value))
				{
					this.OnOccupationChanging(value);
					this.SendPropertyChanging();
					this._Occupation = value;
					this.SendPropertyChanged("Occupation");
					this.OnOccupationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="NVarChar(10)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime")]
		public System.Nullable<System.DateTime> DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaritalStatus", DbType="NVarChar(10)")]
		public string MaritalStatus
		{
			get
			{
				return this._MaritalStatus;
			}
			set
			{
				if ((this._MaritalStatus != value))
				{
					this.OnMaritalStatusChanging(value);
					this.SendPropertyChanging();
					this._MaritalStatus = value;
					this.SendPropertyChanged("MaritalStatus");
					this.OnMaritalStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarriageDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> MarriageDate
		{
			get
			{
				return this._MarriageDate;
			}
			set
			{
				if ((this._MarriageDate != value))
				{
					this.OnMarriageDateChanging(value);
					this.SendPropertyChanging();
					this._MarriageDate = value;
					this.SendPropertyChanged("MarriageDate");
					this.OnMarriageDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegisterDate
		{
			get
			{
				return this._RegisterDate;
			}
			set
			{
				if ((this._RegisterDate != value))
				{
					this.OnRegisterDateChanging(value);
					this.SendPropertyChanging();
					this._RegisterDate = value;
					this.SendPropertyChanged("RegisterDate");
					this.OnRegisterDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Church_OfferingDetail")]
	public partial class Church_OfferingDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Offering_id;
		
		private string _Offername;
		
		private EntitySet<Church_GeneralOfferingDetail> _Church_GeneralOfferingDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOffering_idChanging(int value);
    partial void OnOffering_idChanged();
    partial void OnOffernameChanging(string value);
    partial void OnOffernameChanged();
    #endregion
		
		public Church_OfferingDetail()
		{
			this._Church_GeneralOfferingDetails = new EntitySet<Church_GeneralOfferingDetail>(new Action<Church_GeneralOfferingDetail>(this.attach_Church_GeneralOfferingDetails), new Action<Church_GeneralOfferingDetail>(this.detach_Church_GeneralOfferingDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offering_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Offering_id
		{
			get
			{
				return this._Offering_id;
			}
			set
			{
				if ((this._Offering_id != value))
				{
					this.OnOffering_idChanging(value);
					this.SendPropertyChanging();
					this._Offering_id = value;
					this.SendPropertyChanged("Offering_id");
					this.OnOffering_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offername", DbType="NVarChar(50)")]
		public string Offername
		{
			get
			{
				return this._Offername;
			}
			set
			{
				if ((this._Offername != value))
				{
					this.OnOffernameChanging(value);
					this.SendPropertyChanging();
					this._Offername = value;
					this.SendPropertyChanged("Offername");
					this.OnOffernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Church_OfferingDetail_Church_GeneralOfferingDetail", Storage="_Church_GeneralOfferingDetails", ThisKey="Offering_id", OtherKey="Offering_type")]
		public EntitySet<Church_GeneralOfferingDetail> Church_GeneralOfferingDetails
		{
			get
			{
				return this._Church_GeneralOfferingDetails;
			}
			set
			{
				this._Church_GeneralOfferingDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Church_GeneralOfferingDetails(Church_GeneralOfferingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Church_OfferingDetail = this;
		}
		
		private void detach_Church_GeneralOfferingDetails(Church_GeneralOfferingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Church_OfferingDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Church_BankDetail")]
	public partial class Church_BankDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Bank_id;
		
		private string _Bank_name;
		
		private EntitySet<Church_GeneralOfferingDetail> _Church_GeneralOfferingDetails;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBank_idChanging(int value);
    partial void OnBank_idChanged();
    partial void OnBank_nameChanging(string value);
    partial void OnBank_nameChanged();
    #endregion
		
		public Church_BankDetail()
		{
			this._Church_GeneralOfferingDetails = new EntitySet<Church_GeneralOfferingDetail>(new Action<Church_GeneralOfferingDetail>(this.attach_Church_GeneralOfferingDetails), new Action<Church_GeneralOfferingDetail>(this.detach_Church_GeneralOfferingDetails));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Bank_id
		{
			get
			{
				return this._Bank_id;
			}
			set
			{
				if ((this._Bank_id != value))
				{
					this.OnBank_idChanging(value);
					this.SendPropertyChanging();
					this._Bank_id = value;
					this.SendPropertyChanged("Bank_id");
					this.OnBank_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bank_name", DbType="NVarChar(50)")]
		public string Bank_name
		{
			get
			{
				return this._Bank_name;
			}
			set
			{
				if ((this._Bank_name != value))
				{
					this.OnBank_nameChanging(value);
					this.SendPropertyChanging();
					this._Bank_name = value;
					this.SendPropertyChanged("Bank_name");
					this.OnBank_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Church_BankDetail_Church_GeneralOfferingDetail", Storage="_Church_GeneralOfferingDetails", ThisKey="Bank_id", OtherKey="Bankname")]
		public EntitySet<Church_GeneralOfferingDetail> Church_GeneralOfferingDetails
		{
			get
			{
				return this._Church_GeneralOfferingDetails;
			}
			set
			{
				this._Church_GeneralOfferingDetails.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Church_GeneralOfferingDetails(Church_GeneralOfferingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Church_BankDetail = this;
		}
		
		private void detach_Church_GeneralOfferingDetails(Church_GeneralOfferingDetail entity)
		{
			this.SendPropertyChanging();
			entity.Church_BankDetail = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Church_GeneralOfferingDetail")]
	public partial class Church_GeneralOfferingDetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Account_id;
		
		private System.Nullable<int> _Offering_type;
		
		private System.Nullable<decimal> _CashAmount;
		
		private System.Nullable<int> _Bankname;
		
		private string _Bankbranch;
		
		private string _Chequeno;
		
		private System.Nullable<decimal> _ChequeAmount;
		
		private System.Nullable<System.DateTime> _ChequeDate;
		
		private System.Nullable<System.DateTime> _RegisteredDate;
		
		private System.Nullable<int> @__1000x;
		
		private System.Nullable<int> @__500x;
		
		private System.Nullable<int> @__100x;
		
		private System.Nullable<int> @__50x;
		
		private System.Nullable<int> @__20x;
		
		private System.Nullable<int> @__10x;
		
		private System.Nullable<int> @__5x;
		
		private System.Nullable<int> @__2x;
		
		private System.Nullable<int> @__1x;
		
		private EntityRef<Church_BankDetail> _Church_BankDetail;
		
		private EntityRef<Church_OfferingDetail> _Church_OfferingDetail;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccount_idChanging(long value);
    partial void OnAccount_idChanged();
    partial void OnOffering_typeChanging(System.Nullable<int> value);
    partial void OnOffering_typeChanged();
    partial void OnCashAmountChanging(System.Nullable<decimal> value);
    partial void OnCashAmountChanged();
    partial void OnBanknameChanging(System.Nullable<int> value);
    partial void OnBanknameChanged();
    partial void OnBankbranchChanging(string value);
    partial void OnBankbranchChanged();
    partial void OnChequenoChanging(string value);
    partial void OnChequenoChanged();
    partial void OnChequeAmountChanging(System.Nullable<decimal> value);
    partial void OnChequeAmountChanged();
    partial void OnChequeDateChanging(System.Nullable<System.DateTime> value);
    partial void OnChequeDateChanged();
    partial void OnRegisteredDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegisteredDateChanged();
    partial void On_1000xChanging(System.Nullable<int> value);
    partial void On_1000xChanged();
    partial void On_500xChanging(System.Nullable<int> value);
    partial void On_500xChanged();
    partial void On_100xChanging(System.Nullable<int> value);
    partial void On_100xChanged();
    partial void On_50xChanging(System.Nullable<int> value);
    partial void On_50xChanged();
    partial void On_20xChanging(System.Nullable<int> value);
    partial void On_20xChanged();
    partial void On_10xChanging(System.Nullable<int> value);
    partial void On_10xChanged();
    partial void On_5xChanging(System.Nullable<int> value);
    partial void On_5xChanged();
    partial void On_2xChanging(System.Nullable<int> value);
    partial void On_2xChanged();
    partial void On_1xChanging(System.Nullable<int> value);
    partial void On_1xChanged();
    #endregion
		
		public Church_GeneralOfferingDetail()
		{
			this._Church_BankDetail = default(EntityRef<Church_BankDetail>);
			this._Church_OfferingDetail = default(EntityRef<Church_OfferingDetail>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Account_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long Account_id
		{
			get
			{
				return this._Account_id;
			}
			set
			{
				if ((this._Account_id != value))
				{
					this.OnAccount_idChanging(value);
					this.SendPropertyChanging();
					this._Account_id = value;
					this.SendPropertyChanged("Account_id");
					this.OnAccount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Offering_type", DbType="Int")]
		public System.Nullable<int> Offering_type
		{
			get
			{
				return this._Offering_type;
			}
			set
			{
				if ((this._Offering_type != value))
				{
					if (this._Church_OfferingDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnOffering_typeChanging(value);
					this.SendPropertyChanging();
					this._Offering_type = value;
					this.SendPropertyChanged("Offering_type");
					this.OnOffering_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> CashAmount
		{
			get
			{
				return this._CashAmount;
			}
			set
			{
				if ((this._CashAmount != value))
				{
					this.OnCashAmountChanging(value);
					this.SendPropertyChanging();
					this._CashAmount = value;
					this.SendPropertyChanged("CashAmount");
					this.OnCashAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bankname", DbType="Int")]
		public System.Nullable<int> Bankname
		{
			get
			{
				return this._Bankname;
			}
			set
			{
				if ((this._Bankname != value))
				{
					if (this._Church_BankDetail.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnBanknameChanging(value);
					this.SendPropertyChanging();
					this._Bankname = value;
					this.SendPropertyChanged("Bankname");
					this.OnBanknameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bankbranch", DbType="NVarChar(50)")]
		public string Bankbranch
		{
			get
			{
				return this._Bankbranch;
			}
			set
			{
				if ((this._Bankbranch != value))
				{
					this.OnBankbranchChanging(value);
					this.SendPropertyChanging();
					this._Bankbranch = value;
					this.SendPropertyChanged("Bankbranch");
					this.OnBankbranchChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chequeno", DbType="NVarChar(50)")]
		public string Chequeno
		{
			get
			{
				return this._Chequeno;
			}
			set
			{
				if ((this._Chequeno != value))
				{
					this.OnChequenoChanging(value);
					this.SendPropertyChanging();
					this._Chequeno = value;
					this.SendPropertyChanged("Chequeno");
					this.OnChequenoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChequeAmount", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ChequeAmount
		{
			get
			{
				return this._ChequeAmount;
			}
			set
			{
				if ((this._ChequeAmount != value))
				{
					this.OnChequeAmountChanging(value);
					this.SendPropertyChanging();
					this._ChequeAmount = value;
					this.SendPropertyChanged("ChequeAmount");
					this.OnChequeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChequeDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ChequeDate
		{
			get
			{
				return this._ChequeDate;
			}
			set
			{
				if ((this._ChequeDate != value))
				{
					this.OnChequeDateChanging(value);
					this.SendPropertyChanging();
					this._ChequeDate = value;
					this.SendPropertyChanged("ChequeDate");
					this.OnChequeDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisteredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegisteredDate
		{
			get
			{
				return this._RegisteredDate;
			}
			set
			{
				if ((this._RegisteredDate != value))
				{
					this.OnRegisteredDateChanging(value);
					this.SendPropertyChanging();
					this._RegisteredDate = value;
					this.SendPropertyChanged("RegisteredDate");
					this.OnRegisteredDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1000x]", Storage="__1000x", DbType="Int")]
		public System.Nullable<int> _1000x
		{
			get
			{
				return this.@__1000x;
			}
			set
			{
				if ((this.@__1000x != value))
				{
					this.On_1000xChanging(value);
					this.SendPropertyChanging();
					this.@__1000x = value;
					this.SendPropertyChanged("_1000x");
					this.On_1000xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[500x]", Storage="__500x", DbType="Int")]
		public System.Nullable<int> _500x
		{
			get
			{
				return this.@__500x;
			}
			set
			{
				if ((this.@__500x != value))
				{
					this.On_500xChanging(value);
					this.SendPropertyChanging();
					this.@__500x = value;
					this.SendPropertyChanged("_500x");
					this.On_500xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[100x]", Storage="__100x", DbType="Int")]
		public System.Nullable<int> _100x
		{
			get
			{
				return this.@__100x;
			}
			set
			{
				if ((this.@__100x != value))
				{
					this.On_100xChanging(value);
					this.SendPropertyChanging();
					this.@__100x = value;
					this.SendPropertyChanged("_100x");
					this.On_100xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[50x]", Storage="__50x", DbType="Int")]
		public System.Nullable<int> _50x
		{
			get
			{
				return this.@__50x;
			}
			set
			{
				if ((this.@__50x != value))
				{
					this.On_50xChanging(value);
					this.SendPropertyChanging();
					this.@__50x = value;
					this.SendPropertyChanged("_50x");
					this.On_50xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[20x]", Storage="__20x", DbType="Int")]
		public System.Nullable<int> _20x
		{
			get
			{
				return this.@__20x;
			}
			set
			{
				if ((this.@__20x != value))
				{
					this.On_20xChanging(value);
					this.SendPropertyChanging();
					this.@__20x = value;
					this.SendPropertyChanged("_20x");
					this.On_20xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[10x]", Storage="__10x", DbType="Int")]
		public System.Nullable<int> _10x
		{
			get
			{
				return this.@__10x;
			}
			set
			{
				if ((this.@__10x != value))
				{
					this.On_10xChanging(value);
					this.SendPropertyChanging();
					this.@__10x = value;
					this.SendPropertyChanged("_10x");
					this.On_10xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[5x]", Storage="__5x", DbType="Int")]
		public System.Nullable<int> _5x
		{
			get
			{
				return this.@__5x;
			}
			set
			{
				if ((this.@__5x != value))
				{
					this.On_5xChanging(value);
					this.SendPropertyChanging();
					this.@__5x = value;
					this.SendPropertyChanged("_5x");
					this.On_5xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[2x]", Storage="__2x", DbType="Int")]
		public System.Nullable<int> _2x
		{
			get
			{
				return this.@__2x;
			}
			set
			{
				if ((this.@__2x != value))
				{
					this.On_2xChanging(value);
					this.SendPropertyChanging();
					this.@__2x = value;
					this.SendPropertyChanged("_2x");
					this.On_2xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[1x]", Storage="__1x", DbType="Int")]
		public System.Nullable<int> _1x
		{
			get
			{
				return this.@__1x;
			}
			set
			{
				if ((this.@__1x != value))
				{
					this.On_1xChanging(value);
					this.SendPropertyChanging();
					this.@__1x = value;
					this.SendPropertyChanged("_1x");
					this.On_1xChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Church_BankDetail_Church_GeneralOfferingDetail", Storage="_Church_BankDetail", ThisKey="Bankname", OtherKey="Bank_id", IsForeignKey=true)]
		public Church_BankDetail Church_BankDetail
		{
			get
			{
				return this._Church_BankDetail.Entity;
			}
			set
			{
				Church_BankDetail previousValue = this._Church_BankDetail.Entity;
				if (((previousValue != value) 
							|| (this._Church_BankDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Church_BankDetail.Entity = null;
						previousValue.Church_GeneralOfferingDetails.Remove(this);
					}
					this._Church_BankDetail.Entity = value;
					if ((value != null))
					{
						value.Church_GeneralOfferingDetails.Add(this);
						this._Bankname = value.Bank_id;
					}
					else
					{
						this._Bankname = default(Nullable<int>);
					}
					this.SendPropertyChanged("Church_BankDetail");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Church_OfferingDetail_Church_GeneralOfferingDetail", Storage="_Church_OfferingDetail", ThisKey="Offering_type", OtherKey="Offering_id", IsForeignKey=true, DeleteRule="CASCADE")]
		public Church_OfferingDetail Church_OfferingDetail
		{
			get
			{
				return this._Church_OfferingDetail.Entity;
			}
			set
			{
				Church_OfferingDetail previousValue = this._Church_OfferingDetail.Entity;
				if (((previousValue != value) 
							|| (this._Church_OfferingDetail.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Church_OfferingDetail.Entity = null;
						previousValue.Church_GeneralOfferingDetails.Remove(this);
					}
					this._Church_OfferingDetail.Entity = value;
					if ((value != null))
					{
						value.Church_GeneralOfferingDetails.Add(this);
						this._Offering_type = value.Offering_id;
					}
					else
					{
						this._Offering_type = default(Nullable<int>);
					}
					this.SendPropertyChanged("Church_OfferingDetail");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
