<?xml version="1.0" encoding="utf-8"?><Database Name="ChurchApplication" Class="ChurchApplicationDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=ChurchApplication;Integrated Security=True" SettingsObjectName="churchforms.Properties.Settings" SettingsPropertyName="ChurchApplicationConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Church_LoginDetail" Member="Church_LoginDetails">
    <Type Name="Church_LoginDetail">
      <Column Name="Login_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Login_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Church_MemberDetail" Member="Church_MemberDetails">
    <Type Name="Church_MemberDetail">
      <Column Name="MemberId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MemberName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CardNo" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="FamilyNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Occupation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MaritalStatus" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="MarriageDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Church_OfferingDetail" Member="Church_OfferingDetails">
    <Type Name="Church_OfferingDetail">
      <Column Name="Offering_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Offername" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Church_OfferingDetail_Church_Accountdetail" Member="Church_Accountdetails" ThisKey="Offering_id" OtherKey="Offering_type" Type="Church_Accountdetail" />
    </Type>
  </Table>
  <Table Name="dbo.Church_Accountdetail" Member="Church_Accountdetails">
    <Type Name="Church_Accountdetail">
      <Column Name="Account_id" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cardno" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="MainCatagory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Offering_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CashAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Bankname" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Bankbranch" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Chequeno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ChequeAmount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ChequeDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RegisteredDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[1000x]" Member="_1000x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[500x]" Member="_500x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[100x]" Member="_100x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[50x]" Member="_50x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[20x]" Member="_20x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[10x]" Member="_10x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[5x]" Member="_5x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[2x]" Member="_2x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[1x]" Member="_1x" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Church_OfferingDetail_Church_Accountdetail" Member="Church_OfferingDetail" ThisKey="Offering_type" OtherKey="Offering_id" Type="Church_OfferingDetail" IsForeignKey="true" />
      <Association Name="Church_BankDetail_Church_Accountdetail" Member="Church_BankDetail" ThisKey="Bankname" OtherKey="Bank_id" Type="Church_BankDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Church_BankDetail" Member="Church_BankDetails">
    <Type Name="Church_BankDetail">
      <Column Name="Bank_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Bank_name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Church_BankDetail_Church_Accountdetail" Member="Church_Accountdetails" ThisKey="Bank_id" OtherKey="Bankname" Type="Church_Accountdetail" />
    </Type>
  </Table>
</Database>