WITH T_FIRST (CATALOG_ID,CATALOG_NAME,CATEGORY_ID,CATEGORY_NAME,SUBCATID_L1,SUBCATNAME_L1,SUBCATID_L2,SUBCATNAME_L2,SUBCATID_L3,SUBCATNAME_L3,SUBCATID_L4,SUBCATNAME_L4,FAMILY_ID,FAMILY_NAME,SUBFAMILY_ID,SUBFAMILY_NAME,PRODUCT_ID)
AS
(
Select F.CATALOG_ID,c.CATALOG_NAME,'','','','','','','','','','',F1.PARENT_FAMILY_ID,'',F.FAMILY_ID,
F1.FAMILY_NAME,T.PRODUCT_ID 
From TB_PROD_FAMILY T,TB_CATALOG_FAMILY F,TB_FAMILY F1,TB_CATALOG c where F.FAMILY_ID=F1.FAMILY_ID  AND  T.FAMILY_ID=F.FAMILY_ID AND
F.CATALOG_ID=c.CATALOG_ID AND F.CATEGORY_ID='HC107' and F.CATALOG_ID='1' and PARENT_FAMILY_ID >0
),
T_SEC (CATALOG_ID,CATALOG_NAME,CATEGORY_ID,CATEGORY_NAME,SUBCATID_L1,SUBCATNAME_L1,SUBCATID_L2,SUBCATNAME_L2,SUBCATID_L3,SUBCATNAME_L3,SUBCATID_L4,SUBCATNAME_L4,FAMILY_ID,FAMILY_NAME,SUBFAMILY_ID,SUBFAMILY_NAME,PRODUCT_ID)
AS
(
Select F.CATALOG_ID,c.CATALOG_NAME,'','','','','','','','','','',F.FAMILY_ID,F1.FAMILY_NAME,'','',
T.PRODUCT_ID 
From TB_PROD_FAMILY T,TB_CATALOG_FAMILY F,TB_FAMILY F1,TB_CATALOG c  where F.FAMILY_ID=F1.FAMILY_ID  AND  T.FAMILY_ID=F.FAMILY_ID AND
F.CATALOG_ID=c.CATALOG_ID AND F.CATEGORY_ID='HC107' and F.CATALOG_ID='1' and PARENT_FAMILY_ID = 0
)
,
T_TH (CATALOG_ID,CATALOG_NAME,CATEGORY_ID,CATEGORY_NAME,SUBCATID_L1,SUBCATNAME_L1,SUBCATID_L2,SUBCATNAME_L2,SUBCATID_L3,SUBCATNAME_L3,SUBCATID_L4,SUBCATNAME_L4,FAMILY_ID,FAMILY_NAME,SUBFAMILY_ID,SUBFAMILY_NAME,PRODUCT_ID)
AS
(
Select F.CATALOG_ID,c.CATALOG_NAME,'','','','','','','','','','',F.FAMILY_ID,'','','','' From TB_CATALOG_FAMILY F,TB_FAMILY F1,TB_CATALOG c  where F.FAMILY_ID=F1.FAMILY_ID  AND 
F.CATALOG_ID=c.CATALOG_ID AND F.CATEGORY_ID='HC107' and F.CATALOG_ID='1' and PARENT_FAMILY_ID = 0 
EXCEPT 
Select F.CATALOG_ID,c.CATALOG_NAME,'','','','','','','','','','',F1.PARENT_FAMILY_ID,'','','','' From TB_PROD_FAMILY T,TB_CATALOG_FAMILY F,TB_FAMILY F1,TB_CATALOG c where F.FAMILY_ID=F1.FAMILY_ID  AND  T.FAMILY_ID=F.FAMILY_ID AND
F.CATALOG_ID=c.CATALOG_ID AND F.CATEGORY_ID='HC107' and F.CATALOG_ID='1' and PARENT_FAMILY_ID >0
),
TOT AS
(
SELECT * FROM T_FIRST UNION ALL SELECT * FROM T_SEC UNION ALL SELECT * FROM T_TH
)
SELECT * FROM TOT
--,
--FINAL
--AS
--(
--DECLARE @HIERARCHY_LEVEL INT;
--SET @HIERARCHY_LEVEL = 0;
--SELECT *,SUBCATID_L2=CASE @HIERARCHY_LEVEL
--WHEN 0 THEN 'HC107'
--WHEN 1 THEN 'HC007'
--ELSE 'HC107'
--FROM TOT
--)
--SELECT * FROM FINAL
--SELECT SUBCATID_L2='HC107',SUBCATNAME_L2='Unit Coolers' FROM TOT
--SELECT MAX(HIERARCHY_LEVEL) FROM Category_Function_top(1,'HC107')
--SELECT CATEGORY_ID,CATEGORY_NAME,HIERARCHY_LEVEL from Category_Function_top(1,'HC107')