IF(@MAXHIERARCHY=4)
   BEGIN 
	IF @HIERARCHY_LEVEL=0
		 update TEMP SET SUBCATID_L4='HC107' ,SUBCATNAME_L4='Unit Coolers'
		 
	IF @HIERARCHY_LEVEL=1
		update TEMP SET SUBCATID_L3='HC107' ,SUBCATNAME_L3='Unit Coolers'
		
	IF @HIERARCHY_LEVEL=2
		update TEMP SET SUBCATID_L2='HC107',SUBCATNAME_L2='Unit Coolers'
		 
	IF @HIERARCHY_LEVEL=3
		update TEMP SET SUBCATID_L1='HC107',SUBCATNAME_L1='Unit Coolers'
		 
	IF @HIERARCHY_LEVEL=4
		update TEMP SET CATEGORY_ID='HC107',CATEGORY_NAME='Unit Coolers'
		 
  END
 IF(@MAXHIERARCHY=3)
   BEGIN
	IF @HIERARCHY_LEVEL=0
		update TEMP SET SUBCATID_L3='HC107',SUBCATNAME_L3='Unit Coolers'
		
	IF @HIERARCHY_LEVEL=1
		update TEMP SET SUBCATID_L2='HC107',SUBCATNAME_L2='Unit Coolers'
		
	IF @HIERARCHY_LEVEL=2
		update TEMP SET SUBCATID_L1='HC107',SUBCATNAME_L1='Unit Coolers'
		
	IF @HIERARCHY_LEVEL=3
		update TEMP SET CATEGORY_ID='HC107',CATEGORY_NAME='Unit Coolers'
		
	END
 IF(@MAXHIERARCHY=2)		
	BEGIN
	IF @HIERARCHY_LEVEL=0
		update TEMP SET SUBCATID_L2='HC107',SUBCATNAME_L2='Low Profile'
		
	IF @HIERARCHY_LEVEL=1
		update TEMP SET SUBCATID_L1='HC009',SUBCATNAME_L1='Walk-In Unit Coolers'
		
	IF @HIERARCHY_LEVEL=2
		update TEMP SET CATEGORY_ID='HC107',CATEGORY_NAME='Unit Coolers'
		
	END
 IF(@MAXHIERARCHY=1)
	BEGIN	
	IF @HIERARCHY_LEVEL=0
		update TEMP SET SUBCATID_L1='HC107',SUBCATNAME_L1='Unit Coolers'
		
	IF @HIERARCHY_LEVEL=1
		update TEMP SET CATEGORY_ID='HC107',CATEGORY_NAME='Unit Coolers'
		
	END	
 IF(@MAXHIERARCHY=0)	
	BEGIN 
	IF @HIERARCHY_LEVEL=0
		update TEMP SET CATEGORY_ID='HC107',CATEGORY_NAME='Unit Coolers'
	 END		
	 
	 
	 
	 
	 
	 
