

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - March - 2007 ::</title>
</head>
<script language="JavaScript">

<!--



function NewWindow(url) {                       

                var hWnd = window.open(url,"Window","width=520,height=400,resizable=no,scrollbars=yes,left=100,top=25");

                if (hWnd.focus != null) hWnd.focus();

        }



// -->

</script>

<body topmargin="0" leftmargin="0" rightmargin="0">


<div align="left">


<table border="0" width="780" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top1.php"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="741" bgcolor="#FFFCE8" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="741" bgcolor="#EFEFE9" colspan="3" align=center height="10">
            <div align="left">
				<table border="0" style="border-collapse: collapse" width="23%" cellpadding="0">
					<tr>
						<td width="2" bgcolor="#FF0000" height="30" style="border-left-style: solid; border-left-width: 1px; border-right-width: 1px; border-top-width: 1px; border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#000000">&nbsp;</td>
						<td valign="bottom" style="border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#FF0000">
            <p align="left" style="margin-left: 5px">
			<b><font face="Verdana" size="1">
            COVER</font></b></td>
					</tr>
				</table>
			</div>
			</td>
          </tr>
          <tr>
            <td width="7" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="492" bgcolor="#FFFFFF" valign="top">

<p align="center" style="margin-left: 10px; margin-right: 10px"><font face="Verdana" size="1">
<br>
<img border="0" src="cover1.jpg" width="400" height="314"></font></p>
<p align="justify" style="margin-left: 10px; margin-right: 10px">
<font face="Verdana" size="1">
<b>Economic expert Dr Badr El-din A. Ibrahim takes stock of the banking sector’s 
performance, and analyses the driving factors behind it</b></font></p>
<p align="justify" style="margin-left: 10px; margin-right: 10px">
<font face="Verdana" size="1">
For four successive years, the banking system of Oman has picked up in almost all 
industry aggregates. The upswing can be seen in the Central Bank of Oman’s (CBO) 
combined balance sheet of commercial banks as on December 2006-end. The towering 
credit and deposit growth rates and the relatively stable and low (but 
increasing) interest rate, as well as enhanced liquidity generated by high oil 
prices and buoyant economy meant good fortune for the Oman’s banking sector in 
the last few years. Strong economic growth, modest (but increasing rate of) 
inflation, favourable internal and external positions, easy liquidity 
conditions–created by strong growth of money supply and escalating foreign 
exchange reserves–characterised the economy during the last few years, and not 
only between 2005-2006. <br>
<br>
The sound economic performance has been highly praised by international 
organisations and rating agencies. Recently, Standard and Poor’s raised Oman’s 
credit rating from ‘-BBB’ to ‘-A’ and its long-term foreign and local currency 
sovereign credit ratings to ‘A’. ‘The short-term sovereign credit ratings on 
Oman were also raised to ‘A-1’ from ‘A-2’. Fraser Institute has ranked Oman’s 
economy as 17th in the world and the first among the Arab states in economic 
freedom, in 2006. <br>
<br>
<b>Sound performance</b><br>
During the year, CBO initiated changes in the minimum capital requirements for 
banks, altered the modalities of reserve requirements and actively pursued 
liquidity management. Risk-based supervisory framework has been put in place and 
steps have been taken to ensure smooth transition to Basle-II. <br>
<br>
Total assets, total credits and credits to the private sector, customer deposits 
and net profits (after provisions and taxes) continued to remain significantly 
favourable during 2006 (see comparative table on ‘Key banking performance 
indicators’ in page 46). <br>
<br>
Total deposits increased by 24.2 per cent, mainly the outcome of quasi money. 
Both saving and time deposits accelerated while the growth of demand deposits 
was almost sluggish, increasing by only 3.5 per cent. Saving deposits increased 
by 18.1 per cent, while time deposits went up by 43.1 per cent. The increase in 
total deposits was mainly because of private sector deposits, which increased by 
almost five times compared to public enterprises’ deposits. <br>
<br>
Private credit, which constitutes 93.5 per cent of total credits, increased by 
20.5 per cent. What’s amazing is that the growth of deposits is higher than the 
growth in lending. This is a good sign and indicates that there is a reversal in 
the historical trend where growth in banking loans exceeded the growth in 
deposits. Total accumulated assets of commercial banks increased by almost 28 
per cent, while foreign assets went up by nearly 66 per cent.<br>
<br>
The excellent monetary and money market conditions meant that domestic liquidity 
(M1)* increased 24.5 per cent from RO3,573 million to RO4,448.3 million between 
2005 and 2006, while (M2)** registered a growth of 8.1 per cent. According to 
CBO, the absorption of sustained surplus conditions in the banking system is 
always made through issuance of CDs, and infrequent injection of short-term 
liquidity. Banks’ investment in CDs stood at RO 249 million by the end of 2006. 
Average RO deposit rates increased by nearly 32 per cent, while the RO average 
lending rate increased by only 5 per cent. As a result, the interest rate 
spreading narrowed. Finally, the combined commercial banks’ net profit, after 
provisions and taxes, escalated by 28 per cent between 2005 and 2006, while the 
growth rate between 2004 and 2005 was as high as 55.2 per cent. <br>
<br>
<b>Future outlook </b> <br>
<img border="0" src="cover3.jpg" width="300" height="164" align="right">More banks are expected to come up in the future and existing banks will be 
looking to expand their network and product portfolio to get maximum benefit in 
2007 from the buoyancy in the market. This will also increase competition in the 
market which could lead to launch of new services for the customers. Local banks 
though have to be more cautious in the light of foreign banks showing keen 
interest in Omani market. Currently, local banks roughly control 75 per cent of 
the market. We might see local banks entering into more strategic alliances and 
partnerships with major international financial companies to defend and 
consolidate their market share. On the one hand, we have Bank of Beirut opening 
shop here and Qatar National Bank getting approval to open a full service 
branch, while on the other new local entities like Bank Sohar are making an 
entry too. Even Alliance Housing Bank’s application for a commercial banking 
license has been granted approval in principle. It will also lead to more job 
opportunities, specifically for Omanis.<br>
<br>
The future is distinguished from the past by further competition for market 
shares. The Omani banking industry needs to be fully prepared for this and banks 
should be ready to substantially enhance their financial fundamentals and 
improve their customer services over the next few years. Improvement in credit 
and asset quality, reduction in levels of problem loans, provision of 
state-of-the-art, world-class technology infrastructure, and further improvement 
in liquidity positions need to be among the main areas of focus. The banks 
should also stress on revenue growth and diversification, besides aiming to 
reduce cost to income ratio and increasing profit from their core operations. In 
their enthusiasm to lure business, the banks should be watchful while lending to 
avoid increased non-performing assets.<br>
<br>
At the macro level, the future outlook is stable, if not promising. 
Nevertheless, the continuation of current remarkable banking performance is 
subject to many future circumstances and policies. In addition to the prudent 
banking regulations by the CBO and the continued stable macroeconomic and 
financial policies’ outcomes in the near future, Oman’s banking system will also 
depend on uncontainable factors like sustainable oil price-led liquidity. The 
fiscal policy needs to move away from vulnerability to fluctuations in oil 
production and prices if the banking system has to continue its current healthy 
condition.<br>
<br>
Moreover, other policy-related internal factors are also crucial. The recently 
published Standard &amp; Poor’s report – ‘Bank Industry Risk Analysis: Oman’ – 
singled out concentration risks and funding profile weaknesses as major 
constraints facing the banking system. Therefore, the availability of investment 
avenues following the progress of diversification in progress, dismantling 
credit concentration in few investors and sectors, and enlarging banking sizes 
to enhance lending opportunities are crucial to maintain the current robustness 
in the banking system.<br>
<br>
<b>Good news all around</b><br>
Oil price is, no doubt, at an excellent level. The prices registered noticeable 
increase during 2005 and 2006, with the average oil price reaching US$48.73 per 
barrel compared with the budgeted price of US$23 per barrel in 2005.The average 
price in 2006 was US$61.69 per barrel compared with budgeted price of US$32 per 
barrel. The prospects of future oil price are also good, guiding Oman to 
estimate its 2007 budget at US$40 per barrel. The IMF World Economic Outlook 
(April 2006) has projected the oil prices to remain close to current levels for 
the foreseeable future. Due to both global demand growth and oil supply 
constraint factors–such as tight spare capacity, buoyant GDP growth, security 
concerns, and continued production risks of some large producers–oil prices are 
likely to remain as high as US$70 a barrel on an average during 2007, according 
to the IMF World Economic Outlook (September, 2006). On the other hand, the 
global growth forecasting, although remains strong, falls slightly from 5.1 per 
cent in 2006 to 4.9 per cent in 2007.<br>
<br>
Future prospects of Oman’s non-renewable economic resources also show promise. 
Total proven reserves remain intact while recent improvements in technology have 
enhanced oil recovery, although still less than the record registered before the 
decline at the beginning of the millennium. Also promising are the increasing 
liquefied natural gas exports and the growth of the non-hydrocarbon sector. 
These two output-enhancing sectors have come up with excellent performance 
during the last few years and this trend is likely to continue in the near 
future, given the steady progress in diversification initiatives and a better 
flow of FDI as a result of encouraging and friendly environment.</font></p>
<p align="justify" style="margin-left: 10px; margin-right: 10px">
<img border="0" src="cover2.jpg"><font face="Verdana" size="1"><br>
<br>
<b>Robust growth</b><br>
Macroeconomic scene in Oman is characterised by robust broad-based growth of 
both oil and non-oil sectors, partially brought about by a sound and profitable 
banking system. Nominal economic growth, which registered an impressive rate of 
24 per cent in 2005 and 21.8 per cent in 2006, is most likely to continue 
increasing in the coming years in view of escalating growth of non-petroleum 
activities and high oil prices. With excellent prospects of oil prices remaining 
stable, the fiscal outcome, which registered a surplus of 12.7 per cent of GDP 
in 2006, is projected to remain positive for the coming few years. Net external 
assets are projected to come up to 125 per cent of current accounts receipts in 
2007, while GDP per capita is projected to increase from US$12,000 in 2005 to 
over US$15,000 by 2007.<br>
<br>
Given the CBO’s policy of pegging Omani Riyal to US dollar and the high 
components of imported inflation, global inflation and the movements of the 
exchange rate of the US dollar are critical factors upsetting the future of 
inflation. After a period of subdued trend, official Inflation rate, though 
still slightly lower than the global average, has picked up gradually during the 
last few years. The CPI rose from only 0.7 per cent in 2004 to 1.9 per cent in 
2005, and further to 2.5 per cent in 2006. Based on past trends, inflation is 
not likely to be less than 4 per cent by the end of 2007. Unless some measures 
are undertaken, the inflation rate is expected to increase unabated. This would 
mean that the real values of banking aggregates will turn down in real terms.</font></p>
<p align="justify" style="margin-left: 10px; margin-right: 10px">
<b>
<font face="Verdana" size="1">&#8730; <a href="cover1.php">On A High</a><br>
&nbsp;</font></b></p>

                    </td>
            <td  valign=top bgcolor=white width="242"><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
          <tr>
            <td width="7" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="492" bgcolor="#FFFFFF" valign="top">

						<p align="right"><font face="Verdana" size="1">
						<a href="#top">Top^</a></font></td>
            <td  valign=top bgcolor=white width="242">&nbsp;</td>
          </tr>
          
          <tr>
            <td width="7" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="492" bgcolor="#FFFFFF" valign="top">

                    <hr color="#CC3333">
                    </td>
            <td  valign=top bgcolor=white width="242">&nbsp;</td>
          </tr>
          
        </table>
        </table>
        </div>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </div>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?>
        </body>
        </html>