<?	session_start();?>
<?	session_register("id");
	if(!$HTTP_SESSION_VARS["id"]=="")
	{?>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - June 2003 ::</title>
</head>

<body topmargin="0" leftmargin="0">











<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top.htm"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="5" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#FFFCE8" colspan="3" align=center><b>



<? if(!$HTTP_SESSION_VARS["id"]==""){echo "<font face=Verdana size=2 color=#000000>Welcome&nbsp;&nbsp;</font><font face=Verdana size=2 color=red><i>".$HTTP_SESSION_VARS["id"]."&nbsp;!</i></font>
            ";}else{echo$HTTP_SESSION_VARS["mes"];$HTTP_SESSION_VARS["mes"]="";}?>
              </b></td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF"><font size="4" color="#FF0000">
            <font face="Verdana">A profitable omen<br>
            <br>
            </font></font><font face="Verdana" size="1"><b>While 2002 saw a 
            decline in Ominvest's income, the investment company seems set to 
            bounce back, having already registered a 10 per cent jump in its Q1 
            profits this year, writes Vicky Kapur</b><br>
            <br>
            Oman International Development &amp; Investment Company SAOG (Ominvest) 
            is an investment company with interests primarily in banking, 
            leasing and manufacturing entities operating in Oman; and overseas 
            securities portfolios, including exposure to private equity.<br>
            <br>
            <b>Financials</b><br>
            Ominvest recently announced its first quarter results, reporting an 
            impressive 9.9 per cent jump in its consolidated profits Ð from 
            RO1.30 million in Q1 2002 to RO 1.43 million in Q1 2003. The 
            investment company's banking subsidiary, Oman Arab Bank SAOC, 
            reported a 11.5 per cent increase in profits &quot;mainly due to an 
            increase in net interest income and lower provisioning,&quot; asserts 
            Taya bin Jandal bin Ali, the chairman of Ominvest. <br>
            In 2002, Ominvest registered a decline of 3.94 per cent in its total 
            revenue. Ali attributes this fall to the negative investment climate 
            in the region. &quot;Ominvest had expected an improvement in economic 
            conditions in 2002 both in Oman and overseas. While conditions in 
            Oman did improve due to firmer oil prices and government spending 
            focused on projects, geo-political events within the region and 
            economic uncertainty in the US and other developed markets continued 
            to present a difficult investing environment elsewhere,&quot; he says.
            <br>
            However, the company managed to maintain its revenue stream last 
            year due to the diversity of its business portfolio. &quot;In spite of 
            this difficult background, the company's policy of diversifying its 
            asset base has enabled it to weather the uncertainty and to report 
            substantially improved results underpinned by profits generated by 
            the banking subsidiary and local associates and returns from the 
            local investment portfolio,&quot; says Ali.<br>
            The net increase of RO3.22 million in the company's profits Ñ from 
            RO1.32 million in 2001 to RO4.54 million in 2002 Ñ can be largely 
            attributed to an increase in valuation of investments (from RO1.97 
            million in 2001 to RO4.17 million in 2002) and an increase in the 
            net interest income (RO12.66 million in 2001 to RO13.92 million in 
            2002). Despite this, the company's rank in The OER 20 fell from No. 
            8 in 2001 to No. 11 in 2002 largely due to the entry of companies 
            generating more revenue during the year. <br>
            <br>
            <b>Performance<br>
            Local investments:</b> Ominvest's major subsidiary, Oman Arab Bank 
            SAOC, reported improved results on the back of higher net interest 
            margins and gains recorded on its investment portfolio. The bank 
            reported a profit of RO7.57 million, an increase of 25.9 per cent 
            compared with RO6.01 million reported in 2001.<br>
            Lower interest rates benefited leasing companies and both Muscat 
            Finance Co. and National Finance Co. reported results in line with 
            expectations. &quot;The company's preferred strategy is to hold 
            investments for the longer term and to disregard short-term 
            volatility provided the underlying business, economic and management 
            characteristics of the investing companies remain favourable,&quot; says 
            Ali.<br>
            <b>Overseas marketable portfolio:</b> The company's overseas trading 
            portfolio returned 1.04 per cent in 2002 against the substantial 
            20.6 per cent decline in the World MSCI (US$). According to Ali, 
            &quot;This relative out-performance of our portfolio is also evident over 
            longer periods.&quot; Overseas private equity portfolio: The economic 
            fallout in the US and other markets impacted the company's private 
            equity portfolio, in which provisions of RO1 million offset the 
            minor gains made in 2002. Avers Ali: &quot;We believe that the volatility 
            and unpredictability of earnings in this area is compensated by the 
            excellent returns achieved over the longer term.&quot; <br>
            <br>
            <b>Outlook</b><br>
            &quot;This performance was due to the good results recorded by our 
            investments in the banking, leasing and industrial sectors in Oman 
            and also excellent returns from the local marketable portfolio,&quot; 
            says Ali.<br>
            We are aware that the global economy remains troubled and may be 
            impacted by recent developments in the region. However, we would 
            hope that the strength of our major investments in Oman and the 
            diversification of our portfolios contribute to improved results in 
            2003, he says. <br>
            &quot;The state of the global economy remains fragile and may be further 
            impacted by developments in the region. We are cautiously optimistic 
            about the prospects for 2003 and would expect the banking subsidiary 
            and other local associates to continue to provide the main 
            contribution to profits,&quot; he adds. </font>

                    <hr color="#CC3333">
                    <p>&nbsp;</td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
        </div>
      </center>
        </table>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?>
<p>
        <?}
else 
Header("Location:/inc/error.php");
?>
        </body>
        </html>