<?	session_start();?>
<?	session_register("id");
	if(!$HTTP_SESSION_VARS["id"]=="")
	{?>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - January - 2006 ::</title>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top1.php"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="5" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#FFFCE8" colspan="3" align=center><b>



<? if(!$HTTP_SESSION_VARS["id"]==""){echo "<font face=Verdana size=2 color=#000000>Welcome&nbsp;&nbsp;</font><font face=Verdana size=2 color=red><i>".$HTTP_SESSION_VARS["id"]."!</i></font>
            ";}else{echo$HTTP_SESSION_VARS["mes"];$HTTP_SESSION_VARS["mes"]="";}?>
              </b></td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">

<p align="justify" dir="ltr"><font face="Verdana" size="2" color="#C0C0C0">:: 
CAR TALK<br>
</font><font face="Verdana" size="4" color="#FF0000">
<br>
</font><b><font face="Verdana" size="5" color="#FF0000">Hyundai Azera – the new 
challenger in E-class</font></b><font face="Verdana" size="4" color="#FF0000"><br>
</font><font face="Verdana" size="1">
<br>
</font><font face="Verdana" size="3">
<b>
<img border="0" src="car_talk.jpg" width="300" height="204" align="left" hspace="5" vspace="2">F</b></font><font face="Verdana" size="1">resh 
with the success of the new Sonata in 2005, Hyundai Motor is all set to create a 
challenge for its European and Asian competitors in the E-class segment in 2006. 
Unveiled at the Geneva Motor Show in 2005, Hyundai’s new luxury Sedan Azera 
(known as Grandeur in some markets) will be launched in the Sultanate by OTE in 
January.<br>
<br>
Oman Economic Review (OER) was invited by Hyundai Motor to test drive the new 
vehicle at South Korea’s serene Jeju Island under the punishing chilly and windy 
conditions after an eye opening trip to Hyundai’s Asan plant (in mainland South 
Korea) where robots have replaced human beings in the manufacturing process.<br>
<br>
Jeju Island came into existence 700 to 1,200 thousand years ago when lava spewed 
from a sub-sea volcano and surfaced above the waters. Mt. Halla, formed as a 
result of the volcanic eruption, rises in the centre of Jeju Island to 1950m 
above sea level. The rest of the island slopes down from its summit and is 
covered with dark grey volcanic rocks and volcanic ash soil. Relatively isolated 
from the rest of the world, the island's nature has been well preserved in its 
prehistoric state. The travel to Jeju Island is akin to traveling back in time.<br>
<br>
Back to the test drive, the next day morning I was given the test drive road 
route along with the key of the brand new Azera. I was thrilled but a bit scared 
to drive the beautiful monster on the 160-km long route, which I was treading 
for the first time. A few seconds in the driver’s seat and I was feeling 
comfortable in the car’s pleasing and relaxing interior style and design. The 
elegant dashboard lines and stylish instrument panel immediately catch your 
attention. The extra space generated by the longer wheelbase gives a more 
spacious feeling. The supportive seats, well planned ergonomics, easy access and 
high quality trim materials are expected to appeal to the E-class buyers. Azera 
offers personal comfort facilities that range from sunglass storage and cup 
holders to rear passenger comfort lights and handbag hooks. <br>
<br>
On my journey, I could see fantastically shaped rocks decorating the seashores, 
the hundreds of Oreums (secondary volcanos), stud farms, rice fields, tangerine 
plantations with ripe orange colour fruits hanging on the plants, lots of 
colourful flowers in bloom and dangerous slopes and curvaceous roads 
criss-crossing the forest. <br>
<br>
A few kilometers on the road and I was impressed with the comfortable driving 
experience. Azera offers easy handling and a smooth ride. The 5-speed 
electronically controlled automatic gearbox with H-matic offers smooth 
clutch-less gear shifting. Its road holding, stability and handling precision is 
going to be its major draw among its potential buyers. <br>
<br>
During the coffee break, after covering more than 76 kms, a senior Hyundai 
official at the make shift coffee stall (which was constantly challenged by the 
blowing wind) told me, “Azera’s double wishbone front suspension and redesigned 
in-wheel type multi-link rear suspension have been adapted with Electronic 
Stability Programme (ESP) standard to make it compete at the highest level in 
terms of on-road precision, safety and comfort.” <br>
<br>
Moving further towards the White House (a beach front hotel where I had to halt 
for a lunch break), I tested the pick-up of the 3.3 litre vehicle. Driving on a 
straight long wide road, I reached over 160 kms within a few seconds with little 
effort in spite of going against the wind. With the increased speed, I had 
expected the noise generated by the high winds outside to intrude inside the 
car. But the noise inside was minimal. Perhaps this factor was given extra 
attention while designing the car’s aerodynamics. <br>
<br>
All credit goes to Hyundai’s wind tunnel development, which gives the car 
directional stability and low level of interior noise. The improved flexible 
sealing strips and a center under-floor panel also help reduce wind noise 
intrusion even further. <br>
<br>
After a sumptuous lunch, I embarked on the final leg of my journey back to Hotel 
Shilla via Geumreung beach. The journey took me to some of the areas, which 
reminded of how Koreans lived years ago. I caught a glimpse of the old style of 
living with traditional stone houses with thatched roofs and barnyards. Azera 
kept me going on narrow roads, many of which were not even properly paved, with 
minimum discomfort.<br>
<br>
On reaching my final destination, as I stepped out of the car, I couldn’t stop 
myself from admiring the beautiful 4,895-mm long beauty on the 17” inch alloy 
wheels. <br>
<br>
Despite being in the E-class segment, Azera has a striking family resemblance to 
the new Sonata. After the ride, I could make out what makes Hyundai so confident 
of competing head on with a number of established European and Japanese E-class 
auto brands and expects to sell 260,000 units of Azera globally with the Middle 
East expected to contribute roughly 4 per cent of it. <br>
<br>
In Oman, Hyundai Azera is going to appeal to the mature executive car buyers 
looking for elegant-looking, powerful yet safe and comfortable luxurious sedans. 
- Akshay Bhatnagar</font></p>
<table border="0" cellpadding="0" style="border-collapse: collapse" width="100%" id="table1" height="229">
  <tr>
    <td colspan="2" bgcolor="#FFF8BF" height="25">
    <p align="center"><b><font face="Verdana" size="1">
    Specifications of new Hyundai Azera</font></b></td>
  </tr>
  <tr>
    <td height="16" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Length </font></b></td>
    <td height="16" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    4,895 mm </font></td>
  </tr>
  <tr>
    <td height="16" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Width </font></b></td>
    <td height="16" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    1,865 mm </font></td>
  </tr>
  <tr>
    <td height="16" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Height </font></b></td>
    <td height="16" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    1,490 mm </font></td>
  </tr>
  <tr>
    <td height="16" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Wheel Base</font></b></td>
    <td height="16" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    2,780 mm </font></td>
  </tr>
  <tr>
    <td height="16" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Engine type </font></b></td>
    <td height="16" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    DOHC </font></td>
  </tr>
  <tr>
    <td height="16" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Displacement (cc)</font></b></td>
    <td height="16" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    3,342 </font></td>
  </tr>
  <tr>
    <td height="16" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Maximum Power (kW/rpm) </font></b></td>
    <td height="16" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    173 (235ps)/6,000 </font></td>
  </tr>
  <tr>
    <td height="17" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Maximum Torque (Nm/rpm) </font></b></td>
    <td height="17" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    304(31kg.m) / 3.500 </font></td>
  </tr>
  <tr>
    <td height="17" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Brakes (Front)</font></b></td>
    <td height="17" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    16-inch Ventilated Disc, 1 Pot-caliper Brake with pad wear warning device </font>
    </td>
  </tr>
  <tr>
    <td height="17" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Brakes (Rear)</font></b></td>
    <td height="17" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    15-inch Solid Disc Brake with Parking Brake System, 1 Pot-caliper Brake with 
    pad wear warning device </font></td>
  </tr>
  <tr>
    <td height="17" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Suspension (Front) </font></b></td>
    <td height="17" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    Double wishbone type with stabilizer bar </font></td>
  </tr>
  <tr>
    <td height="17" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Suspension (Rear)</font></b></td>
    <td height="17" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    Multi-link type with stabilizer bar </font></td>
  </tr>
  <tr>
    <td height="17" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Tyre</font></b></td>
    <td height="17" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    225/60R16. 235/55R17 </font></td>
  </tr>
  <tr>
    <td height="17" bgcolor="#FFF9CC" width="30%">
    <p style="margin-left: 10px"><b><font face="Verdana" size="1">
    Fuel tank</font></b></td>
    <td height="17" bgcolor="#FFFCE8" width="70%">
    <p style="margin-left: 10px; margin-right: 5px">
    <font face="Verdana" size="1">
    75 litre</font></td>
  </tr>
</table>

                    <hr color="#CC3333">
                    </td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?>
        </body>
        </html>
        <?}
else 
Header("Location:/inc/error.php");
?>&nbsp;