SELECT * FROM TB_CATALOG WHERE CATALOG_ID=2
SELECT * FROM TB_CATEGORY WHERE CATEGORY_ID='MaheTest'
SELECT * FROM TB_CATALOG_SECTIONS WHERE CATALOG_ID=2 AND CATEGORY_ID='MAHETEST'
SELECT * FROM TB_CATALOG_FAMILY

SELECT C.CATALOG_NAME,A.CATEGORY_NAME FROM TB_CATEGORY A 
JOIN TB_CATALOG_SECTIONS B 
ON A.CATEGORY_ID=B.CATEGORY_ID
JOIN TB_CATALOG C ON C.CATALOG_ID=B.CATALOG_ID
WHERE A.CATEGORY_ID='MAHETEST' AND PARENT_CATEGORY=0

SELECT * FROM TB_CATEGORY A WHERE PARENT_CATEGORY='MaheTest'

SELECT * FROM TB_FAMILY WHERE CATEGORY_ID='MAHETEST'

SELECT * FROM TB_PRODUCT WHERE CATEGORY_ID='SUBTEST'
SELECT A.PRODUCT_ID,B.STRING_VALUE,B.NUMERIC_VALUE FROM TB_PRODUCT A 
JOIN TB_PROD_SPECS B ON A.PRODUCT_ID=B.PRODUCT_ID
SELECT * FROM TB_PROD_SPECS
SELECT * FROM TB_PROD_FAMILY 
SELECT * FROM TB_PROD_FAMILY_ATTR_LIST
SELECT * FROM TB_PROD_FAMILY_ATTR_LIST_BKP WHERE ATTRIBUTE_ID=1  ORDER BY ATTRIBUTE_ID

SELECT * FROM TB_ATTRIBUTE A JOIN TB_PROD_FAMILY_ATTR_LIST B ON A.ATTRIBUTE_ID=B.ATTRIBUTE_ID
JOIN 