CREATE TABLE TEST([CATALOG_ID] [int] NULL,[CATALOG_NAME] [nvarchar](100) NULL,[CATEGORY_ID] [nvarchar](500) NULL,[CATEGORY_NAME] [nvarchar](500) NULL,[SUBCATID_L1] [nvarchar](50) NULL,[SUBCATNAME_L1] [nvarchar](500) NULL,[SUBCATID_L2] [nvarchar](50) NULL,[SUBCATNAME_L2] [nvarchar](500) NULL,[SUBCATID_L3] [nvarchar](50) NULL,[SUBCATNAME_L3] [nvarchar](500) NULL,[SUBCATID_L4] [nvarchar](50) NULL,[SUBCATNAME_L4] [nvarchar](500) NULL,[FAMILY_ID] [int] NULL,[FAMILY_NAME] [nvarchar](400) NULL,[SUBFAMILY_ID] [int] NULL,[SUBFAMILY_NAME] [nvarchar](max) NULL,[PRODUCT_ID] [int] NULL)
GO
INSERT INTO TEST Select F.CATALOG_ID,  c.CATALOG_NAME, '' CATEGORY_ID, '' CATEGORY_NAME, '' SUBCATID_L1, '' SUBCATNAME_L1,  '' SUBCATID_L2,  '' SUBCATNAME_L2, '' SUBCATID_L3, '' SUBCATNAME_L3, '' SUBCATID_L4, '' SUBCATNAME_L4, F1.PARENT_FAMILY_ID FAMILY_ID, ''FAMILY_NAME,  F.FAMILY_ID SUBFAMILY_ID,  F1.FAMILY_NAME SUBFAMILY_NAME,  T.PRODUCT_ID PRODUCT_ID  From TB_PROD_FAMILY T,TB_CATALOG_FAMILY F, TB_FAMILY F1, TB_CATALOG c   where F.FAMILY_ID=F1.FAMILY_ID AND T.FAMILY_ID=F.FAMILY_ID AND F.CATALOG_ID=c.CATALOG_ID AND  F.CATEGORY_ID='HC107' AND F.CATALOG_ID='1'  AND PARENT_FAMILY_ID >0  
GO
INSERT INTO TEST Select F.CATALOG_ID,c.CATALOG_NAME,'' CATEGORY_ID,'' CATEGORY_NAME,'' SUBCATID_L1,'' SUBCATNAME_L1,'' SUBCATID_L2,'' SUBCATNAME_L2,'' SUBCATID_L3,'' SUBCATNAME_L3,'' SUBCATID_L4,'' SUBCATNAME_L4,F.FAMILY_ID,F1.FAMILY_NAME,'' SUBFAMILY_ID,'' SUBFAMILY_NAME,T.PRODUCT_ID From TB_PROD_FAMILY T,TB_CATALOG_FAMILY F,TB_FAMILY F1,TB_CATALOG c  where F.FAMILY_ID=F1.FAMILY_ID  AND  T.FAMILY_ID=F.FAMILY_ID AND F.CATALOG_ID=c.CATALOG_ID AND F.CATEGORY_ID='HC107' and F.CATALOG_ID='1' and PARENT_FAMILY_ID = 0
GO
INSERT INTO TEST Select F.CATALOG_ID,c.CATALOG_NAME,'' CATEGORY_ID, '' CATEGORY_NAME, '' SUBCATID_L1, '' SUBCATNAME_L1,  '' SUBCATID_L2,  '' SUBCATNAME_L2, '' SUBCATID_L3, '' SUBCATNAME_L3, '' SUBCATID_L4, '' SUBCATNAME_L4,F.FAMILY_ID,'' FAMILY_NAME,  '' SUBFAMILY_ID,  '' SUBFAMILY_NAME,  '' PRODUCT_ID From TB_CATALOG_FAMILY F,TB_FAMILY F1,TB_CATALOG c  where F.FAMILY_ID=F1.FAMILY_ID AND F.CATALOG_ID=c.CATALOG_ID AND F.CATEGORY_ID='HC107' and F.CATALOG_ID='1' and PARENT_FAMILY_ID = 0 EXCEPT Select F.CATALOG_ID,c.CATALOG_NAME,'' CATEGORY_ID, '' CATEGORY_NAME, '' SUBCATID_L1, '' SUBCATNAME_L1,  '' SUBCATID_L2,  '' SUBCATNAME_L2, '' SUBCATID_L3, '' SUBCATNAME_L3, '' SUBCATID_L4, '' SUBCATNAME_L4,F1.PARENT_FAMILY_ID,'' FAMILY_NAME,  '' SUBFAMILY_ID,  '' SUBFAMILY_NAME,  '' PRODUCT_ID From TB_PROD_FAMILY T,TB_CATALOG_FAMILY F,TB_FAMILY F1,TB_CATALOG c where F.FAMILY_ID=F1.FAMILY_ID  AND  T.FAMILY_ID=F.FAMILY_ID AND F.CATALOG_ID=c.CATALOG_ID AND F.CATEGORY_ID='HC107' and F.CATALOG_ID='1' and PARENT_FAMILY_ID >0
GO


DECLARE @QUERY VARCHAR(MAX);
DECLARE @SESS_ID VARCHAR(MAX)='TEST';
DECLARE @MAXHIERARCHY INT;
SET @MAXHIERARCHY =(SELECT MAX(HIERARCHY_LEVEL) FROM Category_Function_top('1','HC107'))
DECLARE @CATEGORY_ID nvarchar(100)
DECLARE @CATEGORY_NAME NVARCHAR(100)
DECLARE @HIERARCHY_LEVEL INT
DECLARE @UPDAT CURSOR 
SET @UPDAT = CURSOR FOR
SELECT CATEGORY_ID,CATEGORY_NAME,HIERARCHY_LEVEL from Category_Function_top('1','HC107')
OPEN @UPDAT
FETCH NEXT
FROM @UPDAT INTO @CATEGORY_ID,@CATEGORY_NAME,@HIERARCHY_LEVEL
 WHILE @@FETCH_STATUS=0
  BEGIN  
 IF(@MAXHIERARCHY=4)
   BEGIN 
	IF @HIERARCHY_LEVEL=0
		 SET @QUERY ='update ' +@SESS_ID+' SET SUBCATID_L4='+''''+@CATEGORY_ID+''''+' ,SUBCATNAME_L4='+''''+@CATEGORY_NAME+''''
		 EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update ' + @SESS_ID+' SET SUBCATID_L3='+''''+@CATEGORY_ID+''''+' ,SUBCATNAME_L3='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=2
		SET @QUERY ='update ' +@SESS_ID+' SET SUBCATID_L2='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L2='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY) 
	IF @HIERARCHY_LEVEL=3
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY) 
	IF @HIERARCHY_LEVEL=4
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY) 
  END
 IF(@MAXHIERARCHY=3)
   BEGIN
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L3='+''''+@CATEGORY_ID+''''+ ',SUBCATNAME_L3='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L2='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L2='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=2
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=3
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	END
 IF(@MAXHIERARCHY=2)		
	BEGIN
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L2='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L2='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update ' +@SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=2
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	END
 IF(@MAXHIERARCHY=1)
	BEGIN	
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	END	
 IF(@MAXHIERARCHY=0)	
	BEGIN 
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	 END		
FETCH NEXT 
FROM @UPDAT INTO  @CATEGORY_ID,@CATEGORY_NAME,@HIERARCHY_LEVEL
   END
CLOSE @UPDAT
DEALLOCATE @UPDAT

GO


UPDATE TEST SET  FAMILY_NAME = TF.FAMILY_NAME 
FROM TB_FAMILY TF WHERE TF.FAMILY_ID=TEST.FAMILY_ID

GO



--DROP TABLE TEST


SELECT * FROM TEST
