select DISTINCT(ta.ATTRIBUTE_NAME) 
INTO TTEST 
from TB_PROD_SPECS tps,
TB_ATTRIBUTE ta
where tps.ATTRIBUTE_ID = ta.ATTRIBUTE_ID AND 
PRODUCT_ID IN (select distinct(PRODUCT_ID) AS PRODUCT_ID from TEST where PRODUCT_ID<>0)


SELECT * FROM TTEST