<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true"
    CodeFile="AdminHome.aspx.cs" Inherits="AdminHome" MaintainScrollPositionOnPostback="true" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="Server">
    <table cellpadding="0" cellspacing="0" align="center">
        <tr>
            <td colspan="3">
                <br />
            </td>
        </tr>
        <tr>
            <td colspan="3">
                Enter the Categories:
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <br />
            </td>
        </tr>
        <tr height="25px">
            <td>
                Categories:
            </td>
            <td width="200px">
                <asp:DropDownList ID="ddlCategories" runat="server" Width="143px" AutoPostBack="True"
                    OnSelectedIndexChanged="ddlCategories_SelectedIndexChanged">
                </asp:DropDownList>
            </td>
            <td width="500px">
                <asp:Label ID="lbCateName" runat="server" Text="Category" Visible="False"></asp:Label>
                <asp:TextBox ID="txtCateADD" runat="server" Visible="False"></asp:TextBox>
                <asp:Label ID="lbRate" runat="server" Text="Rate" Visible="False"></asp:Label>
                <asp:TextBox ID="txtRate" runat="server" Visible="False"></asp:TextBox>
                <asp:Button ID="btnADD" runat="server" Text="ADD" Visible="False" OnClick="btnADD_Click" />
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <br />
            </td>
        </tr>
        <tr>
            <td>
                Sub-Categories:
            </td>
            <td colspan="2">
                <asp:TextBox ID="txtSubCategories" runat="server" Width="150px"></asp:TextBox>
            </td>
        </tr>
        <tr>
            <td height="25px" colspan="3">
                <asp:Label ID="lbResponse" runat="server" Font-Bold="True" ForeColor="#006600"></asp:Label>
            </td>
        </tr>
        <tr>
            <td colspan="3">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<asp:Button ID="btnSubmit"
                    runat="server" Text="Submit" OnClick="btnSubmit_Click" />
            </td>
        </tr>
        <tr>
            <td colspan="3">
                <table>
                    <tr>
                        <td>
                            <asp:GridView ID="Grid" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="True"
                                AutoGenerateEditButton="True" AllowSorting="true" OnRowCancelingEdit="Grid_RowCancelingEdit"
                                OnRowDeleting="Grid_RowDeleting" OnRowUpdating="Grid_RowUpdating" OnRowEditing="Grid_RowEditing"
                                OnRowDataBound="Grid_RowDataBound" DataKeyNames="Plan_id" BackColor="#999966"
                                Width="700px">
                                <Columns>
                                  <%--  <asp:TemplateField HeaderText="S.No">
                                        <ItemTemplate>
                                            <asp:Label ID="lbNum" runat="server" Text='<%# Eval("Sno") %>'></asp:Label></ItemTemplate>
                                    </asp:TemplateField>--%>
                                    <asp:TemplateField HeaderText="S.No" Visible="false">
                                        <ItemTemplate>
                                            <asp:Label ID="lbSno" runat="server" Text='<%# Eval("Plan_id") %>'></asp:Label>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Plan">
                                        <ItemTemplate>
                                            <asp:Label ID="lbPlanName" runat="server" Text='<%# Eval("Plan_Name") %>'></asp:Label>
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <asp:TextBox ID="txtPlanName" runat="server" Text='<%# Eval("Plan_Name") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="Rate">
                                        <ItemTemplate>
                                            <asp:Label ID="lbRate" runat="server" Text='<%# Eval("Rate") %>'></asp:Label>
                                        </ItemTemplate>
                                        <EditItemTemplate>
                                            <asp:TextBox ID="txtRate" runat="server" Text='<%# Eval("Rate") %>'></asp:TextBox>
                                        </EditItemTemplate>
                                    </asp:TemplateField>
                                    <asp:TemplateField HeaderText="SubTitle">
                                        <ItemTemplate>
                                            <asp:GridView ID="GridSubtitle" runat="server" AutoGenerateColumns="false" AutoGenerateDeleteButton="true"
                                                OnRowDeleting="GridSubtitle_RowDeleting" DataKeyNames="SubCategory_id" Width="100%">
                                                <Columns>
                                                    <asp:TemplateField>
                                                        <ItemTemplate>
                                                            <table>
                                                                <tr>
                                                                    <td width="300px">
                                                                        <asp:Label ID="lbsubtitle" runat="server" Text='<%#Eval("Category_name") %>'></asp:Label>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                        </ItemTemplate>
                                                    </asp:TemplateField>
                                                </Columns>
                                            </asp:GridView>
                                        </ItemTemplate>
                                    </asp:TemplateField>
                                </Columns>
                            </asp:GridView>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</asp:Content>
