<?xml version="1.0" encoding="utf-8"?><Database Name="Payroll" Class="PayrollDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(local)\SQLEXPRESS;Initial Catalog=Payroll;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PayrollConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Payroll_AdvanceManagement" Member="Payroll_AdvanceManagements">
    <Type Name="Payroll_AdvanceManagement">
      <Column Name="Advance_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Salary_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Refund_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Advance_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Payroll_PersonalDetail_Payroll_AdvanceManagement" Member="Payroll_PersonalDetail" ThisKey="fkEmployee_ID" OtherKey="Employee_id" Type="Payroll_PersonalDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll_AdvanceRefund" Member="Payroll_AdvanceRefunds">
    <Type Name="Payroll_AdvanceRefund">
      <Column Name="Refund_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Refund_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Due_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Payroll_PersonalDetail_Payroll_AdvanceRefund" Member="Payroll_PersonalDetail" ThisKey="fkEmployee_ID" OtherKey="Employee_id" Type="Payroll_PersonalDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll_Attendance" Member="Payroll_Attendances">
    <Type Name="Payroll_Attendance">
      <Column Name="Attendance_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="In_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Out_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Payroll_PersonalDetail_Payroll_Attendance" Member="Payroll_PersonalDetail" ThisKey="fkEmployee_ID" OtherKey="Employee_id" Type="Payroll_PersonalDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll_MaritalStatus" Member="Payroll_MaritalStatus">
    <Type Name="Payroll_MaritalStatus">
      <Column Name="Marital_Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Marital_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Payroll_MaritalStatus_Payroll_PersonalDetail" Member="Payroll_PersonalDetails" ThisKey="Marital_Id" OtherKey="Marital_Status" Type="Payroll_PersonalDetail" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll_OurCompanyDetail" Member="Payroll_OurCompanyDetails">
    <Type Name="Payroll_OurCompanyDetail">
      <Column Name="Cur_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cur_JoiningDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_SalaryOnJoining" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Relieving" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Cur_CertificateProvided" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_SalaryNow" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Designation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_ResumeUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_Command" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Payroll_PersonalDetail_Payroll_OurCompanyDetail" Member="Payroll_PersonalDetail" ThisKey="fkEmployee_ID" OtherKey="Employee_id" Type="Payroll_PersonalDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll_PersonalDetail" Member="Payroll_PersonalDetails">
    <Type Name="Payroll_PersonalDetail">
      <Column Name="Employee_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Employee_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Permanent_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Present_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Photo_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_proof_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address_Proof_url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Experience" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Payroll_PersonalDetail_Payroll_AdvanceManagement" Member="Payroll_AdvanceManagements" ThisKey="Employee_id" OtherKey="fkEmployee_ID" Type="Payroll_AdvanceManagement" />
      <Association Name="Payroll_PersonalDetail_Payroll_AdvanceRefund" Member="Payroll_AdvanceRefunds" ThisKey="Employee_id" OtherKey="fkEmployee_ID" Type="Payroll_AdvanceRefund" />
      <Association Name="Payroll_PersonalDetail_Payroll_Attendance" Member="Payroll_Attendances" ThisKey="Employee_id" OtherKey="fkEmployee_ID" Type="Payroll_Attendance" />
      <Association Name="Payroll_PersonalDetail_Payroll_OurCompanyDetail" Member="Payroll_OurCompanyDetails" ThisKey="Employee_id" OtherKey="fkEmployee_ID" Type="Payroll_OurCompanyDetail" />
      <Association Name="Payroll_PersonalDetail_Payroll_Previous_CompanyDetail" Member="Payroll_Previous_CompanyDetails" ThisKey="Employee_id" OtherKey="fkEmployee_id" Type="Payroll_Previous_CompanyDetail" />
      <Association Name="Payroll_PersonalDetail_Payroll_SalaryDetail" Member="Payroll_SalaryDetails" ThisKey="Employee_id" OtherKey="fkEmployee_ID" Type="Payroll_SalaryDetail" />
      <Association Name="Payroll_MaritalStatus_Payroll_PersonalDetail" Member="Payroll_MaritalStatus" ThisKey="Marital_Status" OtherKey="Marital_Id" Type="Payroll_MaritalStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll_Previous_CompanyDetail" Member="Payroll_Previous_CompanyDetails">
    <Type Name="Payroll_Previous_CompanyDetail">
      <Column Name="Pre_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pre_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Pre_ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pre_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="fkEmployee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Payroll_PersonalDetail_Payroll_Previous_CompanyDetail" Member="Payroll_PersonalDetail" ThisKey="fkEmployee_id" OtherKey="Employee_id" Type="Payroll_PersonalDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Payroll_SalaryDetail" Member="Payroll_SalaryDetails">
    <Type Name="Payroll_SalaryDetail">
      <Column Name="Salary_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="No_Days" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Extra_Benifits" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Gross_Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Basic" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HRA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NETT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryAdvanceBalance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AdvanceDeduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PF" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ESI" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Deduction_Total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryOfMonth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Payroll_PersonalDetail_Payroll_SalaryDetail" Member="Payroll_PersonalDetail" ThisKey="fkEmployee_ID" OtherKey="Employee_id" Type="Payroll_PersonalDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_Payroll_AdvanceManagementNewDeleteCommand" Method="sp_Payroll_AdvanceManagementNewDeleteCommand">
    <Parameter Name="Original_Advance_ID" Parameter="original_Advance_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Payroll_AdvanceManagementNewInsertCommand" Method="sp_Payroll_AdvanceManagementNewInsertCommand">
    <Parameter Name="Salary_Advance" Parameter="salary_Advance" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Refund_Advance" Parameter="refund_Advance" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Advance_Date" Parameter="advance_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_AdvanceManagementNewInsertCommandResult">
      <Column Name="Advance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Salary_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Refund_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Advance_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AdvanceManagementNewSelectCommand" Method="sp_Payroll_AdvanceManagementNewSelectCommand">
    <ElementType Name="sp_Payroll_AdvanceManagementNewSelectCommandResult">
      <Column Name="Advance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Salary_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Refund_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Advance_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AdvanceManagementNewUpdateCommand" Method="sp_Payroll_AdvanceManagementNewUpdateCommand">
    <Parameter Name="Salary_Advance" Parameter="salary_Advance" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Refund_Advance" Parameter="refund_Advance" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Advance_Date" Parameter="advance_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_Advance_ID" Parameter="original_Advance_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Advance_ID" Parameter="advance_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_AdvanceManagementNewUpdateCommandResult">
      <Column Name="Advance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Salary_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Refund_Advance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Advance_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AdvanceRefundNewDeleteCommand" Method="sp_Payroll_AdvanceRefundNewDeleteCommand">
    <Parameter Name="Original_Refund_ID" Parameter="original_Refund_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Payroll_AdvanceRefundNewInsertCommand" Method="sp_Payroll_AdvanceRefundNewInsertCommand">
    <Parameter Name="Refund_Amount" Parameter="refund_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Due_Date" Parameter="due_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_AdvanceRefundNewInsertCommandResult">
      <Column Name="Refund_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Refund_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Due_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AdvanceRefundNewSelectCommand" Method="sp_Payroll_AdvanceRefundNewSelectCommand">
    <ElementType Name="sp_Payroll_AdvanceRefundNewSelectCommandResult">
      <Column Name="Refund_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Refund_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Due_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AdvanceRefundNewUpdateCommand" Method="sp_Payroll_AdvanceRefundNewUpdateCommand">
    <Parameter Name="Refund_Amount" Parameter="refund_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Due_Date" Parameter="due_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_Refund_ID" Parameter="original_Refund_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Refund_ID" Parameter="refund_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_AdvanceRefundNewUpdateCommandResult">
      <Column Name="Refund_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Refund_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Due_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AttendanceNewDeleteCommand" Method="sp_Payroll_AttendanceNewDeleteCommand">
    <Parameter Name="Original_Attendance_ID" Parameter="original_Attendance_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Payroll_AttendanceNewSelectCommand" Method="sp_Payroll_AttendanceNewSelectCommand">
    <ElementType Name="sp_Payroll_AttendanceNewSelectCommandResult">
      <Column Name="Attendance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="In_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Out_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AttendanceNewInsertCommand" Method="sp_Payroll_AttendanceNewInsertCommand">
    <Parameter Name="In_Time" Parameter="in_Time" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="Out_Time" Parameter="out_Time" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="Reg_Date" Parameter="reg_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_AttendanceNewInsertCommandResult">
      <Column Name="Attendance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="In_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Out_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_AttendanceNewUpdateCommand" Method="sp_Payroll_AttendanceNewUpdateCommand">
    <Parameter Name="In_Time" Parameter="in_Time" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="Out_Time" Parameter="out_Time" Type="System.DateTime" DbType="SmallDateTime" />
    <Parameter Name="Reg_Date" Parameter="reg_Date" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_Attendance_ID" Parameter="original_Attendance_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Attendance_ID" Parameter="attendance_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_AttendanceNewUpdateCommandResult">
      <Column Name="Attendance_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="In_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Out_Time" Type="System.DateTime" DbType="SmallDateTime" CanBeNull="true" />
      <Column Name="Reg_Date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_OurCompanyDetailNewDeleteCommand" Method="sp_Payroll_OurCompanyDetailNewDeleteCommand">
    <Parameter Name="Original_Cur_ID" Parameter="original_Cur_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Payroll_OurCompanyDetailNewInsertCommand" Method="sp_Payroll_OurCompanyDetailNewInsertCommand">
    <Parameter Name="Cur_JoiningDate" Parameter="cur_JoiningDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Cur_SalaryOnJoining" Parameter="cur_SalaryOnJoining" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Cur_Relieving" Parameter="cur_Relieving" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Cur_Status" Parameter="cur_Status" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Cur_CertificateProvided" Parameter="cur_CertificateProvided" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Cur_SalaryNow" Parameter="cur_SalaryNow" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Cur_Insentive" Parameter="cur_Insentive" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Cur_Designation" Parameter="cur_Designation" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Cur_ResumeUrl" Parameter="cur_ResumeUrl" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Cur_Command" Parameter="cur_Command" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_OurCompanyDetailNewInsertCommandResult">
      <Column Name="Cur_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cur_JoiningDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_SalaryOnJoining" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Relieving" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Cur_CertificateProvided" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_SalaryNow" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Designation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_ResumeUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_Command" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_OurCompanyDetailNewSelectCommand" Method="sp_Payroll_OurCompanyDetailNewSelectCommand">
    <ElementType Name="sp_Payroll_OurCompanyDetailNewSelectCommandResult">
      <Column Name="Cur_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cur_JoiningDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_SalaryOnJoining" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Relieving" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Cur_CertificateProvided" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_SalaryNow" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Designation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_ResumeUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_Command" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_OurCompanyDetailNewUpdateCommand" Method="sp_Payroll_OurCompanyDetailNewUpdateCommand">
    <Parameter Name="Cur_JoiningDate" Parameter="cur_JoiningDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Cur_SalaryOnJoining" Parameter="cur_SalaryOnJoining" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Cur_Relieving" Parameter="cur_Relieving" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Cur_Status" Parameter="cur_Status" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Cur_CertificateProvided" Parameter="cur_CertificateProvided" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Cur_SalaryNow" Parameter="cur_SalaryNow" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Cur_Insentive" Parameter="cur_Insentive" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Cur_Designation" Parameter="cur_Designation" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Cur_ResumeUrl" Parameter="cur_ResumeUrl" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Cur_Command" Parameter="cur_Command" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_Cur_ID" Parameter="original_Cur_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Cur_ID" Parameter="cur_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_OurCompanyDetailNewUpdateCommandResult">
      <Column Name="Cur_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cur_JoiningDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_SalaryOnJoining" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Relieving" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Cur_Status" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Cur_CertificateProvided" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_SalaryNow" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Cur_Designation" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_ResumeUrl" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Cur_Command" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_SalaryDetailNewDeleteCommand" Method="sp_Payroll_SalaryDetailNewDeleteCommand">
    <Parameter Name="Original_Salary_ID" Parameter="original_Salary_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Payroll_SalaryDetailNewInsertCommand" Method="sp_Payroll_SalaryDetailNewInsertCommand">
    <Parameter Name="Pay" Parameter="pay" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="No_Days" Parameter="no_Days" Type="System.Double" DbType="Float" />
    <Parameter Name="Insentive" Parameter="insentive" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Extra_Benifits" Parameter="extra_Benifits" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Gross_Pay" Parameter="gross_Pay" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Basic" Parameter="basic" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="HRA" Parameter="hRA" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Total_Amount" Parameter="total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="NETT" Parameter="nETT" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="SalaryAdvanceBalance" Parameter="salaryAdvanceBalance" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="AdvanceDeduction" Parameter="advanceDeduction" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="PF" Parameter="pF" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="ESI" Parameter="eSI" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Deduction_Total" Parameter="deduction_Total" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="SalaryOfMonth" Parameter="salaryOfMonth" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_SalaryDetailNewInsertCommandResult">
      <Column Name="Salary_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="No_Days" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Extra_Benifits" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Gross_Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Basic" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HRA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NETT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryAdvanceBalance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AdvanceDeduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PF" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ESI" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Deduction_Total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryOfMonth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_SalaryDetailNewSelectCommand" Method="sp_Payroll_SalaryDetailNewSelectCommand">
    <ElementType Name="sp_Payroll_SalaryDetailNewSelectCommandResult">
      <Column Name="Salary_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="No_Days" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Extra_Benifits" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Gross_Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Basic" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HRA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NETT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryAdvanceBalance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AdvanceDeduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PF" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ESI" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Deduction_Total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryOfMonth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_SalaryDetailNewUpdateCommand" Method="sp_Payroll_SalaryDetailNewUpdateCommand">
    <Parameter Name="Pay" Parameter="pay" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="No_Days" Parameter="no_Days" Type="System.Double" DbType="Float" />
    <Parameter Name="Insentive" Parameter="insentive" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Extra_Benifits" Parameter="extra_Benifits" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Gross_Pay" Parameter="gross_Pay" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Basic" Parameter="basic" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="HRA" Parameter="hRA" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Total_Amount" Parameter="total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="NETT" Parameter="nETT" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="SalaryAdvanceBalance" Parameter="salaryAdvanceBalance" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="AdvanceDeduction" Parameter="advanceDeduction" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="PF" Parameter="pF" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="ESI" Parameter="eSI" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="Deduction_Total" Parameter="deduction_Total" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="SalaryOfMonth" Parameter="salaryOfMonth" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="fkEmployee_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_Salary_ID" Parameter="original_Salary_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Salary_ID" Parameter="salary_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_SalaryDetailNewUpdateCommandResult">
      <Column Name="Salary_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="No_Days" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Insentive" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Extra_Benifits" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Gross_Pay" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Basic" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="HRA" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Total_Amount" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NETT" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryAdvanceBalance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="AdvanceDeduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PF" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="ESI" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Deduction_Total" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SalaryOfMonth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fkEmployee_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_PersonalDetailNewDeleteCommand" Method="sp_Payroll_PersonalDetailNewDeleteCommand">
    <Parameter Name="Original_Employee_id" Parameter="original_Employee_id" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Payroll_PersonalDetailNewInsertCommand" Method="sp_Payroll_PersonalDetailNewInsertCommand">
    <Parameter Name="Employee_Code" Parameter="employee_Code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="First_Name" Parameter="first_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Last_Name" Parameter="last_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Father_Name" Parameter="father_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Sex" Parameter="sex" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Marital_Status" Parameter="marital_Status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Phone" Parameter="phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Permanent_Address" Parameter="permanent_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Present_Address" Parameter="present_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Photo_Url" Parameter="photo_Url" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ID_proof_Url" Parameter="iD_proof_Url" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Address_Proof_url" Parameter="address_Proof_url" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Total_Experience" Parameter="total_Experience" Type="System.String" DbType="NVarChar(50)" />
    <ElementType Name="sp_Payroll_PersonalDetailNewInsertCommandResult">
      <Column Name="Employee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Employee_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Permanent_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Present_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Photo_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_proof_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address_Proof_url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Experience" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_PersonalDetailNewSelectCommand" Method="sp_Payroll_PersonalDetailNewSelectCommand">
    <ElementType Name="sp_Payroll_PersonalDetailNewSelectCommandResult">
      <Column Name="Employee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Employee_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Permanent_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Present_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Photo_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_proof_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address_Proof_url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Experience" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_PersonalDetailNewUpdateCommand" Method="sp_Payroll_PersonalDetailNewUpdateCommand">
    <Parameter Name="Employee_Code" Parameter="employee_Code" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="First_Name" Parameter="first_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Last_Name" Parameter="last_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Father_Name" Parameter="father_Name" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="DOB" Parameter="dOB" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Sex" Parameter="sex" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Marital_Status" Parameter="marital_Status" Type="System.Int32" DbType="Int" />
    <Parameter Name="Phone" Parameter="phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Mobile" Parameter="mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Password" Parameter="password" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Permanent_Address" Parameter="permanent_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Present_Address" Parameter="present_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Photo_Url" Parameter="photo_Url" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="ID_proof_Url" Parameter="iD_proof_Url" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Address_Proof_url" Parameter="address_Proof_url" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Total_Experience" Parameter="total_Experience" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Original_Employee_id" Parameter="original_Employee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Employee_id" Parameter="employee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_PersonalDetailNewUpdateCommandResult">
      <Column Name="Employee_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Employee_Code" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="First_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Last_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Father_Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Sex" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Marital_Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Permanent_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Present_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Photo_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ID_proof_Url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address_Proof_url" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Total_Experience" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_Previous_CompanyDetailNewDeleteCommand" Method="sp_Payroll_Previous_CompanyDetailNewDeleteCommand">
    <Parameter Name="Original_Pre_ID" Parameter="original_Pre_ID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_Payroll_Previous_CompanyDetailNewInsertCommand" Method="sp_Payroll_Previous_CompanyDetailNewInsertCommand">
    <Parameter Name="Pre_Name" Parameter="pre_Name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Pre_Address" Parameter="pre_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Pre_ContactPerson" Parameter="pre_ContactPerson" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Pre_Mobile" Parameter="pre_Mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Pre_Phone" Parameter="pre_Phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Pre_Email" Parameter="pre_Email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Pre_Website" Parameter="pre_Website" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Pre_Salary" Parameter="pre_Salary" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="fkEmployee_id" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_Previous_CompanyDetailNewInsertCommandResult">
      <Column Name="Pre_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pre_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Pre_ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pre_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="fkEmployee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_Previous_CompanyDetailNewSelectCommand" Method="sp_Payroll_Previous_CompanyDetailNewSelectCommand">
    <ElementType Name="sp_Payroll_Previous_CompanyDetailNewSelectCommandResult">
      <Column Name="Pre_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pre_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Pre_ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pre_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="fkEmployee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Payroll_Previous_CompanyDetailNewUpdateCommand" Method="sp_Payroll_Previous_CompanyDetailNewUpdateCommand">
    <Parameter Name="Pre_Name" Parameter="pre_Name" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Pre_Address" Parameter="pre_Address" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="Pre_ContactPerson" Parameter="pre_ContactPerson" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Pre_Mobile" Parameter="pre_Mobile" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Pre_Phone" Parameter="pre_Phone" Type="System.Int64" DbType="BigInt" />
    <Parameter Name="Pre_Email" Parameter="pre_Email" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Pre_Website" Parameter="pre_Website" Type="System.String" DbType="NVarChar(100)" />
    <Parameter Name="Pre_Salary" Parameter="pre_Salary" Type="System.Decimal" DbType="Decimal(18,2)" />
    <Parameter Name="fkEmployee_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Original_Pre_ID" Parameter="original_Pre_ID" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pre_ID" Parameter="pre_ID" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_Payroll_Previous_CompanyDetailNewUpdateCommandResult">
      <Column Name="Pre_ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pre_Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Pre_ContactPerson" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pre_Mobile" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Phone" Type="System.Int64" DbType="BigInt" CanBeNull="true" />
      <Column Name="Pre_Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Website" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Pre_Salary" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="fkEmployee_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>