#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Biz_OutSource_To_India")]
	public partial class OnlineExamDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertOnlineCategory(OnlineCategory instance);
    partial void UpdateOnlineCategory(OnlineCategory instance);
    partial void DeleteOnlineCategory(OnlineCategory instance);
    partial void InsertOnlineOption(OnlineOption instance);
    partial void UpdateOnlineOption(OnlineOption instance);
    partial void DeleteOnlineOption(OnlineOption instance);
    partial void InsertOnlineRegistration(OnlineRegistration instance);
    partial void UpdateOnlineRegistration(OnlineRegistration instance);
    partial void DeleteOnlineRegistration(OnlineRegistration instance);
    partial void InsertOnlineResult(OnlineResult instance);
    partial void UpdateOnlineResult(OnlineResult instance);
    partial void DeleteOnlineResult(OnlineResult instance);
    partial void InsertOnlineResultMark(OnlineResultMark instance);
    partial void UpdateOnlineResultMark(OnlineResultMark instance);
    partial void DeleteOnlineResultMark(OnlineResultMark instance);
    partial void InsertOnlineQuestion(OnlineQuestion instance);
    partial void UpdateOnlineQuestion(OnlineQuestion instance);
    partial void DeleteOnlineQuestion(OnlineQuestion instance);
    #endregion
		
		public OnlineExamDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OnlineExamConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineExamDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineExamDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineExamDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnlineExamDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<OnlineCategory> OnlineCategories
		{
			get
			{
				return this.GetTable<OnlineCategory>();
			}
		}
		
		public System.Data.Linq.Table<OnlineOption> OnlineOptions
		{
			get
			{
				return this.GetTable<OnlineOption>();
			}
		}
		
		public System.Data.Linq.Table<OnlineRegistration> OnlineRegistrations
		{
			get
			{
				return this.GetTable<OnlineRegistration>();
			}
		}
		
		public System.Data.Linq.Table<OnlineResult> OnlineResults
		{
			get
			{
				return this.GetTable<OnlineResult>();
			}
		}
		
		public System.Data.Linq.Table<OnlineResultMark> OnlineResultMarks
		{
			get
			{
				return this.GetTable<OnlineResultMark>();
			}
		}
		
		public System.Data.Linq.Table<OnlineQuestion> OnlineQuestions
		{
			get
			{
				return this.GetTable<OnlineQuestion>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineCategoryNewDeleteCommand")]
		public int sp_OnlineCategoryNewDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_CategoryId", DbType="BigInt")] System.Nullable<long> original_CategoryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_CategoryId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineCategoryNewInsertCommand")]
		public ISingleResult<sp_OnlineCategoryNewInsertCommandResult> sp_OnlineCategoryNewInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="NVarChar(100)")] string category)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category);
			return ((ISingleResult<sp_OnlineCategoryNewInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineCategoryNewSelectCommand")]
		public ISingleResult<sp_OnlineCategoryNewSelectCommandResult> sp_OnlineCategoryNewSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_OnlineCategoryNewSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineCategoryNewUpdateCommand")]
		public ISingleResult<sp_OnlineCategoryNewUpdateCommandResult> sp_OnlineCategoryNewUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Category", DbType="NVarChar(100)")] string category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_CategoryId", DbType="BigInt")] System.Nullable<long> original_CategoryId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="BigInt")] System.Nullable<long> categoryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), category, original_CategoryId, categoryId);
			return ((ISingleResult<sp_OnlineCategoryNewUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineOptionsNewDeleteCommand")]
		public int sp_OnlineOptionsNewDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_OptionId", DbType="BigInt")] System.Nullable<long> original_OptionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_OptionId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineOptionsNewInsertCommand")]
		public ISingleResult<sp_OnlineOptionsNewInsertCommandResult> sp_OnlineOptionsNewInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionName", DbType="NVarChar(500)")] string optionName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionType", DbType="Int")] System.Nullable<int> optionType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_QuestionId", DbType="BigInt")] System.Nullable<long> fK_QuestionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), optionName, optionType, fK_QuestionId);
			return ((ISingleResult<sp_OnlineOptionsNewInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineOptionsNewSelectCommand")]
		public ISingleResult<sp_OnlineOptionsNewSelectCommandResult> sp_OnlineOptionsNewSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_OnlineOptionsNewSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineOptionsNewUpdateCommand")]
		public ISingleResult<sp_OnlineOptionsNewUpdateCommandResult> sp_OnlineOptionsNewUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionName", DbType="NVarChar(500)")] string optionName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionType", DbType="Int")] System.Nullable<int> optionType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_QuestionId", DbType="BigInt")] System.Nullable<long> fK_QuestionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_OptionId", DbType="BigInt")] System.Nullable<long> original_OptionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OptionId", DbType="BigInt")] System.Nullable<long> optionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), optionName, optionType, fK_QuestionId, original_OptionId, optionId);
			return ((ISingleResult<sp_OnlineOptionsNewUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineQuestionNewDeleteCommand")]
		public int sp_OnlineQuestionNewDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_QuestionId", DbType="BigInt")] System.Nullable<long> original_QuestionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_QuestionId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineQuestionNewSelectCommand")]
		public ISingleResult<sp_OnlineQuestionNewSelectCommandResult> sp_OnlineQuestionNewSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_OnlineQuestionNewSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineQuestionNewUpdateCommand")]
		public ISingleResult<sp_OnlineQuestionNewUpdateCommandResult> sp_OnlineQuestionNewUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(500)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Imageurl", DbType="NVarChar(200)")] string imageurl, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_Answer", DbType="BigInt")] System.Nullable<long> fK_Answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_Category", DbType="BigInt")] System.Nullable<long> fK_Category, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_QuestionId", DbType="BigInt")] System.Nullable<long> original_QuestionId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="QuestionId", DbType="BigInt")] System.Nullable<long> questionId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), question, imageurl, fK_Answer, fK_Category, original_QuestionId, questionId);
			return ((ISingleResult<sp_OnlineQuestionNewUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineRegistrationNewDeleteCommand")]
		public int sp_OnlineRegistrationNewDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_UserId", DbType="BigInt")] System.Nullable<long> original_UserId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_UserId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineRegistrationNewSelectCommand")]
		public ISingleResult<sp_OnlineRegistrationNewSelectCommandResult> sp_OnlineRegistrationNewSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_OnlineRegistrationNewSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineRegistrationNewUpdateCommand")]
		public ISingleResult<sp_OnlineRegistrationNewUpdateCommandResult> sp_OnlineRegistrationNewUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="BigInt")] System.Nullable<long> mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="DateTime")] System.Nullable<System.DateTime> date, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_UserId", DbType="BigInt")] System.Nullable<long> original_UserId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserId", DbType="BigInt")] System.Nullable<long> userId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, mobile, email, date, original_UserId, userId);
			return ((ISingleResult<sp_OnlineRegistrationNewUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineRegistrationNewInsertCommand")]
		public ISingleResult<sp_OnlineRegistrationNewInsertCommandResult> sp_OnlineRegistrationNewInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(100)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mobile", DbType="BigInt")] System.Nullable<long> mobile, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(100)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Date", DbType="DateTime")] System.Nullable<System.DateTime> date)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), name, mobile, email, date);
			return ((ISingleResult<sp_OnlineRegistrationNewInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultMarksNewDeleteCommand")]
		public int sp_OnlineResultMarksNewDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_MarkId", DbType="BigInt")] System.Nullable<long> original_MarkId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_MarkId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultMarksNewInsertCommand")]
		public ISingleResult<sp_OnlineResultMarksNewInsertCommandResult> sp_OnlineResultMarksNewInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mark", DbType="Int")] System.Nullable<int> mark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_MarkType", DbType="BigInt")] System.Nullable<long> fK_MarkType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_ResultId", DbType="BigInt")] System.Nullable<long> fK_ResultId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mark, fK_MarkType, fK_ResultId);
			return ((ISingleResult<sp_OnlineResultMarksNewInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultMarksNewSelectCommand")]
		public ISingleResult<sp_OnlineResultMarksNewSelectCommandResult> sp_OnlineResultMarksNewSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_OnlineResultMarksNewSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultMarksNewUpdateCommand")]
		public ISingleResult<sp_OnlineResultMarksNewUpdateCommandResult> sp_OnlineResultMarksNewUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mark", DbType="Int")] System.Nullable<int> mark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_MarkType", DbType="BigInt")] System.Nullable<long> fK_MarkType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_ResultId", DbType="BigInt")] System.Nullable<long> fK_ResultId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_MarkId", DbType="BigInt")] System.Nullable<long> original_MarkId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MarkId", DbType="BigInt")] System.Nullable<long> markId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mark, fK_MarkType, fK_ResultId, original_MarkId, markId);
			return ((ISingleResult<sp_OnlineResultMarksNewUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultNewDeleteCommand")]
		public int sp_OnlineResultNewDeleteCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_ResultId", DbType="BigInt")] System.Nullable<long> original_ResultId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), original_ResultId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultNewInsertCommand")]
		public ISingleResult<sp_OnlineResultNewInsertCommandResult> sp_OnlineResultNewInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_UserId", DbType="BigInt")] System.Nullable<long> fK_UserId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mark", DbType="Int")] System.Nullable<int> mark)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fK_UserId, mark);
			return ((ISingleResult<sp_OnlineResultNewInsertCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultNewSelectCommand")]
		public ISingleResult<sp_OnlineResultNewSelectCommandResult> sp_OnlineResultNewSelectCommand()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_OnlineResultNewSelectCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineResultNewUpdateCommand")]
		public ISingleResult<sp_OnlineResultNewUpdateCommandResult> sp_OnlineResultNewUpdateCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_UserId", DbType="BigInt")] System.Nullable<long> fK_UserId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Mark", DbType="Int")] System.Nullable<int> mark, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Original_ResultId", DbType="BigInt")] System.Nullable<long> original_ResultId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResultId", DbType="BigInt")] System.Nullable<long> resultId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fK_UserId, mark, original_ResultId, resultId);
			return ((ISingleResult<sp_OnlineResultNewUpdateCommandResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_OnlineQuestionNewInsertCommand")]
		public ISingleResult<sp_OnlineQuestionNewInsertCommandResult> sp_OnlineQuestionNewInsertCommand([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Question", DbType="NVarChar(500)")] string question, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string path, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_Answer", DbType="BigInt")] System.Nullable<long> fK_Answer, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_Category", DbType="BigInt")] System.Nullable<long> fK_Category)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), question, path, fK_Answer, fK_Category);
			return ((ISingleResult<sp_OnlineQuestionNewInsertCommandResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnlineCategory")]
	public partial class OnlineCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _CategoryId;
		
		private string _Category;
		
		private EntitySet<OnlineResultMark> _OnlineResultMarks;
		
		private EntitySet<OnlineQuestion> _OnlineQuestions;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCategoryIdChanging(long value);
    partial void OnCategoryIdChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    #endregion
		
		public OnlineCategory()
		{
			this._OnlineResultMarks = new EntitySet<OnlineResultMark>(new Action<OnlineResultMark>(this.attach_OnlineResultMarks), new Action<OnlineResultMark>(this.detach_OnlineResultMarks));
			this._OnlineQuestions = new EntitySet<OnlineQuestion>(new Action<OnlineQuestion>(this.attach_OnlineQuestions), new Action<OnlineQuestion>(this.detach_OnlineQuestions));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this.OnCategoryIdChanging(value);
					this.SendPropertyChanging();
					this._CategoryId = value;
					this.SendPropertyChanged("CategoryId");
					this.OnCategoryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineCategory_OnlineResultMark", Storage="_OnlineResultMarks", ThisKey="CategoryId", OtherKey="FK_MarkType")]
		public EntitySet<OnlineResultMark> OnlineResultMarks
		{
			get
			{
				return this._OnlineResultMarks;
			}
			set
			{
				this._OnlineResultMarks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineCategory_OnlineQuestion", Storage="_OnlineQuestions", ThisKey="CategoryId", OtherKey="FK_Category")]
		public EntitySet<OnlineQuestion> OnlineQuestions
		{
			get
			{
				return this._OnlineQuestions;
			}
			set
			{
				this._OnlineQuestions.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OnlineResultMarks(OnlineResultMark entity)
		{
			this.SendPropertyChanging();
			entity.OnlineCategory = this;
		}
		
		private void detach_OnlineResultMarks(OnlineResultMark entity)
		{
			this.SendPropertyChanging();
			entity.OnlineCategory = null;
		}
		
		private void attach_OnlineQuestions(OnlineQuestion entity)
		{
			this.SendPropertyChanging();
			entity.OnlineCategory = this;
		}
		
		private void detach_OnlineQuestions(OnlineQuestion entity)
		{
			this.SendPropertyChanging();
			entity.OnlineCategory = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnlineOptions")]
	public partial class OnlineOption : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OptionId;
		
		private string _OptionName;
		
		private System.Nullable<int> _OptionType;
		
		private System.Nullable<long> _FK_QuestionId;
		
		private EntityRef<OnlineQuestion> _OnlineQuestion;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOptionIdChanging(long value);
    partial void OnOptionIdChanged();
    partial void OnOptionNameChanging(string value);
    partial void OnOptionNameChanged();
    partial void OnOptionTypeChanging(System.Nullable<int> value);
    partial void OnOptionTypeChanged();
    partial void OnFK_QuestionIdChanging(System.Nullable<long> value);
    partial void OnFK_QuestionIdChanged();
    #endregion
		
		public OnlineOption()
		{
			this._OnlineQuestion = default(EntityRef<OnlineQuestion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this.OnOptionIdChanging(value);
					this.SendPropertyChanging();
					this._OptionId = value;
					this.SendPropertyChanged("OptionId");
					this.OnOptionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionName", DbType="NVarChar(500)")]
		public string OptionName
		{
			get
			{
				return this._OptionName;
			}
			set
			{
				if ((this._OptionName != value))
				{
					this.OnOptionNameChanging(value);
					this.SendPropertyChanging();
					this._OptionName = value;
					this.SendPropertyChanged("OptionName");
					this.OnOptionNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionType", DbType="Int")]
		public System.Nullable<int> OptionType
		{
			get
			{
				return this._OptionType;
			}
			set
			{
				if ((this._OptionType != value))
				{
					this.OnOptionTypeChanging(value);
					this.SendPropertyChanging();
					this._OptionType = value;
					this.SendPropertyChanged("OptionType");
					this.OnOptionTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_QuestionId", DbType="BigInt")]
		public System.Nullable<long> FK_QuestionId
		{
			get
			{
				return this._FK_QuestionId;
			}
			set
			{
				if ((this._FK_QuestionId != value))
				{
					if (this._OnlineQuestion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_QuestionIdChanging(value);
					this.SendPropertyChanging();
					this._FK_QuestionId = value;
					this.SendPropertyChanged("FK_QuestionId");
					this.OnFK_QuestionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineQuestion_OnlineOption", Storage="_OnlineQuestion", ThisKey="FK_QuestionId", OtherKey="QuestionId", IsForeignKey=true)]
		public OnlineQuestion OnlineQuestion
		{
			get
			{
				return this._OnlineQuestion.Entity;
			}
			set
			{
				OnlineQuestion previousValue = this._OnlineQuestion.Entity;
				if (((previousValue != value) 
							|| (this._OnlineQuestion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OnlineQuestion.Entity = null;
						previousValue.OnlineOptions.Remove(this);
					}
					this._OnlineQuestion.Entity = value;
					if ((value != null))
					{
						value.OnlineOptions.Add(this);
						this._FK_QuestionId = value.QuestionId;
					}
					else
					{
						this._FK_QuestionId = default(Nullable<long>);
					}
					this.SendPropertyChanged("OnlineQuestion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnlineRegistration")]
	public partial class OnlineRegistration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _UserId;
		
		private string _Name;
		
		private System.Nullable<long> _Mobile;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Date;
		
		private EntitySet<OnlineResult> _OnlineResults;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIdChanging(long value);
    partial void OnUserIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnMobileChanging(System.Nullable<long> value);
    partial void OnMobileChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDateChanged();
    #endregion
		
		public OnlineRegistration()
		{
			this._OnlineResults = new EntitySet<OnlineResult>(new Action<OnlineResult>(this.attach_OnlineResults), new Action<OnlineResult>(this.detach_OnlineResults));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this.OnUserIdChanging(value);
					this.SendPropertyChanging();
					this._UserId = value;
					this.SendPropertyChanged("UserId");
					this.OnUserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="BigInt")]
		public System.Nullable<long> Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this.OnMobileChanging(value);
					this.SendPropertyChanging();
					this._Mobile = value;
					this.SendPropertyChanged("Mobile");
					this.OnMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineRegistration_OnlineResult", Storage="_OnlineResults", ThisKey="UserId", OtherKey="FK_UserId")]
		public EntitySet<OnlineResult> OnlineResults
		{
			get
			{
				return this._OnlineResults;
			}
			set
			{
				this._OnlineResults.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OnlineResults(OnlineResult entity)
		{
			this.SendPropertyChanging();
			entity.OnlineRegistration = this;
		}
		
		private void detach_OnlineResults(OnlineResult entity)
		{
			this.SendPropertyChanging();
			entity.OnlineRegistration = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnlineResult")]
	public partial class OnlineResult : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ResultId;
		
		private System.Nullable<long> _FK_UserId;
		
		private System.Nullable<int> _Mark;
		
		private EntitySet<OnlineResultMark> _OnlineResultMarks;
		
		private EntityRef<OnlineRegistration> _OnlineRegistration;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnResultIdChanging(long value);
    partial void OnResultIdChanged();
    partial void OnFK_UserIdChanging(System.Nullable<long> value);
    partial void OnFK_UserIdChanged();
    partial void OnMarkChanging(System.Nullable<int> value);
    partial void OnMarkChanged();
    #endregion
		
		public OnlineResult()
		{
			this._OnlineResultMarks = new EntitySet<OnlineResultMark>(new Action<OnlineResultMark>(this.attach_OnlineResultMarks), new Action<OnlineResultMark>(this.detach_OnlineResultMarks));
			this._OnlineRegistration = default(EntityRef<OnlineRegistration>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ResultId
		{
			get
			{
				return this._ResultId;
			}
			set
			{
				if ((this._ResultId != value))
				{
					this.OnResultIdChanging(value);
					this.SendPropertyChanging();
					this._ResultId = value;
					this.SendPropertyChanged("ResultId");
					this.OnResultIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_UserId", DbType="BigInt")]
		public System.Nullable<long> FK_UserId
		{
			get
			{
				return this._FK_UserId;
			}
			set
			{
				if ((this._FK_UserId != value))
				{
					if (this._OnlineRegistration.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_UserIdChanging(value);
					this.SendPropertyChanging();
					this._FK_UserId = value;
					this.SendPropertyChanged("FK_UserId");
					this.OnFK_UserIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this.OnMarkChanging(value);
					this.SendPropertyChanging();
					this._Mark = value;
					this.SendPropertyChanged("Mark");
					this.OnMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineResult_OnlineResultMark", Storage="_OnlineResultMarks", ThisKey="ResultId", OtherKey="FK_ResultId")]
		public EntitySet<OnlineResultMark> OnlineResultMarks
		{
			get
			{
				return this._OnlineResultMarks;
			}
			set
			{
				this._OnlineResultMarks.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineRegistration_OnlineResult", Storage="_OnlineRegistration", ThisKey="FK_UserId", OtherKey="UserId", IsForeignKey=true)]
		public OnlineRegistration OnlineRegistration
		{
			get
			{
				return this._OnlineRegistration.Entity;
			}
			set
			{
				OnlineRegistration previousValue = this._OnlineRegistration.Entity;
				if (((previousValue != value) 
							|| (this._OnlineRegistration.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OnlineRegistration.Entity = null;
						previousValue.OnlineResults.Remove(this);
					}
					this._OnlineRegistration.Entity = value;
					if ((value != null))
					{
						value.OnlineResults.Add(this);
						this._FK_UserId = value.UserId;
					}
					else
					{
						this._FK_UserId = default(Nullable<long>);
					}
					this.SendPropertyChanged("OnlineRegistration");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OnlineResultMarks(OnlineResultMark entity)
		{
			this.SendPropertyChanging();
			entity.OnlineResult = this;
		}
		
		private void detach_OnlineResultMarks(OnlineResultMark entity)
		{
			this.SendPropertyChanging();
			entity.OnlineResult = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnlineResultMarks")]
	public partial class OnlineResultMark : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _MarkId;
		
		private System.Nullable<int> _Mark;
		
		private System.Nullable<long> _FK_MarkType;
		
		private System.Nullable<long> _FK_ResultId;
		
		private EntityRef<OnlineCategory> _OnlineCategory;
		
		private EntityRef<OnlineResult> _OnlineResult;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMarkIdChanging(long value);
    partial void OnMarkIdChanged();
    partial void OnMarkChanging(System.Nullable<int> value);
    partial void OnMarkChanged();
    partial void OnFK_MarkTypeChanging(System.Nullable<long> value);
    partial void OnFK_MarkTypeChanged();
    partial void OnFK_ResultIdChanging(System.Nullable<long> value);
    partial void OnFK_ResultIdChanged();
    #endregion
		
		public OnlineResultMark()
		{
			this._OnlineCategory = default(EntityRef<OnlineCategory>);
			this._OnlineResult = default(EntityRef<OnlineResult>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long MarkId
		{
			get
			{
				return this._MarkId;
			}
			set
			{
				if ((this._MarkId != value))
				{
					this.OnMarkIdChanging(value);
					this.SendPropertyChanging();
					this._MarkId = value;
					this.SendPropertyChanged("MarkId");
					this.OnMarkIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this.OnMarkChanging(value);
					this.SendPropertyChanging();
					this._Mark = value;
					this.SendPropertyChanged("Mark");
					this.OnMarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_MarkType", DbType="BigInt")]
		public System.Nullable<long> FK_MarkType
		{
			get
			{
				return this._FK_MarkType;
			}
			set
			{
				if ((this._FK_MarkType != value))
				{
					if (this._OnlineCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_MarkTypeChanging(value);
					this.SendPropertyChanging();
					this._FK_MarkType = value;
					this.SendPropertyChanged("FK_MarkType");
					this.OnFK_MarkTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_ResultId", DbType="BigInt")]
		public System.Nullable<long> FK_ResultId
		{
			get
			{
				return this._FK_ResultId;
			}
			set
			{
				if ((this._FK_ResultId != value))
				{
					if (this._OnlineResult.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_ResultIdChanging(value);
					this.SendPropertyChanging();
					this._FK_ResultId = value;
					this.SendPropertyChanged("FK_ResultId");
					this.OnFK_ResultIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineCategory_OnlineResultMark", Storage="_OnlineCategory", ThisKey="FK_MarkType", OtherKey="CategoryId", IsForeignKey=true)]
		public OnlineCategory OnlineCategory
		{
			get
			{
				return this._OnlineCategory.Entity;
			}
			set
			{
				OnlineCategory previousValue = this._OnlineCategory.Entity;
				if (((previousValue != value) 
							|| (this._OnlineCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OnlineCategory.Entity = null;
						previousValue.OnlineResultMarks.Remove(this);
					}
					this._OnlineCategory.Entity = value;
					if ((value != null))
					{
						value.OnlineResultMarks.Add(this);
						this._FK_MarkType = value.CategoryId;
					}
					else
					{
						this._FK_MarkType = default(Nullable<long>);
					}
					this.SendPropertyChanged("OnlineCategory");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineResult_OnlineResultMark", Storage="_OnlineResult", ThisKey="FK_ResultId", OtherKey="ResultId", IsForeignKey=true)]
		public OnlineResult OnlineResult
		{
			get
			{
				return this._OnlineResult.Entity;
			}
			set
			{
				OnlineResult previousValue = this._OnlineResult.Entity;
				if (((previousValue != value) 
							|| (this._OnlineResult.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OnlineResult.Entity = null;
						previousValue.OnlineResultMarks.Remove(this);
					}
					this._OnlineResult.Entity = value;
					if ((value != null))
					{
						value.OnlineResultMarks.Add(this);
						this._FK_ResultId = value.ResultId;
					}
					else
					{
						this._FK_ResultId = default(Nullable<long>);
					}
					this.SendPropertyChanged("OnlineResult");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OnlineQuestion")]
	public partial class OnlineQuestion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _QuestionId;
		
		private string _Question;
		
		private string _Imageurl;
		
		private System.Nullable<long> _FK_Answer;
		
		private System.Nullable<long> _FK_Category;
		
		private EntitySet<OnlineOption> _OnlineOptions;
		
		private EntityRef<OnlineCategory> _OnlineCategory;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQuestionIdChanging(long value);
    partial void OnQuestionIdChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnImageurlChanging(string value);
    partial void OnImageurlChanged();
    partial void OnFK_AnswerChanging(System.Nullable<long> value);
    partial void OnFK_AnswerChanged();
    partial void OnFK_CategoryChanging(System.Nullable<long> value);
    partial void OnFK_CategoryChanged();
    #endregion
		
		public OnlineQuestion()
		{
			this._OnlineOptions = new EntitySet<OnlineOption>(new Action<OnlineOption>(this.attach_OnlineOptions), new Action<OnlineOption>(this.detach_OnlineOptions));
			this._OnlineCategory = default(EntityRef<OnlineCategory>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this.OnQuestionIdChanging(value);
					this.SendPropertyChanging();
					this._QuestionId = value;
					this.SendPropertyChanged("QuestionId");
					this.OnQuestionIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(500)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imageurl", DbType="NVarChar(200)")]
		public string Imageurl
		{
			get
			{
				return this._Imageurl;
			}
			set
			{
				if ((this._Imageurl != value))
				{
					this.OnImageurlChanging(value);
					this.SendPropertyChanging();
					this._Imageurl = value;
					this.SendPropertyChanged("Imageurl");
					this.OnImageurlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Answer", DbType="BigInt")]
		public System.Nullable<long> FK_Answer
		{
			get
			{
				return this._FK_Answer;
			}
			set
			{
				if ((this._FK_Answer != value))
				{
					this.OnFK_AnswerChanging(value);
					this.SendPropertyChanging();
					this._FK_Answer = value;
					this.SendPropertyChanged("FK_Answer");
					this.OnFK_AnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Category", DbType="BigInt")]
		public System.Nullable<long> FK_Category
		{
			get
			{
				return this._FK_Category;
			}
			set
			{
				if ((this._FK_Category != value))
				{
					if (this._OnlineCategory.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnFK_CategoryChanging(value);
					this.SendPropertyChanging();
					this._FK_Category = value;
					this.SendPropertyChanged("FK_Category");
					this.OnFK_CategoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineQuestion_OnlineOption", Storage="_OnlineOptions", ThisKey="QuestionId", OtherKey="FK_QuestionId")]
		public EntitySet<OnlineOption> OnlineOptions
		{
			get
			{
				return this._OnlineOptions;
			}
			set
			{
				this._OnlineOptions.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="OnlineCategory_OnlineQuestion", Storage="_OnlineCategory", ThisKey="FK_Category", OtherKey="CategoryId", IsForeignKey=true)]
		public OnlineCategory OnlineCategory
		{
			get
			{
				return this._OnlineCategory.Entity;
			}
			set
			{
				OnlineCategory previousValue = this._OnlineCategory.Entity;
				if (((previousValue != value) 
							|| (this._OnlineCategory.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._OnlineCategory.Entity = null;
						previousValue.OnlineQuestions.Remove(this);
					}
					this._OnlineCategory.Entity = value;
					if ((value != null))
					{
						value.OnlineQuestions.Add(this);
						this._FK_Category = value.CategoryId;
					}
					else
					{
						this._FK_Category = default(Nullable<long>);
					}
					this.SendPropertyChanged("OnlineCategory");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OnlineOptions(OnlineOption entity)
		{
			this.SendPropertyChanging();
			entity.OnlineQuestion = this;
		}
		
		private void detach_OnlineOptions(OnlineOption entity)
		{
			this.SendPropertyChanging();
			entity.OnlineQuestion = null;
		}
	}
	
	public partial class sp_OnlineCategoryNewInsertCommandResult
	{
		
		private long _CategoryId;
		
		private string _Category;
		
		public sp_OnlineCategoryNewInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="BigInt NOT NULL")]
		public long CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineCategoryNewSelectCommandResult
	{
		
		private long _CategoryId;
		
		private string _Category;
		
		public sp_OnlineCategoryNewSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="BigInt NOT NULL")]
		public long CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineCategoryNewUpdateCommandResult
	{
		
		private long _CategoryId;
		
		private string _Category;
		
		public sp_OnlineCategoryNewUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryId", DbType="BigInt NOT NULL")]
		public long CategoryId
		{
			get
			{
				return this._CategoryId;
			}
			set
			{
				if ((this._CategoryId != value))
				{
					this._CategoryId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineOptionsNewInsertCommandResult
	{
		
		private long _OptionId;
		
		private string _OptionName;
		
		private System.Nullable<int> _OptionType;
		
		private System.Nullable<long> _FK_QuestionId;
		
		public sp_OnlineOptionsNewInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", DbType="BigInt NOT NULL")]
		public long OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this._OptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionName", DbType="NVarChar(500)")]
		public string OptionName
		{
			get
			{
				return this._OptionName;
			}
			set
			{
				if ((this._OptionName != value))
				{
					this._OptionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionType", DbType="Int")]
		public System.Nullable<int> OptionType
		{
			get
			{
				return this._OptionType;
			}
			set
			{
				if ((this._OptionType != value))
				{
					this._OptionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_QuestionId", DbType="BigInt")]
		public System.Nullable<long> FK_QuestionId
		{
			get
			{
				return this._FK_QuestionId;
			}
			set
			{
				if ((this._FK_QuestionId != value))
				{
					this._FK_QuestionId = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineOptionsNewSelectCommandResult
	{
		
		private long _OptionId;
		
		private string _OptionName;
		
		private System.Nullable<int> _OptionType;
		
		private System.Nullable<long> _FK_QuestionId;
		
		public sp_OnlineOptionsNewSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", DbType="BigInt NOT NULL")]
		public long OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this._OptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionName", DbType="NVarChar(500)")]
		public string OptionName
		{
			get
			{
				return this._OptionName;
			}
			set
			{
				if ((this._OptionName != value))
				{
					this._OptionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionType", DbType="Int")]
		public System.Nullable<int> OptionType
		{
			get
			{
				return this._OptionType;
			}
			set
			{
				if ((this._OptionType != value))
				{
					this._OptionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_QuestionId", DbType="BigInt")]
		public System.Nullable<long> FK_QuestionId
		{
			get
			{
				return this._FK_QuestionId;
			}
			set
			{
				if ((this._FK_QuestionId != value))
				{
					this._FK_QuestionId = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineOptionsNewUpdateCommandResult
	{
		
		private long _OptionId;
		
		private string _OptionName;
		
		private System.Nullable<int> _OptionType;
		
		private System.Nullable<long> _FK_QuestionId;
		
		public sp_OnlineOptionsNewUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionId", DbType="BigInt NOT NULL")]
		public long OptionId
		{
			get
			{
				return this._OptionId;
			}
			set
			{
				if ((this._OptionId != value))
				{
					this._OptionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionName", DbType="NVarChar(500)")]
		public string OptionName
		{
			get
			{
				return this._OptionName;
			}
			set
			{
				if ((this._OptionName != value))
				{
					this._OptionName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionType", DbType="Int")]
		public System.Nullable<int> OptionType
		{
			get
			{
				return this._OptionType;
			}
			set
			{
				if ((this._OptionType != value))
				{
					this._OptionType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_QuestionId", DbType="BigInt")]
		public System.Nullable<long> FK_QuestionId
		{
			get
			{
				return this._FK_QuestionId;
			}
			set
			{
				if ((this._FK_QuestionId != value))
				{
					this._FK_QuestionId = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineQuestionNewSelectCommandResult
	{
		
		private long _QuestionId;
		
		private string _Question;
		
		private string _Imageurl;
		
		private System.Nullable<long> _FK_Answer;
		
		private System.Nullable<long> _FK_Category;
		
		public sp_OnlineQuestionNewSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="BigInt NOT NULL")]
		public long QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(500)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imageurl", DbType="NVarChar(200)")]
		public string Imageurl
		{
			get
			{
				return this._Imageurl;
			}
			set
			{
				if ((this._Imageurl != value))
				{
					this._Imageurl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Answer", DbType="BigInt")]
		public System.Nullable<long> FK_Answer
		{
			get
			{
				return this._FK_Answer;
			}
			set
			{
				if ((this._FK_Answer != value))
				{
					this._FK_Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Category", DbType="BigInt")]
		public System.Nullable<long> FK_Category
		{
			get
			{
				return this._FK_Category;
			}
			set
			{
				if ((this._FK_Category != value))
				{
					this._FK_Category = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineQuestionNewUpdateCommandResult
	{
		
		private long _QuestionId;
		
		private string _Question;
		
		private string _Imageurl;
		
		private System.Nullable<long> _FK_Answer;
		
		private System.Nullable<long> _FK_Category;
		
		public sp_OnlineQuestionNewUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="BigInt NOT NULL")]
		public long QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(500)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imageurl", DbType="NVarChar(200)")]
		public string Imageurl
		{
			get
			{
				return this._Imageurl;
			}
			set
			{
				if ((this._Imageurl != value))
				{
					this._Imageurl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Answer", DbType="BigInt")]
		public System.Nullable<long> FK_Answer
		{
			get
			{
				return this._FK_Answer;
			}
			set
			{
				if ((this._FK_Answer != value))
				{
					this._FK_Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Category", DbType="BigInt")]
		public System.Nullable<long> FK_Category
		{
			get
			{
				return this._FK_Category;
			}
			set
			{
				if ((this._FK_Category != value))
				{
					this._FK_Category = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineRegistrationNewSelectCommandResult
	{
		
		private long _UserId;
		
		private string _Name;
		
		private System.Nullable<long> _Mobile;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Date;
		
		public sp_OnlineRegistrationNewSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="BigInt NOT NULL")]
		public long UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="BigInt")]
		public System.Nullable<long> Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineRegistrationNewUpdateCommandResult
	{
		
		private long _UserId;
		
		private string _Name;
		
		private System.Nullable<long> _Mobile;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Date;
		
		public sp_OnlineRegistrationNewUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="BigInt NOT NULL")]
		public long UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="BigInt")]
		public System.Nullable<long> Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineRegistrationNewInsertCommandResult
	{
		
		private long _UserId;
		
		private string _Name;
		
		private System.Nullable<long> _Mobile;
		
		private string _Email;
		
		private System.Nullable<System.DateTime> _Date;
		
		public sp_OnlineRegistrationNewInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserId", DbType="BigInt NOT NULL")]
		public long UserId
		{
			get
			{
				return this._UserId;
			}
			set
			{
				if ((this._UserId != value))
				{
					this._UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(100)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile", DbType="BigInt")]
		public System.Nullable<long> Mobile
		{
			get
			{
				return this._Mobile;
			}
			set
			{
				if ((this._Mobile != value))
				{
					this._Mobile = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime")]
		public System.Nullable<System.DateTime> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this._Date = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineResultMarksNewInsertCommandResult
	{
		
		private long _MarkId;
		
		private System.Nullable<int> _Mark;
		
		private System.Nullable<long> _FK_MarkType;
		
		private System.Nullable<long> _FK_ResultId;
		
		public sp_OnlineResultMarksNewInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkId", DbType="BigInt NOT NULL")]
		public long MarkId
		{
			get
			{
				return this._MarkId;
			}
			set
			{
				if ((this._MarkId != value))
				{
					this._MarkId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this._Mark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_MarkType", DbType="BigInt")]
		public System.Nullable<long> FK_MarkType
		{
			get
			{
				return this._FK_MarkType;
			}
			set
			{
				if ((this._FK_MarkType != value))
				{
					this._FK_MarkType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_ResultId", DbType="BigInt")]
		public System.Nullable<long> FK_ResultId
		{
			get
			{
				return this._FK_ResultId;
			}
			set
			{
				if ((this._FK_ResultId != value))
				{
					this._FK_ResultId = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineResultMarksNewSelectCommandResult
	{
		
		private long _MarkId;
		
		private System.Nullable<int> _Mark;
		
		private System.Nullable<long> _FK_MarkType;
		
		private System.Nullable<long> _FK_ResultId;
		
		public sp_OnlineResultMarksNewSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkId", DbType="BigInt NOT NULL")]
		public long MarkId
		{
			get
			{
				return this._MarkId;
			}
			set
			{
				if ((this._MarkId != value))
				{
					this._MarkId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this._Mark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_MarkType", DbType="BigInt")]
		public System.Nullable<long> FK_MarkType
		{
			get
			{
				return this._FK_MarkType;
			}
			set
			{
				if ((this._FK_MarkType != value))
				{
					this._FK_MarkType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_ResultId", DbType="BigInt")]
		public System.Nullable<long> FK_ResultId
		{
			get
			{
				return this._FK_ResultId;
			}
			set
			{
				if ((this._FK_ResultId != value))
				{
					this._FK_ResultId = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineResultMarksNewUpdateCommandResult
	{
		
		private long _MarkId;
		
		private System.Nullable<int> _Mark;
		
		private System.Nullable<long> _FK_MarkType;
		
		private System.Nullable<long> _FK_ResultId;
		
		public sp_OnlineResultMarksNewUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkId", DbType="BigInt NOT NULL")]
		public long MarkId
		{
			get
			{
				return this._MarkId;
			}
			set
			{
				if ((this._MarkId != value))
				{
					this._MarkId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this._Mark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_MarkType", DbType="BigInt")]
		public System.Nullable<long> FK_MarkType
		{
			get
			{
				return this._FK_MarkType;
			}
			set
			{
				if ((this._FK_MarkType != value))
				{
					this._FK_MarkType = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_ResultId", DbType="BigInt")]
		public System.Nullable<long> FK_ResultId
		{
			get
			{
				return this._FK_ResultId;
			}
			set
			{
				if ((this._FK_ResultId != value))
				{
					this._FK_ResultId = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineResultNewInsertCommandResult
	{
		
		private long _ResultId;
		
		private System.Nullable<long> _FK_UserId;
		
		private System.Nullable<int> _Mark;
		
		public sp_OnlineResultNewInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultId", DbType="BigInt NOT NULL")]
		public long ResultId
		{
			get
			{
				return this._ResultId;
			}
			set
			{
				if ((this._ResultId != value))
				{
					this._ResultId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_UserId", DbType="BigInt")]
		public System.Nullable<long> FK_UserId
		{
			get
			{
				return this._FK_UserId;
			}
			set
			{
				if ((this._FK_UserId != value))
				{
					this._FK_UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this._Mark = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineResultNewSelectCommandResult
	{
		
		private long _ResultId;
		
		private System.Nullable<long> _FK_UserId;
		
		private System.Nullable<int> _Mark;
		
		public sp_OnlineResultNewSelectCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultId", DbType="BigInt NOT NULL")]
		public long ResultId
		{
			get
			{
				return this._ResultId;
			}
			set
			{
				if ((this._ResultId != value))
				{
					this._ResultId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_UserId", DbType="BigInt")]
		public System.Nullable<long> FK_UserId
		{
			get
			{
				return this._FK_UserId;
			}
			set
			{
				if ((this._FK_UserId != value))
				{
					this._FK_UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this._Mark = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineResultNewUpdateCommandResult
	{
		
		private long _ResultId;
		
		private System.Nullable<long> _FK_UserId;
		
		private System.Nullable<int> _Mark;
		
		public sp_OnlineResultNewUpdateCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ResultId", DbType="BigInt NOT NULL")]
		public long ResultId
		{
			get
			{
				return this._ResultId;
			}
			set
			{
				if ((this._ResultId != value))
				{
					this._ResultId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_UserId", DbType="BigInt")]
		public System.Nullable<long> FK_UserId
		{
			get
			{
				return this._FK_UserId;
			}
			set
			{
				if ((this._FK_UserId != value))
				{
					this._FK_UserId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this._Mark = value;
				}
			}
		}
	}
	
	public partial class sp_OnlineQuestionNewInsertCommandResult
	{
		
		private long _QuestionId;
		
		private string _Question;
		
		private string _Imageurl;
		
		private System.Nullable<long> _FK_Answer;
		
		private System.Nullable<long> _FK_Category;
		
		public sp_OnlineQuestionNewInsertCommandResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QuestionId", DbType="BigInt NOT NULL")]
		public long QuestionId
		{
			get
			{
				return this._QuestionId;
			}
			set
			{
				if ((this._QuestionId != value))
				{
					this._QuestionId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(500)")]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this._Question = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imageurl", DbType="NVarChar(200)")]
		public string Imageurl
		{
			get
			{
				return this._Imageurl;
			}
			set
			{
				if ((this._Imageurl != value))
				{
					this._Imageurl = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Answer", DbType="BigInt")]
		public System.Nullable<long> FK_Answer
		{
			get
			{
				return this._FK_Answer;
			}
			set
			{
				if ((this._FK_Answer != value))
				{
					this._FK_Answer = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_Category", DbType="BigInt")]
		public System.Nullable<long> FK_Category
		{
			get
			{
				return this._FK_Category;
			}
			set
			{
				if ((this._FK_Category != value))
				{
					this._FK_Category = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
