






<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - June - 2012 ::</title><style type="text/css">
<!--
.style10 {
	border-collapse: collapse;
}
.style13 {
	font-family: Verdana;
	font-size: xx-small;
	margin: 10px;
}
.style14 {
	font-size: 9pt;
}
.style15 {
	font-family: Verdana;
	font-size: xx-small;
	margin: 10px;
	text-align: justify;
}
.style28 {
	font-family: Verdana;
	font-size: xx-small;
}
.style27 {
	font-family: Verdana;
	font-size: medium;
	color: #C00000;
}
-->
</style>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" cellpadding="0" style="width: 780px;" bordercolor="#111111" class="style10" align="center">
  <tr>
    <td width="100%" style="height: 19px">
<? include("../../../inc/top1.php"); ?>  
<? include("../../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="100%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#EFEFE9" colspan="3" align=center height="10">
            <div align="left">
				<table border="0" style="border-collapse: collapse" width="175" cellpadding="0">
					<tr>
						<td width="28" bgcolor="#FF0000" height="30" style="border-left-style: solid; border-left-width: 1px; border-right-width: 1px; border-top-width: 1px; border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#000000">
						&nbsp;</td>
						
                  <td valign="bottom" style="border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#FF0000" width="131"> 
                    <p align="left" style="margin-left: 5px"> 
					<span class="style28"><strong><a name="top">ECONOMY</a></strong></span></td>
					</tr>
				</table>
			</div>
			</td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">

<table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse: collapse" bordercolor="#111111">
	<tr>
						<td>
						&nbsp;</td>
					</tr>
	<tr>
						<td valign="top">
						<p align="justify" style="margin: 3px 10px">
						<strong><span class="style27">Sustainable utilities</span><span class="style14"><br>
						<br>
						<br>
						</span></strong><b><font face="Verdana" size="1">
						<img border="0" src="images/economy-june-12-1.jpg" width="150" height="186" align="right" hspace="8" vspace="3">The 
						Sultanate is now witnessing huge changes in its water 
						and electricity sectors, creating new opportunities for 
						investment and infrastructure in the process <br>
						<br>
						By Oliver Cornock</font></b><br>
						&nbsp;<p align="justify" class="style13">
						The two main challenges facing the Middle East as a 
						region concern resources. Most debated, discussed and 
						dissected is economic dependency on oil and how the Gulf 
						will diversify for the days when crude supplies run low. 
						The second, perhaps even more fundamental, concerns 
						water and power supply. Just as towering cities such as 
						Doha and Abu Dhabi owe their existence to the huge 
						revenues generated by energy, the growing populations of 
						the Gulf cannot be sustained without adequate water and 
						electricity. Furthermore, the solutions must themselves 
						be sustainable.<br>
						<br>
						Oman is a good example of how this second regional 
						challenge of provision is being met head on. The 
						Sultanate is now witnessing huge changes in its water 
						and electricity sectors, creating new opportunities for 
						investment and infrastructure in the process.<br>
						<br>
						This is largely due to demand driving the need for 
						increased access to – and supply of – water, as well as 
						power generation. Over the next five years to 2017, 
						domestic-sector demand for desalinated water in Oman is 
						set to rise from 163m cu metres to 278m cu metres – a 70 
						per cent rise – according to estimates from the Oman 
						Power and Water Procurement Company (OPWP). In addition, 
						the OPWP expects electricity demand to grow from 16.9 
						TWh to 30.3 TWh in 2017. One of the reasons for this is 
						Oman’s rising population, which World Bank statistics 
						show has grown by around one million in the past 20 
						years. <br>
						<br>
						In fact, the Sultanate now represents the 
						fastest-growing power and water sectors in the Middle 
						East, with demand for utilities set to grow at an 
						average yearly rate of 9 per cent until 2017, according 
						to the OPWP’s December 2010 report. <br>
						<br>
						To cater for this, a range of major developments are in 
						the pipeline. In mid-February, it was announced that the 
						Sultanate will make sector investments to the tune of 
						$2.9bn, spread across 13 new power, water and energy 
						projects, to begin construction in 2012. Although 
						specific details were not available at the time of 
						writing, it was reported that the focus of these 
						projects will be on increasing desalinated water supply 
						and improving network efficiency. <br>
						The government is looking to the private sector to take 
						on the majority of its utilities projects. In late 
						October 2011, for example, engineering and contracting 
						company Galfar was awarded a water pipeline project 
						worth $36.4mn by the Public Authority for Electricity 
						and Water (PAEW). On completion – estimated to be a year 
						and a half away – the pipeline will transport water from 
						Wadi Adai to Amerat.<br>
						<br>
						Although Oman benefits from slightly higher rainfall in 
						comparison to other GCC states, it is still a desert 
						country, and drinking water is never in abundance. 
						However, early March 2012 saw the awarding of a contract 
						to develop an important new water desalination facility 
						move one step closer, with the short-listing of seven 
						international firms for the bid. <br>
						<br>
						The plant, to be built in Ghubrah in the Muscat 
						governorate, will cost around $400mn and will process 
						some 42 million gallons of desalinated water per day 
						when completed in 2014, according to estimates. Two 
						other private sector-led “independent water projects” 
						are planned for Qurayat and Al Suwaiq.<br>
						<br>
						These projects will be high-efficiency reverse osmosis 
						desalination plants, which will draw electricity from 
						the main grid, as opposed to being co-located with power 
						generation capacity. In line with the OPWP’s 
						environmental strategy and seven-year planning process, 
						old facilities are to be decommissioned by 2017. <br>
						<br>
						Furthermore, the treatment of wastewater for reuse is a 
						central part of Oman’s irrigation strategy, called the 
						“Muscat Wastewater Master Plan”, which is aimed at 
						reducing pressure on groundwater resources within the 
						Muscat governorate. By reusing treated wastewater for 
						agriculture and landscaping, the Sultanate will help 
						reduce the water deficit, which has been estimated at 
						more than 300m cu metres of water each year. <br>
						<br>
						Two projects, with a combined value of over $1bn, were 
						launched in 2008; in A’Seeb and in Al Ansab. These are 
						being overseen by Omani wastewater service company Haya 
						Water. A’Seeb has now entered its second phase of 
						development, and will reach full operating capacity by 
						2017, although the facility is already partially 
						operational. <br>
						<br>
						Al Ansab, on the other hand, opened in early 2011, and 
						is the world’s largest submerged membrane bio-reactor 
						system with a capacity to handle up to 74,000 cu metres. 
						Taken together, these two projects will serve 80 per 
						cent of the Muscat population by 2014 and about 90 per 
						cent by 2017, delivered across the Muscat area by more 
						than 280km of pipeline that will replace the inefficient 
						septic tank system currently used by most properties in 
						the governorate. By end-2011 it was estimated that 20 
						per cent of properties within the Muscat governorate had 
						been connected to the new system.<br>
						<br>
						Despite some criticism that Oman has been slow to 
						develop alternative means of power generation, 
						renewables are increasingly being looked to as the 
						future source of Oman’s energy provision. According to 
						the first renewable energy country attractiveness 
						indices of 2012, published by professional service firm 
						Ernst and Young, Oman’s solar resources rank among the 
						highest in the world, and have the potential to supply a 
						sizeable share of Oman’s current energy demand. Indeed, 
						the government aims to produce 10 per cent of its energy 
						needs from renewable energy resources by 2020.<br>
						<br>
						This potential looks set to offer huge opportunities for 
						not only private-sector – but also international – 
						involvement. In January it was announced that German 
						private investment firm Middle East Best Select (MEBS), 
						and Terra Nex Financial Engineering of Switzerland, are 
						looking to fund a project valued at over $2bn to build a 
						400-megawatt solar panel facility in Oman, which could 
						be utilised by power stations. A further $600mn of 
						project investment is being provided by direct equity 
						capital, as well as loans from European financiers, 
						mostly from Germany. MEBS and Terra Nex are looking to 
						secure a quantity of the generated power for export. <br>
						<br>
						Going forward, the issue of developing an expanded and 
						sustainable water and power sector is likely to gain 
						increasing prominence on the Omani agenda. In May, the 
						PAEW will host the Second Annual Oman Power and Water 
						Summit in Muscat, where high-profile infrastructure and 
						investment opportunities will be presented, as well as 
						the latest sector innovations and strategies. 
						Specifically, this will represent a key opportunity for 
						foreign companies to share knowledge and become involved 
						in upcoming projects in Omani utilities. <br>
						<br>
						By taking a proactive approach and finding solutions to 
						an environmental challenge, the Sultanate is ensuring 
						its long-term economic progress. Such action now will 
						not only guarantee environmental stability, but is also 
						set to be highly lucrative for Oman in the future.</td>
					</tr>
	<tr>
		        <td width="100%" valign="top"> 

                    <hr color="#CC3333">
                  <p align="right" style="margin: 3px 10px">
					<font face="Verdana" size="1">
                <a href="#top">Top^</a></font></td>
		</tr>
	<tr>
		        <td width="100%" valign="top"> 

                    &nbsp;</td>
		</tr>
	</table>

            </td>
            <td  valign=top bgcolor=white><?include("../../../inc/current_issue_menu.php");?>&nbsp;</td>
          </tr>
          
        </table>
	</tr>
  <tr>
    <td width="100%" height="15" valign="middle">
              <? include("../../../inc/menu1.htm");?>
        <? include("../../../inc/bottom.htm");?>
</table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
</body>
</html>