<html>

<head>
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<title>New Page 1</title>
</head>

<body>

<p> 
            <a href="http://www.bankmuscat.com"  target="_blank">
<img width="468" height="60" border="0" src="http://www.oeronline.com/images/banner_bk.gif" ></a></p>

</body>

</html>