SELECT * FROM TB_CATALOG
	SELECT * FROM TB_CATALOG_FAMILY
	SELECT * FROM TB_CATALOG_ATTRIBUTES
	SELECT * FROM TB_CATALOG_PRODUCT
	SELECT * FROM TB_CATALOG_SECTIONS
	SELECT * FROM TB_CATALOG_USER
SELECT * FROM TB_CATEGORY
	SELECT * FROM TB_CATALOG_SECTIONS
	SELECT * FROM TB_PRODUCT
	SELECT * FROM TB_FAMILY
	SELECT * FROM TB_CATALOG_FAMILY
SELECT * FROM TB_FAMILY
	SELECT * FROM TB_SUBFAMILY
	SELECT * FROM TB_PROD_FAMILY
	SELECT * FROM TB_FAMILY_SPECS
SELECT * FROM TB_PRODUCT
	SELECT * FROM TB_PROD_FAMILY
	SELECT * FROM TB_CATALOG_PRODUCT
	SELECT * FROM TB_PROD_SPECS
	SELECT * FROM TB_PRODUCT_KIT
SELECT * FROM TB_ATTRIBUTE
Select * From 
TB_PROD_FAMILY T,
TB_CATALOG_FAMILY F, 
TB_FAMILY F1, 
TB_CATALOG c where 
F.FAMILY_ID=F1.FAMILY_ID AND 
T.FAMILY_ID=F.FAMILY_ID AND 
F.CATALOG_ID=c.CATALOG_ID AND  
F.CATEGORY_ID='HC107' AND 
F.CATALOG_ID='1'  AND 
PARENT_FAMILY_ID >0 

Select * From 
TB_PROD_FAMILY T,
TB_CATALOG_FAMILY F,
TB_FAMILY F1,
TB_CATALOG c  where 
F.FAMILY_ID=F1.FAMILY_ID  AND  
T.FAMILY_ID=F.FAMILY_ID AND 
F.CATALOG_ID=c.CATALOG_ID AND 
F.CATEGORY_ID='HC107' and 
F.CATALOG_ID='1' and 
PARENT_FAMILY_ID = 0

Select * From 
TB_CATALOG_FAMILY F,
TB_FAMILY F1,
TB_CATALOG c  where 
F.FAMILY_ID=F1.FAMILY_ID AND 
F.CATALOG_ID=c.CATALOG_ID AND 
F.CATEGORY_ID='HC107' and 
F.CATALOG_ID='1' and 
PARENT_FAMILY_ID = 0 EXCEPT Select * From 
TB_PROD_FAMILY T,
TB_CATALOG_FAMILY F,
TB_FAMILY F1,
TB_CATALOG c where 
F.FAMILY_ID=F1.FAMILY_ID  AND  
T.FAMILY_ID=F.FAMILY_ID AND 
F.CATALOG_ID=c.CATALOG_ID AND 
F.CATEGORY_ID='HC107' and 
F.CATALOG_ID='1' and 
PARENT_FAMILY_ID >0

