DECLARE @QUERY VARCHAR(MAX);
DECLARE @SESS_ID VARCHAR(MAX)='TEST';
DECLARE @MAXHIERARCHY INT;
SET @MAXHIERARCHY =(SELECT MAX(HIERARCHY_LEVEL) FROM Category_Function_top('1','HC107'))
DECLARE @CATEGORY_ID nvarchar(100)
DECLARE @CATEGORY_NAME NVARCHAR(100)
DECLARE @HIERARCHY_LEVEL INT
DECLARE @UPDAT CURSOR 
SET @UPDAT = CURSOR FOR
SELECT CATEGORY_ID,CATEGORY_NAME,HIERARCHY_LEVEL from Category_Function_top('1','HC107')
OPEN @UPDAT
FETCH NEXT
FROM @UPDAT INTO @CATEGORY_ID,@CATEGORY_NAME,@HIERARCHY_LEVEL
 WHILE @@FETCH_STATUS=0
  BEGIN
  EXEC @MAXHIERARCHY
 IF(@MAXHIERARCHY=4)
   BEGIN 
	IF @HIERARCHY_LEVEL=0
		 SET @QUERY ='update ' +@SESS_ID+' SET SUBCATID_L4='+''''+@CATEGORY_ID+''''+' ,SUBCATNAME_L4='+''''+@CATEGORY_NAME+''''
		 EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update ' + @SESS_ID+' SET SUBCATID_L3='+''''+@CATEGORY_ID+''''+' ,SUBCATNAME_L3='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=2
		SET @QUERY ='update ' +@SESS_ID+' SET SUBCATID_L2='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L2='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY) 
	IF @HIERARCHY_LEVEL=3
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY) 
	IF @HIERARCHY_LEVEL=4
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY) 
  END
 IF(@MAXHIERARCHY=3)
   BEGIN
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L3='+''''+@CATEGORY_ID+''''+ ',SUBCATNAME_L3='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L2='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L2='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=2
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=3
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	END
 IF(@MAXHIERARCHY=2)		
	BEGIN
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L2='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L2='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update ' +@SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=2
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	END
 IF(@MAXHIERARCHY=1)
	BEGIN	
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET SUBCATID_L1='+''''+@CATEGORY_ID+''''+',SUBCATNAME_L1='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	IF @HIERARCHY_LEVEL=1
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	END	
 IF(@MAXHIERARCHY=0)	
	BEGIN 
	IF @HIERARCHY_LEVEL=0
		SET @QUERY ='update '+ @SESS_ID+' SET CATEGORY_ID='+''''+@CATEGORY_ID+''''+',CATEGORY_NAME='+''''+@CATEGORY_NAME+''''
		EXEC(@QUERY)
	 END		
FETCH NEXT 
FROM @UPDAT INTO  @CATEGORY_ID,@CATEGORY_NAME,@HIERARCHY_LEVEL
   END
CLOSE @UPDAT
DEALLOCATE @UPDAT

GO


UPDATE TEST SET  FAMILY_NAME = TF.FAMILY_NAME 
FROM TB_FAMILY TF WHERE TF.FAMILY_ID=TEST.FAMILY_ID

GO

