WITH TEST AS
(
Select F.CATALOG_ID,  c.CATALOG_NAME, '' CATEGORY_ID, '' CATEGORY_NAME, '' SUBCATID_L1, '' SUBCATNAME_L1,  '' SUBCATID_L2,  '' SUBCATNAME_L2, '' SUBCATID_L3, '' SUBCATNAME_L3, '' SUBCATID_L4, '' SUBCATNAME_L4, F1.PARENT_FAMILY_ID FAMILY_ID, ''FAMILY_NAME,  F.FAMILY_ID SUBFAMILY_ID,  F1.FAMILY_NAME SUBFAMILY_NAME,  T.PRODUCT_ID PRODUCT_ID  From
TB_PROD_FAMILY T,
TB_CATALOG_FAMILY F,
TB_FAMILY F1,
TB_CATALOG c  where 
F.FAMILY_ID=F1.FAMILY_ID  AND  
T.FAMILY_ID=F.FAMILY_ID AND 
F.CATALOG_ID=c.CATALOG_ID AND 
F.CATEGORY_ID='HC107' and 
F.CATALOG_ID='1' and 
PARENT_FAMILY_ID = 0
)


SELECT * FROM TEST