<?	session_start();?>
<?	session_register("id");
	if(!$HTTP_SESSION_VARS["id"]=="")
	{?>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - March - 2005 ::</title>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top1.php"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="5" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#FFFCE8" colspan="3" align=center><b>



<? if(!$HTTP_SESSION_VARS["id"]==""){echo "<font face=Verdana size=2 color=#000000>Welcome&nbsp;&nbsp;</font><font face=Verdana size=2 color=red><i>".$HTTP_SESSION_VARS["id"]."!</i></font>
            ";}else{echo$HTTP_SESSION_VARS["mes"];$HTTP_SESSION_VARS["mes"]="";}?>
              </b></td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF">

<p align="justify"><font face="Verdana" size="4" color="#FF0000">A split in 
time…<br>
</font><font face="Verdana" size="1"><br>
<b>Khalid Al-Yahmadi explains how stock splits can be employed to enhance 
liquidity in the stock market and thus attract more capital</b><br>
<br>
<img border="0" src="im10.jpg" align="left" hspace="5" width="110" height="129">As 
an investment and brokerage services company, one of our goals is to promote the 
local stock market in both the regional as well as international arenas. Many 
regional investors are keen to invest in the Muscat Securities Market (MSM) for 
that it is one of the most regulated and organised markets in the Middle East in 
addition to the political stability and the relaxed investment laws of the 
Sultanate. <br>
<br>
However, liquidity—one of the most important ingredients for an efficient and 
active stock market—is conspicuous by its absence on the country’s bourse. Many 
investors complain about the shallow liquidity of the local stock market 
compared to most other regional markets. In this article, I will try and explain 
how stock splits can enhance liquidity in the stock market and, hence, attract 
more foreign as well as local capital.<br>
<br>
As an investment manager, one of my duties is to advise clients on how to 
achieve a better return on their investment. Emaar Properties was one of the 
companies that attracted my attention towards the end of the second quarter of 
last year. However, a price of AED50 (RO5.260) was a constraint for some of my 
individual clients. Luckily, the company put into place a 10-for-1 stock split 
and the AED60 stock began trading at AED6. A number of my clients who were 
interested in the stock got in and, as of year-end 2004, the stock was trading 
at AED15, a return of 150 per cent.<br>
<br>
<b>So what do we mean by stock split and how does it work?</b><br>
Stock splits remain one of the most popular and least understood phenomena in 
equity markets. In theory, a stock split is merely an accounting change, which 
leaves investors no better or worse off than they were before the split. A stock 
split simply increases the amount of shares that exist, but does not change the 
value of an investor’s holdings or the market value of the company. For 
instance, one share worth RO10 becomes two shares worth RO5 each in a 2-for-1 
stock split. Splits can occur in any combination: 2-for-1, 3-for-2, 5-for-3, 
etc. <br>
<br>
Because stock splits have no impact on the fundamentals of a company, the 
interest generated by stock splits is generally considered strictly 
psychological. Yet, stock splits are relatively common occurrences in many 
regional and international stock markets. This implies that there must be some 
benefit, either real or perceived, that results from a firm splitting its stock.
<br>
<br>
It remains a puzzle why companies ever split their shares. Several hypotheses in 
academia have been proposed to address the question of why firms split their 
stock. The two most accepted hypotheses are the Signalling Hypothesis and the 
Liquidity Hypothesis. The signalling hypothesis states that due to the 
information asymmetry between managers and shareholders, managers split their 
stock to signal good information to the public. The traditional wisdom is that 
stock splits are “good information” – that companies split their stocks when 
they are confident that earnings momentum will continue to push their stock’s 
price upward. The positive stock price reaction accompanying the announcement of 
a split gives credence to this optimistic view.<br>
<br>
The liquidity hypothesis states that managers split their firm’s stock to make 
the stock more liquid. This hypothesis argues that firms prefer to keep their 
stock price within a particular (lower) price range. Survey evidence indicates 
that managers split their stock to get the stock’s price into some optimal 
trading range. By splitting the stock and lowering its price, more investors 
will be able to own it and liquidity should increase.<br>
<br>
While empirical evidence regarding the signalling hypothesis is mixed, there is 
more evidence in favour of this hypothesis than against it. Lakonishok and Lev 
(1987) find that firms that split have better-than-average earnings growth 
following the split. McNichols and Dravid (1990) find that the difference 
between actual and forecasted earnings following a split tends to be directly 
related to the size of the split factor: the higher the split factor, the better 
the earnings. Ikenberry, Rankine and Stice (1996) find that the post-split stock 
returns for firms that split their stock are higher than those of a controlled 
sample of firms that do not split their stock.<br>
<br>
As discussed above, the second hypothesis regarding the motive for stock splits 
is liquidity. By making the share price lower, more individuals can afford to 
purchase the stock and liquidity should improve. <br>
<br>
A survey conducted in the US supported this motive. Sixty-five per cent managers 
at firms that have split their stock stated that they did so to attract small 
investors while 32 per cent stated that they split their stock to increase the 
liquidity of trading. More support for the liquidity effect is found in a study 
conducted by Muscarella and Vetsuypens (1996) and Schultz (2000), who find that 
the frequency and volume of small trades increase following a stock split.<br>
<br>
Authorities at MSM and Capital Market Authority should, therefore, allow stock 
splits to enhance liquidity at the market. However, par value for stocks should 
be set at 100 baisa per share as a first step towards allowing stock splits. 
Trading activities for companies like Oman Refreshment Company, Renaissance 
Services, Port Services and Al Jazeera Tube Millis have declined as their stock 
prices soared. They have become too expensive to purchase for individual 
investors, who account for most of the daily trading activity in terms of number 
of transactions. <br>
<br>
The profitability of these companies has been growing rapidly and so have been 
their prices. By not allowing stock splits, we are depriving most of our 
individual investors from enjoying the higher returns expected by holding those 
stocks and alike as well as keeping those shares from reaching their full price 
potential as demand subsides at higher prices.<br>
By the same token, we can look at the primary market – the market where the 
security is offered to the pubic for the first time. Take as an example Omantel. 
The market is expecting the IPO to be priced anywhere between RO10 to RO14 per 
share. This is normally considered very expensive for the average investors who 
account for majority of investments at MSM. However, if the par value is set at 
100 baisa, the shares will then be offered at a more acceptable range of 
RO1.000-1.400, which in turn will stimulate the stock liquidity in the secondary 
market. <br>
<br>
Therefore, allowing share splits will bring higher per share quality stocks to 
more acceptable trading ranges, thus promoting liquidity in the market and 
attracting more foreign capital as well as new capital from the locals.<br>
<br>
<i>The author is Investment Manager, Al Madina Investment &amp; Financial Services. 
The views contained within this column are those of the author and do not 
necessarily represent those of OER or his employer. The publisher does not 
accept responsibility for any loss occasioned to any person or organisation 
acting or refraining as a result of material in this publication.</i></font></p>

                    <hr color="#CC3333">
                    </td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?>
        </body>
        </html>
        <?}
else 
Header("Location:/inc/error.php");
?>