<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - January/February 2001 ::</title>
</head>

<body topmargin="0" leftmargin="0">

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%" height="19">
<? include("../../inc/top.htm"); ?></td>
  </tr>
  <tr>
    <td width="100%" height="15">
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="19">
<?
                    include("../../inc/home_inc1.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="13" valign="middle">
      <font face="Verdana" size="1">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</font>
    </td>
  </tr>
  <tr>
    <td width="100%" valign="top" height="1911">
      <table border="0" width="100%" cellspacing="0" cellpadding="0">
        <tr>
          <td width="77%" height="181" valign="top">
            <div align="center">
              <center>
              <table border="0" width="90%" cellspacing="0" cellpadding="0">
                <tr>
                  <td width="100%"><font face="Verdana" size="4" color="#FF0000">Take off</font><p><font face="Verdana" size="2"><img border="0" src="../../images/2001_january_February/img3.jpg" align="left" hspace="5" vspace="5" width="175" height="256"></font><font face="Verdana" size="2">In 1999, the government engaged external consultants to prepare a two-stage expansion plan for Seeb International Airport, the Sultanate's main airport and the closest to Muscat. The first stage will see the airport increase its capacity to handle six million passengers a year by 2004. The second phase, to be completed by 2010, envisages a annual capacity of 10 million passengers annually. The government also wants a new terminal at Seeb and additional runway space. The overall cost of the project is seen at more than $US100 million.<br>
                    <br>
                    Under-Secretary for Economic Affairs HE Dr Abdulmalik Al-Hinai, who is chairman of the government's airport privatization steering committee, told OER the government decided development of the airports would best be achieved by creating a new airport company and selecting a private sector strategic partner to manage it.</font></p>
                    <p><font face="Verdana" size="2"><img border="0" src="../../images/2001_january_February/img6.jpg" align="left" hspace="5" vspace="5" width="250" height="158">In terms of the structure of the new airport company, initially the government will hold a 20% stake, Oman Aviation Services company (OASC) up to 5.0% and a strategic partner will have 75% (the strategic partnercould hold up to 80% depending on the size of stake - if any (OASC takes). Up to 60% of the new airport company can be held by foreign investors. Once the new airport company is up and running, Al-Hinai said the government is planning to dispose of its 20% stake on the Muscat Securities Market in an IPO.&nbsp;<br>
                    <br>
                    It's the 75% stake in the new company that is now up for grabs in the government's recently-announced tender, a stake it hopes to award by mid-2001. Al-Hinai said there is a misconception that the government is selling the airport.<br>
                    <br>
                    "There is no price on this transaction - no one is going to be handing over a cheque to the government on day one. Instead the government will receive an annual concession fee based on a percentage of revenue generated by the airport company," a spokesperson for the London-based office of Credit Suisse First Boston (CSFB), the government's consultants on the privatization, told OER, adding that this percentage figure would be decided upon at a later stage in the tender process.<br>
                    <br>
                    "We want a strategic investor who can invest in building an airport infrastructure and also who can attract more international airlines to Oman by way of improving the services that are provided for airlines in terms of both for passengers and for cargo,"said Al Hinai.<br>
                    "It's not just to make more revenue, it's one of the steps we are taking to stimulate the economy and it has been found that privatization in general increases efficiencies in economies," he added.<br>
                    <br>
                    Currently, Oman's airports, air traffic control service and related airspace and meteorological services are provided by the Directorate General of Civil Aviation and Meteorology (DGCAM). After the privatisation, DGCAM will remain Oman's Civil Aviation Authority and air traffic service provider.<br>
                    <br>
                    The government is particularly keen to have a new terminal built and in operation at Seeb by 2007. Al-Hinai said any potential strategic partner that can commit to developing the terminal will be looked upon at favourably. He added that tender award for concession sooner would go to the consortium which could best demonstrate excellent airport management experience and provide a clear, workable strategy to increase revenue by increasing the number of foreign airlines using the airports, increasing cargo and passenger numbers and from better commercial management of the terminal concessions such as duty free, restaurants and and other outlets.&nbsp;<br>
                    <br>
                    However, while airport services will improve, it is still unknown to what extent Seeb will expand.<br>
                    <br>
                    What Oman is not going to see is something the size of Dubai (airport's new terminal). There's only three million people going through Seeb and at last count 11 million going through Dubai. People (in Oman) can expect a very good, very efficient new terminal building, but a passenger terminal built for four to five million passengers will look very different compared to one built for 20 million passengers," the CSFB spokesperson said.<br>
                    <br>
                    Indeed, aviation industry sources have told OER that airport staff are worried that the privatization will lead to significant job losses at the airport.<br>
                    <br>
                    "They claim this but I think they will not," Al-Hinai says. "They are not going to lose a lot of their activities. We studied this and we found that a very limited number of people, if any at all, will be affected by the privatization."<br>
                    <br>
                    His view is supported by CSFB, whose spokesman said that in terms of spin-offs for the local economy, indirect job creation is seen as a benefit of airport privatisation.<br>
                    There is also concern that the privatization will have a major negative impact on Oman Aviation Services company, which currently manages the majority of airport services.&nbsp;<br>
                    OASC could not be contacted for comment, but Dr Al-Hinai said that OASC will be allowed to continue to "monopolise" its concession for inflight catering for 10 years and ground handling for five years.<br>
                    <br>
                    "After that, they will have to compete with other companies," he said. "The government is not imposing Oman Aviation on the new investor - the government is keen to see that Oman Aviation survives."&nbsp;<br>
                    According to CSFB, response to the tender so far has been excellent. However, one challenge Oman faces as an emerging market is convincing potential airport management groups that government expectations are realistic and the airport concession documentation is transparent enough to allow a profitable commercially focussed operation.<br>
                    While investors have had positive experiences with airport privatizations in developing countries such as Mexico and Bolivia, other privatizations in similar markets have been "enormously painful" for investors, the CSFB consultant says, mainly due to lack of preparation for privatization and bad process management by the relevant authorities.<br>
                    <br>
                    "At any given time there are a handful of airport privatizations going on around the world," CSFB says, adding that potential investors could look elsewhere if their initial experience in the Oman tender process is too prolonged or bureaucratic.<br>
                    <br>
                    However, the CSFB spokesman said there were a number of factors specific to Oman which were attracting potential strategic partners.<br>
                    <br>
                    Airport management companies are keen to exploit the 'first mover' advantage - establishing the first privately-managed and successful airports in the Gulf will provide the operator with an enormous advantage as similar opportunities in the region develop.&nbsp;<br>
                    <br>
                    In terms of country and political risk assessments, Oman's stable environment scores very highly in terms of investor perception compared to many other emerging markets beginning to privatize their airports, particularly in this region.<br>
                    <br>
                    There is also potential for solid growth in passenger numbers with two distinct markets identified - two billion people living on the Indian subcontinent are just a few hours' flight away from Oman and tourist traffic from Europe is increasing. Indeed, the average annual rate of passenger growth between 2000-2004 to/from Oman is seen at 3.9%. Added to this, population-wise the Sultanate is one of the fastest growing countries in the world, with a current population of 2.3 million, forecast to double by 2010.<br>
                    <br>
                    Finally, both Seeb and Salalah airports are established with, good aeronautical infrastructure to support them. While Seeb needs a new terminal, its runway is large - roughly the same size as London's Gatwick Airport which sees 40 million passengers annually and 30-40 aircraft movements per hour, compared to Seeb's 2.8 million passengers and average of five aircraft movements per hour.&nbsp;<br>
                    <br>
                    One sticking point, however, could be gaining investors'commitment to the development of the new terminal, the CSFB consultant said.<br>
                    <br>
                    "The single biggest objective for the government is to develop a new terminal at Seeb. Any airport operator in the world will say, 'We'll build you a new terminal, but only when it's feasible and that's when we have enough passengers going through'.&nbsp;<br>
                    <br>
                    "The original master plan had a new terminal in construction as we speak which would have cost hundreds of millions of dollars and would have been the single biggest construction project ever in Oman. Investors we have spoken to recognise the government's objective, but will need to assess the financial feasibility of the development and ensure there is a sufficient growth in passenger numbers to sustain the investment," the CSFB consultant said.<br>
                    <br>
                    A major plus for the strategic partner in Salalah Airport's privatization is the planned free trade zone at Salalah Port. According to one industry source, this is seen as being a "major competitor" to the UAE's free zones, as it is so much closer to international shipping routes.&nbsp;<br>
                    <br>
                    "Salalah may become quite a major airport - if you won the (Oman airport privatization) concession you'd be straight down to those developing the free zone to develop some type of link-up," the CSFB consultant said.<br>
                    <br>
                    In 1999, Seeb handled 2.8 million passengers. The average growth in passenger numbers at Seeb airport over the past five years (1994-1998) has been 5.69%, with cargo volumes up by 16.5% in 1998. In 1999, Salalah Airport saw just over 180,000 passengers. The Sultanate has six civil airports: Seeb, Salalah, Sur, Masairah, Khasab and Diba in the Musandam. These airports will remain under the control of the DGCA.</font></p>
                    <hr color="#CC3333">
                  </td>
                </tr>
                <tr>
                  <td width="100%"></td>
                </tr>
              </center>
                <tr>
                  <td width="100%"><? include("../../inc/menu1.htm");
?></td>
                </tr>
              <center>
                <tr>
                  <td width="100%"><font size="1">&nbsp;</font></td>
                </tr>
              </table>
              </center>
            </div>
          </td>
          <td width="25%" height="198" valign="top">
            <table border="0" width="100%" cellspacing="0" cellpadding="0" height="290">
              <tr>
                <td width="50%" height="61">
                  <p align="center"><img border="0" src="../../images/2001_january_February/cover.jpg" width="80" height="104"></td>
                <td width="50%" height="61">
                  <p align="center"><b><font face="Verdana" size="1" color="#FF0000">January/<br>
                  February<br>
 2000</font></b></td>
              </tr>
              <tr>
                <td width="101%" height="21" colspan="2"></td>
              </tr>
              <tr>
                <td width="101%" height="21" bgcolor="#CC3333" colspan="2">
                  <p align="left"><b><font face="Verdana" color="#FFFFFF" size="1">&nbsp;&nbsp;
                  Other Headlines</font></b></td>
              </tr>
              <tr>
                <td width="101%" height="116" valign="top" colspan="2">
                  <div align="right">
                    <table border="0" width="100%" cellspacing="0" cellpadding="0">
                      <tr>
                        <td width="100%" height="3"><font face="Verdana" size="1">&nbsp;</font></td>
                      </tr>
                      <tr>
                        <td width="100%"><font color="#CC3333" face="Verdana" size="1"><b><a href="cover.php">Muscat Securities Market</a></b></font><font face="Verdana" size="1"><b><font color="#CC3333"><br>
                          </font></b><br>
                          CMA President His Excellency Yahya Bin Said Al Jabri talks about the delayed cross-listing agreement...<br>
                          &nbsp;</font></td>
                      </tr>
                      <tr>
                        <td width="100%"><font face="Verdana" size="1"><b><font color="#CC3333"><a href="main1.php">Mideast violence unsettles oil market</a><br>
                          </font></b><br>
                          Markets hate nothing more than uncertainty. It's bad enough when that uncertainty revolves around economic factors...<br>
                          &nbsp;</font></td>
                      </tr>
                      <tr>
                        <td width="100%"></td>
                      </tr>
                    </table>
                  </div>
                </td>
              </tr>
              <tr>
                <td width="100%" height="14" style="border-top: 1 solid #000000" colspan="2">
                  <font face="Verdana" color="#008000" size="1">&nbsp;</font></td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <tr>
    <td width="100%" valign="top" height="61">

<table border="0" width="100%" cellspacing="0" cellpadding="0">
  <tr>
    <td width="100%">

                       </td>
  </tr>
  <tr>
    <td width="100%">

                    
 <? include("../../inc/bottom.htm");
?>                  </td>
  </tr>
</table>

    </td>
  </tr>
</table>

</body>

</html>
