

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - May - 2006 ::</title>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top1.php"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#EFEFE9" colspan="3" align=center height="10">
            <div align="left">
				<table border="0" style="border-collapse: collapse" width="19%" cellpadding="0">
					<tr>
						<td width="2" bgcolor="#FF0000" height="30" style="border-left-style: solid; border-left-width: 1px; border-right-width: 1px; border-top-width: 1px; border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#000000">&nbsp;</td>
						<td valign="bottom" style="border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#FF0000">
            <p align="left" style="margin-left: 5px">
			<span style="font-weight: 700">
			<font face="Verdana" style="font-size: 8pt"><a name="MARKET WATCH">MARKET WATCH</a></font></span></td>
					</tr>
				</table>
			</div>
			</td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">

<p align="justify" style="margin-right: 10px"><font face="Verdana" size="1"><br>
<br>
<b>Allure Sensuelle — the new perfume from Chanel<br>
</b><br>
<img border="1" src="mkt_watch1.jpg" align="right" width="150" height="148" hspace="5" vspace="2">Allure. 
The expression of one’s personality. An inner light, a fascinating charisma, an 
enigmatic grace that goes to the very essence of one’s being. When allure 
becomes sensual, it takes on a natural magnetism, a mysterious gaze, an elegant 
shape, the nuance of a feminine voice.<br>
<br>
Allure Sensuelle is a more sensuous and intimate interpretation of the Allure 
fragrance. Warm, voluptuous, mysterious...luminous and ethereal. A soft floral 
oriental, which suggests subtly, as if to exalt a natural sensuality and entice 
our emotions.<br>
<br>
Like Allure, Allure Sensuelle is constructed as an olfactory diamond, around six 
facets that unfurl and express themselves to give a unique, radiating aura to 
each woman. Six facets like the six letters of the word Allure that Jacques 
Polge has revisited to write a new story.</font></p>
<hr color="#800000" width="80%" size="1">

<p align="justify"><font face="Verdana" size="1"><b>‘Treasures from the Deep’ 
from Swarovski<br>
</b><br>
Immerse 
yourself in your own private underwater paradise and create an Ocean world, 
<img border="1" src="mkt_watch2.jpg" align="left" hspace="5" vspace="2">which you can change and rearrange using crystal objects. Existence and design. 
A sense of well-being is not generated by chance. On the contrary, comfort, 
simplicity and satisfaction result from good design, intelligent planning and 
creative application. <br>
<br>
Crystals create unusual highlights, which lend a personal touch and add a 
pleasant and friendly atmosphere to an ordinary living space. To make the best 
possible use of their vibrant effect, design experts recommend highlighting the 
variety of the crystal objects.<br>
The “Wonders of the Sea” trilogy is ideally suited to this type of varied 
display, imaginative arrangements and new ideas.</font></p>
<hr color="#800000" width="80%" size="1">

<p align="justify"><font face="Verdana" size="1"><b>Nokia N73—the ultimate 
challenge to digital camera<br>
</b><br>
<img border="0" src="mkt_watch3.jpg" align="right" width="75" height="149">Nokia 
has unveiled the latest addition to the Nokia Nseries family, the Nokia N73, a 
stunning multimedia computer in a compact and savvy exterior with exquisite 
photography features and integrated stereo speakers with 3D sound for optimized 
audio pleasure. In addition to a large 2.4 inch display, the Nokia N73 includes 
a 3.2 megapixel camera with Carl Zeiss optics, auto-focus and support for 
Internet communities like Flickr—a package ready to challenge any digital 
camera.<br>
<br>
“The ideal companion for the digital camera lover, the Nokia N73 is as easy to 
use as it is compact to carry. Imagine, stunning print quality photos and 
multimedia are just a slide and a click away, ready to be shared immediately, 
said Juha Putkiranta, senior vice president, Multimedia Computers, Nokia. <br>
<br>
“Being able to intuitively capture, edit and share your digital memories is at 
the core of the Nokia N73, which also offers the enriched multimedia experiences 
of the Nokia Nseries range.</font></p>

<p align="right"><b><font face="Verdana" size="1">
						<a href="#top">Top^</a></font></b></p>

                    <hr color="#CC3333">
                    </td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?>
        </body>
        </html>