



<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - January - 2011 ::</title>
<style type="text/css">
<!--
.style1 {
	color: #CC3300;
	font-weight: bold;
}
-->
</style>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../../inc/top1.php"); ?>  
<? include("../../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#EFEFE9" colspan="3" align=center height="10">
            <div align="left">
				<table border="0" style="border-collapse: collapse" width="154" cellpadding="0">
					<tr>
						<td width="10" bgcolor="#FF0000" height="30" style="border-left-style: solid; border-left-width: 1px; border-right-width: 1px; border-top-width: 1px; border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#000000">&nbsp;</td>
						<td valign="bottom" style="border-bottom-style: solid; border-bottom-width: 1px; padding-left: 4px; padding-right: 4px; padding-top: 1px; padding-bottom: 1px" bordercolor="#FF0000" width="128">
            <p align="left" style="margin-left: 5px"> <a name="top"><b>
			<font face="Verdana" style="font-size: 8pt">BY INVITATION</font></b></a></td>
					</tr>
				</table>
			</div>
			</td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	          <tr> 
                <td valign="top" width="100%"> 

<table border="0" cellpadding="0" cellspacing="0" width="100%">
	<tr>
		        <td valign="top" width="100%"> 
                  <p align="justify" style="margin: 3px 10px"> 
					<b><font face="Verdana" size="1" color="#C00000">&nbsp;<br>
					</font><font face="Verdana" size="4" color="#C00000">
					The power of great questions</font></b></p>
                </td>
		</tr>
	<tr>
		        <td valign="top" width="100%"> 
				<p align="justify" style="margin: 10px; ">
				<font face="Verdana" size="2"><b>The spill-over of ideas 
				generated by a great question can spread like wildfire 
				throughout the organisation<br>
&nbsp;</b></font><p align="justify" style="margin: 10px; ">
				<font face="Verdana" size="1">In my last column, I discussed the 
				benefits solution focused coaching can provide to businesses. 
				This month, I would like to introduce one of the vital elements 
				of managerial coaching: Great Questions. When managers and 
				executives unleash the power of Great Questions, enormous 
				potential is uncovered in teams and employees. This kind of 
				managerial methodology is often what separates hugely successful 
				corporate cultures from the rest.<br>
				<br>
				We immediately notice when someone asks us a great question. The 
				ideas flash, and we start to think on a new level. The question 
				takes us on a search and leads us into new territory. We all 
				have this ability to ask great questions and transform our 
				business.<br>
				<br>
				Why don’t most questions do this? It could be a closed question 
				with a yes/no answer. The person asking the question may have an 
				agenda or judgment about us. The question might lead us into the 
				past, where we are asked to explain, justify or rationalise our 
				choices. In business, such questions can stop all forward 
				movement for a team.<br>
				<br>
				What is the difference between asking and telling? Telling 
				people what to do is a necessary part of business. However, you 
				cannot tell someone how to be a great manager or leader, nor can 
				you tell them how to be creative or inspired. Giving advice 
				often comes from the belief that a person does not have ‘what it 
				takes’. We can avoid the creation of a defensive, 
				problem-oriented atmosphere by inspiring creative, 
				solution-focused thinking through the power of great questions.<br>
				<br>
				</font><font face="Verdana" size="2" color="#000080"><b>Open and 
				closed questions</b></font><font face="Verdana" size="1"><br>
				<br>
				What is the difference between open and closed questions? A 
				closed question can only be answered with a yes or a no. This 
				leads to a dead-end conversation. By their nature closed 
				questions tend to inhibit higher-level thinking and deeper 
				reflection. In business, closed questions will reduce 
				independent thinking, creativity and innovation. Open-ended 
				questions stimulate inquisitiveness, resourcefulness and deep 
				thinking. Open-ended questions offer people an opportunity to 
				move past any limiting ideas they have about themselves. This 
				allows people to come up with their own integral insights and 
				solutions. Open-ended questions build great managers, business 
				leaders and employees.<br>
				<br>
				The power of open-ended questions is that they lead to more 
				open-ended questions. For example, we conducted ‘Art &amp; Science 
				of Coaching’ for Canada Post, an organisation with 80,000 
				people. We measured the powerful ripple effect as the 
				questioning skillset moved out into the organisation. In our 
				management coach training programmes, accredited by the 
				International Coach Federation, the first challenge is to 
				immerse managers in the coaching conversation. The second 
				challenge is to build momentum through practice and focus. The 
				aim is to develop a bridge to get those coaching conversations 
				into the workplace.<br>
				<br>
				</font><font face="Verdana" size="2"><b><font color="#000080">
				High-level skills</font><br>
				</b></font><font face="Verdana" size="1"><br>
				<b>What are the key skills of a great 21st century manager? The 
				key low-level skills are operational: process, procedures and 
				information about the business. What are the key high-level 
				skills of a great manager?</b> </font>
				<ul>
					<li>
					<p align="justify" style="margin: 10px; ">
					<font face="Verdana" size="1">Building strong relationships is essential because trust is the 
				equity of teams. </font></li>
					<li>
					<p align="justify" style="margin: 10px; ">
					<font face="Verdana" size="1">Having breakthrough conversations is vital to create a shared 
				vision for what teams want. </font></li>
					<li>
					<p align="justify" style="margin: 10px; ">
					<font face="Verdana" size="1">Designing effective structures of accountability allows teams to 
				stay focused and make realistic promises.<br>Great Questions open the door to the development of these 
				high-level skills! </font></li>
				</ul>
				<p align="justify" style="margin: 10px; ">
				<font face="Verdana" size="1"><i><br>
				In affiliation with Prosper Management Consultancy</i> (
				<a href="http://www.prosper105.com">www.prosper105.com</a> )<br>&nbsp;</font></td>
		</tr>
	<tr>
		        <td valign="top" width="100%"> 
                  	<p align="right" style="margin: 3px 10px">
				<font face="Verdana" size="1"> 
				<br>
                    <a href="#top">
                    Top^</a></font><br>
                </td>
		</tr>
	</table>

				</td>
		</tr>
	          <tr> 
                <td valign="top" width="100%"> 

                    <hr color="#CC3333">
                </td>
		</tr>
	          <tr> 
                <td valign="top" width="100%">&nbsp; </td>
		</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	</table>

            </td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
</table>
        </body>
</html>