--INSERT WITH DESTINATION CATEGORY
--INSERT AS ROOT FAMILY

INSERT INTO TB_FAMILY 
	(
		FAMILY_NAME
	,	FOOT_NOTES
	,	PARENT_FAMILY_ID
	,	ROOT_FAMILY
	,	STATUS
	,	PRODUCT_TABLE_STRUCTURE
	,	DISPLAY_TABLE_HEADER
	,	CATEGORY_ID
	)
SELECT FAMILY_NAME
	,	FOOT_NOTES
	,	0
	,	1
	,	STATUS
	,	PRODUCT_TABLE_STRUCTURE
	,	DISPLAY_TABLE_HEADER
	,	'HHH2' 
FROM TB_FAMILY WHERE FAMILY_ID = 966619

--INSERT WITH NEW FAMILY ID
--GET THE SORT ORDER TO INSERT

DECLARE @NEW_FAMILY INT = SCOPE_IDENTITY();

INSERT INTO TB_CATALOG_FAMILY 
	(
		CATALOG_ID
	,	FAMILY_ID
	,	SORT_ORDER
	,	CATEGORY_ID
	)
SELECT 
		CATALOG_ID
	,	@NEW_FAMILY
	,	(SELECT MAX(SORT_ORDER)+1 FROM TB_CATALOG_FAMILY WHERE CATEGORY_ID = 'HHH2' AND CATALOG_ID=2)
	,	'HHH2' 
FROM TB_CATALOG_FAMILY WHERE FAMILY_ID =966619 AND CATALOG_ID=2

-------------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM TB_FAMILY WHERE FAMILY_ID = 966619
SELECT * FROM TB_CATALOG_FAMILY WHERE FAMILY_ID = 966619
SELECT MAX(SORT_ORDER)+1 FROM TB_CATALOG_FAMILY WHERE CATEGORY_ID = 'HHH2' AND CATALOG_ID=2

SELECT * FROM TB_CATALOG_FAMILY WHERE CATALOG_ID=2  AND CATALOG_ID<>1 AND FAMILY_ID=966616
SELECT SUBFAMILY_ID FROM TB_SUBFAMILY WHERE FAMILY_ID=966616
SELECT COUNT(*) FROM TB_SUBFAMILY WHERE SUBFAMILY_ID=966616
DELETE FROM TB_SUBFAMILY WHERE SUBFAMILY_ID=966616
SELECT MAX(SORT_ORDER) AS SORT_ORDER FROM TB_CATALOG_FAMILY WHERE FAMILY_ID<>966616 AND CATALOG_ID = 2 AND FAMILY_ID IN 
	(SELECT FAMILY_ID FROM TB_FAMILY WHERE FAMILY_ID<>966616 AND CATEGORY_ID ='HHH2')
UPDATE TB_CATALOG_FAMILY SET SORT_ORDER=3 WHERE CATALOG_ID=2  AND CATALOG_ID<>1 AND FAMILY_ID=966616



SELECT * FROM TE
INSERT INTO TE VALUES('QW')
PRINT SCOPE_IDENTITY()
INSERT INTO TE VALUES('QW')
PRINT SCOPE_IDENTITY()