--UPDATE TB_FAMILY SET CATEGORY_ID = @Category_ID WHERE FAMILY_ID = @Family_ID
INSERT INTO TB_FAMILY (FAMILY_NAME,FOOT_NOTES,PARENT_FAMILY_ID,ROOT_FAMILY,STATUS,PRODUCT_TABLE_STRUCTURE,DISPLAY_TABLE_HEADER,CATEGORY_ID)
SELECT FAMILY_NAME,FOOT_NOTES,PARENT_FAMILY_ID,ROOT_FAMILY,STATUS,PRODUCT_TABLE_STRUCTURE,DISPLAY_TABLE_HEADER,'HHH1' 
FROM TB_FAMILY WHERE FAMILY_ID = 966623

DECLARE @NEW_FAMILY INT = SCOPE_IDENTITY();

INSERT INTO TB_FAMILY (FAMILY_NAME,FOOT_NOTES,PARENT_FAMILY_ID,ROOT_FAMILY,STATUS,PRODUCT_TABLE_STRUCTURE,DISPLAY_TABLE_HEADER,CATEGORY_ID)
SELECT FAMILY_NAME,FOOT_NOTES,@NEW_FAMILY,0,STATUS,PRODUCT_TABLE_STRUCTURE,DISPLAY_TABLE_HEADER,'HHH1' 
FROM TB_FAMILY WHERE PARENT_FAMILY_ID = 966623

SELECT * FROM TB_FAMILY WHERE CATEGORY_ID = 'HHH2' AND PARENT_FAMILY_ID<>0 AND PARENT_FAMILY_ID = 966623

INSERT INTO TB_CATALOG_FAMILY (CATALOG_ID,FAMILY_ID,SORT_ORDER,CATEGORY_ID)
SELECT CATALOG_ID,FAMILY_ID,SORT_ORDER,'HHH1' FROM TB_CATALOG_FAMILY WHERE CATALOG_ID = 2 AND FAMILY_ID IN (966624,966625,966626)

SELECT MAX(SORT_ORDER) as SORT_ORDER FROM TB_CATALOG_FAMILY WHERE FAMILY_ID<>966623 AND CATALOG_ID = 2 AND FAMILY_ID IN (SELECT FAMILY_ID FROM TB_FAMILY WHERE FAMILY_ID<>966623 AND CATEGORY_ID ='HHH1')
--UPDATE TB_CATALOG_FAMILY SET CATEGORY_ID =N'HHH1' WHERE FAMILY_ID =966624 AND CATALOG_ID=2

SELECT * FROM TB_CATALOG_FAMILY WHERE CATALOG_ID = 2 AND FAMILY_ID IN 
(SELECT FAMILY_ID FROM TB_FAMILY WHERE PARENT_FAMILY_ID<>0 AND PARENT_FAMILY_ID = 966623)
SELECT * FROM TB_SUBFAMILY WHERE SUBFAMILY_ID = 966623