SELECT 
	TB_FAMILY.FAMILY_ID AS SUBFAMILY_ID
	, TB_FAMILY.FAMILY_NAME
	, TB_FAMILY.FOOT_NOTES
	, TB_FAMILY.PARENT_FAMILY_ID
	, TB_FAMILY.ROOT_FAMILY
	, TB_FAMILY.STATUS
	, TB_FAMILY_TABLE_STRUCTURE.FAMILY_TABLE_STRUCTURE
	, TB_FAMILY.CATEGORY_ID
	, TB_SUBFAMILY.SORT_ORDER 
FROM TB_FAMILY INNER JOIN TB_CATALOG_FAMILY ON TB_FAMILY.FAMILY_ID = TB_CATALOG_FAMILY.FAMILY_ID 
			   INNER JOIN TB_CATALOG_SECTIONS ON TB_FAMILY.CATEGORY_ID = TB_CATALOG_SECTIONS.CATEGORY_ID 
						AND TB_CATALOG_FAMILY.CATALOG_ID = TB_CATALOG_SECTIONS.CATALOG_ID
               INNER JOIN TB_SUBFAMILY ON TB_FAMILY.FAMILY_ID = TB_SUBFAMILY.SUBFAMILY_ID 
						AND TB_CATALOG_FAMILY.FAMILY_ID = TB_SUBFAMILY.SUBFAMILY_ID 
						AND TB_CATALOG_FAMILY.CATALOG_ID = TB_CATALOG_SECTIONS.CATALOG_ID,
						TB_FAMILY_TABLE_STRUCTURE WHERE TB_FAMILY_TABLE_STRUCTURE.CATALOG_ID=TB_CATALOG_SECTIONS.CATALOG_ID 
						AND TB_FAMILY_TABLE_STRUCTURE.FAMILY_ID=TB_FAMILY.FAMILY_ID 
						AND TB_FAMILY_TABLE_STRUCTURE.IS_DEFAULT=1 
						AND (TB_CATALOG_SECTIONS.CATALOG_ID =2) 
						AND (TB_CATALOG_SECTIONS.CATALOG_ID = TB_CATALOG_SECTIONS.CATALOG_ID) 
						AND (TB_FAMILY.PARENT_FAMILY_ID = 10778) 
							ORDER BY TB_SUBFAMILY.SORT_ORDER
							
							
SELECT CATEGORY_ID,PARENT_CATEGORY,CATEGORY_NAME FROM TB_CATEGORY 
	WHERE CATEGORY_ID = (SELECT DISTINCT CATEGORY_ID FROM TB_CATALOG_FAMILY WHERE FAMILY_ID = 10788  AND CATALOG_ID = 1)