SELECT FAMILY_ID FROM TB_PROJECT_SECTION_DETAILS 
	WHERE RECORD_ID IN 
(SELECT RECORD_ID FROM TB_PROJECT_SECTIONS WHERE  FILE_NO = 1 AND PROJECT_ID  = 41) ORDER BY SORT_ORDER

SELECT CATEGORY_ID,PARENT_CATEGORY,CATEGORY_NAME 
FROM TB_CATEGORY WHERE 
CATEGORY_ID = (SELECT DISTINCT CATEGORY_ID FROM TB_CATALOG_FAMILY WHERE FAMILY_ID = 10778  AND CATALOG_ID = 2)


SELECT CATEGORY_ID,PARENT_CATEGORY,CATEGORY_NAME 
FROM TB_CATEGORY WHERE CATEGORY_ID = 
(SELECT DISTINCT CATEGORY_ID FROM TB_CATALOG_FAMILY WHERE FAMILY_ID = 10778  AND CATALOG_ID = 3)


SELECT CATEGORY_ID,PARENT_CATEGORY,CATEGORY_NAME from TB_CATEGORY WHERE CATEGORY_ID = 'WES 1000'

SELECT * FROM TB_PROJECT_SECTIONS
SELECT * FROM TB_CATALOG
SELECT * FROM TB_CATALOG_SECTIONS
