SELECT TB_CATALOG.CATALOG_NAME, TB_CATALOG.VERSION, TB_CATALOG.DESCRIPTION, TB_CATEGORY.CATEGORY_NAME, 
TB_CATEGORY.SHORT_DESC, TB_CATEGORY.CUSTOM_NUM_FIELD1, TB_CATEGORY.CUSTOM_NUM_FIELD2, 
TB_CATEGORY.CUSTOM_NUM_FIELD3, TB_CATEGORY.CUSTOM_TEXT_FIELD1, TB_CATEGORY.CUSTOM_TEXT_FIELD3, 
TB_CATEGORY.CUSTOM_TEXT_FIELD2,TB_CATEGORY.IMAGE_FILE,TB_CATEGORY.IMAGE_TYPE,TB_CATEGORY.IMAGE_NAME,TB_CATEGORY.IMAGE_FILE2,TB_CATEGORY.IMAGE_TYPE2,TB_CATEGORY.IMAGE_NAME2
FROM TB_CATALOG CROSS JOIN TB_CATEGORY
WHERE (TB_CATALOG.CATALOG_ID IN (SELECT CATALOG_ID FROM TB_CATALOG_SECTIONS WHERE (CATALOG_ID = '1'))) AND (TB_CATEGORY.CATEGORY_ID IN 
(SELECT CATEGORY_ID FROM TB_CATALOG_SECTIONS AS TB_CATALOG_SECTIONS_1 WHERE (CATEGORY_ID = '000122')))

SELECT FAMILY_FILTERS FROM TB_CATALOG WHERE CATALOG_ID =1

