<?	session_start();?>
<?	session_register("id");
	if(!$HTTP_SESSION_VARS["id"]=="")
	{?>

<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>:: OER - March 2004 ::</title>
</head>

<body topmargin="0" leftmargin="0" rightmargin="0">


<table border="0" width="100%" cellspacing="0" cellpadding="0" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td width="100%">
<? include("../../inc/top1.php"); ?>  
<? include("../../inc/menu_gen.htm");
?></td>
  </tr>
  <tr>
    <td width="100%" height="21">
<?include("../../inc/home_inc1.htm");?></td>
  </tr>
  <tr>
    <td width="100%" height="15" valign="middle">
      <div align="center">
        <center>
        <table border="0" width="95%" bgcolor="#FFFCE8" cellspacing="0" cellpadding="5" style="border-collapse: collapse" bordercolor="#111111">
          <tr>
            <td width="100%" bgcolor="#FFFCE8" colspan="3" align=center><b>



<? if(!$HTTP_SESSION_VARS["id"]==""){echo "<font face=Verdana size=2 color=#000000>Welcome&nbsp;&nbsp;</font><font face=Verdana size=2 color=red><i>".$HTTP_SESSION_VARS["id"]."&nbsp;!</i></font>
            ";}else{echo$HTTP_SESSION_VARS["mes"];$HTTP_SESSION_VARS["mes"]="";}?>
              </b></td>
          </tr>
          <tr>
            <td width="1%" bgcolor="#FFFFFF">&nbsp;</td>
            <td width="70%" bgcolor="#FFFFFF" valign="top">
            <p align="justify"><font size="4" color="#FF0000" face="Verdana">
            Tech review<br>
                  </font><font face="Verdana" size="1"><b><br>
                  Siemens: Fuel cells will irreversibly alter the energy 
            landscape</b></font></p>
            <p align="center">
            <img border="0" src="im15.jpg" width="250" height="140"><br>
            <font face="Verdana" size="1">Fuel cells in the test laboratory: A 
            Siemens researcher measures the electrical characteristics of new 
            solid oxide fuel cells</font></p>
            <p align="justify"><font face="Verdana" size="1">Our energy landscape will undergo dramatic changes in coming
years. The liberalisation of markets, combined with efforts
to reduce greenhouse gases, will lead to a decentralization of
electric power generation. And, according to the German
telecommunications company Siemens, fuel cells will play an
important role in this scenario - not least because they may
reduce the size of our mobile handsets by at least 10 times and
one day power central electricity grids.
<br>
            <br>
            &quot;If you want to know what the future of electric power
will be like, look to the past. Electrification did not begin its
triumphant advance with large, centralised power plants like
the ones that power the globe today, but with electric generators
driven by mill wheels, steam engines and combustion
engines,&quot; explains Norbert Aschenbrenner, a scientist working
for Siemens. &quot;Whether mobile or stationary, the fuel cell
will-in the not-too-distant future-change the way power is
supplied. But this will tend to be a gentle revolution because
of high initial production costs.&quot;
<br>
            <br>
            Today, however, the watchword is decentralisation. RWE,
Germany's largest electric power company, is even showing
advertisements that envisage a fuel cell bought in a supermarket.
RWE predicts that by 2015 about 10 per cent of electricity
in Germany will be generated by fuel cells. The company
plans to market compact power plants for private households
by 2010. In the US, companies like Ballard Power, Plug
Power, H-Power and Fuel Cell Technologies are crowding
into the market. Siemens Westinghouse is building a plant in
Pittsburgh, Pennsylvania that will produce fuel cells. In
Switzerland, Sulzer Hexis has embraced the concept of distributed
power generation with fuel cells. And German heating
system specialist
Vaillant has teamed
up with New Jerseybased
Plug Power to
develop a fuel cell for
power and heat generation
in everyone's
basement.
<br>
            <br>
            &quot;All the players
understand that energy
is the key to continuing
economic and,
above all, sustainable
development, especially
in the long
term,&quot; says Dr.
Thomas Hamacher at
the Max Planck
Institute for Plasma
Physics, Germany.
Energy demand is
expected to continue to increase. Realistically, up to 10 billion
people will require electricity in 2050. The required investments
should, however, be kept within manageable limits.
And what's more, &quot;The risks must be manageable and acceptable.&quot;<br>
            <br>
            Rosenbauer believes that domestic fuel cells, smaller fuel
cell power plants and renewable energy sources will supply
power in an intelligent alliance with large power plants.
These distributed power systems will feed any excess production
into the power grid-a feature that will necessitate a
sophisticated management system. Many smaller fuel cells,
interconnected to form a virtual power plant, would even
provide grid companies with the opportunity to use a selective
control system to stabilise the network and thus minimise
losses. Operating costs can also be reduced, as it will be possible
to monitor mini power plants from a central control
room and coordinate maintenance activities.
<br>
            <br>
            In PEM (polymer electrolyte membrane) cells, hydrogen
atoms surrender their electrons, diffuse through a plastic
membrane and react with atmospheric oxygen on the other
side. Prototypes already exist in Siemens laboratories for PEM
fuel cells that are particularly suitable for use in automobiles
and even as mini cells in mobile phones and laptops, but cost,
size and weight are even more critical in such applications
than in stationary use. However, PEM fuel cells have an interesting
niche market in submarines. In 2004, the German navy
will begin to operate the first submarine equipped with a
Siemens fuel cell weighing some eight tons. Here, the principal
advantage of fuel cell drives is that submarines can stay
underwater much longer than with lead batteries.
                  </font></p>
                    <hr color="#CC3333">
                    <p>&nbsp;</td>
            <td  valign=top bgcolor=white><?include("right_include.php");?>&nbsp;</td>
          </tr>
          
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        </table>
        <? include("../../inc/menu1.htm");?>
        <? include("../../inc/bottom.htm");?>
        </body>
        </html>
        <?}
else 
Header("Location:/inc/error.php");
?>